//! Contracts between the Rust workflow model and the TypeScript graph mapper
//! that types cannot express.
//!
//! `webcomponents/src/workflow/issuetype-to-ir.ts` is typed against the
//! **generated** bindings (`bindings/StepSchema.ts`, `StepTypeTag.ts`,
//! `IssueType.ts`), produced from `src/templates/schema.rs` and
//! `src/issuetypes/schema.rs` by ts-rs. So the type-shape questions this file
//! used to grep for are now compile errors instead:
//!
//! * a new `StepTypeTag` variant fails the mapper's exhaustive `switch`
//!   (`const unhandled: never = type`), and
//! * a renamed or removed `StepSchema` field fails every read of it.
//!
//! What remains here is the part the compiler cannot check: that the mapper
//! keeps deriving its types from Rust rather than re-introducing a hand-written
//! mirror, and that its ordering rule still matches the exporter's.

use std::path::PathBuf;

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn read(relative: &str) -> String {
    let path = repo_root().join(relative);
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()))
}

const MAPPER: &str = "webcomponents/src/workflow/issuetype-to-ir.ts";

/// The whole point of generating the bindings: the mapper must not go back to
/// declaring its own copy of the Rust types.
#[test]
fn test_mapper_is_typed_against_generated_bindings() {
    let mapper = read(MAPPER);

    for generated in [
        "../generated/IssueType",
        "../generated/StepSchema",
        "../generated/StepTypeTag",
    ] {
        assert!(
            mapper.contains(generated),
            "{MAPPER} should import its domain types from '{generated}' (generated by ts-rs \
             into bindings/ and copied to src/generated/ by scripts/copy-types.mjs)"
        );
    }

    assert!(
        !repo_root()
            .join("webcomponents/src/workflow/types.ts")
            .exists(),
        "webcomponents/src/workflow/types.ts is back. Domain types are generated from Rust — \
         add the field or variant in src/templates/schema.rs (or src/issuetypes/schema.rs) \
         and regenerate with `make bindings`, rather than hand-mirroring it."
    );
}

/// The mapper's exhaustive `switch` is what turns a new Rust step type into a
/// TypeScript compile error. Without the `never` binding it silently degrades
/// to ignoring the new variant.
#[test]
fn test_mapper_switch_is_exhaustive_over_step_types() {
    let mapper = read(MAPPER);
    assert!(
        mapper.contains("const unhandled: never = type"),
        "{MAPPER} must keep its `never` exhaustiveness check — it is what makes a new \
         StepTypeTag variant fail the webcomponents typecheck instead of being dropped \
         from the graph"
    );
}

/// Step ordering is a behavioral contract shared with the exporter: follow the
/// `next_step` chain, then append whatever it never reached. If the Rust side
/// stops defining it, the mapper's copy of the rule needs revisiting.
#[test]
fn test_mapper_mirrors_the_rust_step_ordering_rule() {
    let mapper = read(MAPPER);
    assert!(
        mapper.contains("orderedSteps"),
        "{MAPPER} should implement and name an ordering function mirroring `ordered_steps`"
    );
    assert!(
        read("src/workflow_gen/export.rs").contains("fn ordered_steps"),
        "src/workflow_gen/export.rs no longer defines `ordered_steps` — the TypeScript \
         mapper's ordering rule was written to mirror it and needs revisiting"
    );
}

/// The copy step is the link between `bindings/` and the components; without it
/// the package would typecheck against whatever happened to be in `src/generated/`.
#[test]
fn test_generated_types_are_copied_before_every_compile_step() {
    let pkg: serde_json::Value =
        serde_json::from_str(&read("webcomponents/package.json")).expect("package.json parses");
    let scripts = pkg["scripts"].as_object().expect("scripts object");

    for step in ["typecheck", "test", "build"] {
        let script = scripts[step].as_str().unwrap_or("");
        assert!(
            script.contains("copy-types"),
            "webcomponents `{step}` script must run copy-types first so it cannot compile \
             against missing or stale generated types (got: {script:?})"
        );
    }

    assert!(
        repo_root()
            .join("webcomponents/scripts/copy-types.mjs")
            .is_file(),
        "webcomponents/scripts/copy-types.mjs is missing"
    );
}

/// `make webcomponents` must regenerate bindings first, so the ordering holds
/// for `make ui` and `make docs` too (both depend on it).
#[test]
fn test_make_generates_bindings_before_building_the_frontend() {
    let makefile = read("Makefile");
    assert!(
        makefile.contains("bindings:"),
        "Makefile should expose a `bindings` target that runs the ts-rs export tests"
    );
    assert!(
        makefile.contains("webcomponents: bindings"),
        "`make webcomponents` must depend on `bindings`, so the components are always \
         built against freshly generated types"
    );
}

/// Every type the mapper reads must actually be generated. Catches someone
/// dropping `#[ts(export)]` from a domain type.
#[test]
fn test_workflow_domain_types_are_exported_to_bindings() {
    for name in [
        "IssueType",
        "StepSchema",
        "StepTypeTag",
        "ReviewType",
        "OnReject",
        "MultiModelConfig",
        "MultiPromptConfig",
        "MatrixedConfig",
        "PipelineConfig",
        "PipelineStage",
        "DelegatorStepConfig",
    ] {
        let path = repo_root().join(format!("bindings/{name}.ts"));
        assert!(
            path.is_file(),
            "bindings/{name}.ts is missing — the Rust type lost its `#[ts(export)]`. \
             Regenerate with `make bindings`."
        );
    }
}

/// A generated file that drifts from its Rust source is worse than no
/// generation at all, so the header must survive to warn against hand-edits.
#[test]
fn test_generated_bindings_are_marked_generated() {
    for name in ["IssueType", "StepSchema", "StepTypeTag"] {
        let contents = read(&format!("bindings/{name}.ts"));
        assert!(
            contents.contains("generated by [ts-rs]") && contents.contains("Do not edit"),
            "bindings/{name}.ts lost its generated-file header"
        );
    }
}
