//! Orchestration: render a ticket against its issuetype into a Claude
//! dynamic-workflow `.js` source string.

use anyhow::{Context, Result};
use handlebars::Handlebars;
use serde_json::Value;

use super::js;
use super::step_map;
use super::GAP_MARKER;
use crate::issuetypes::IssueType;
use crate::pr_config::PrConfig;
use crate::queue::Ticket;
use crate::steps::manager::StepManager;
use crate::templates::schema::{RagSource, ReviewType, StepSchema, StepTypeTag};

/// Render `ticket` against `issuetype` into a concrete Claude dynamic-workflow
/// `.js` source string.
///
/// Deterministic: the output never contains wall-clock, `Date.now`, or
/// `Math.random`, so the same inputs always produce byte-identical output.
pub fn export_workflow(
    ticket: &Ticket,
    issuetype: &IssueType,
    pr_config: Option<&PrConfig>,
) -> Result<String> {
    // Reuse the exact variable surface a step prompt sees at launch time.
    let ctx = StepManager::build_ticket_context(ticket, pr_config);

    let mut hbs = Handlebars::new();
    hbs.set_strict_mode(false);
    hbs.register_escape_fn(handlebars::no_escape);

    let steps = ordered_steps(issuetype);

    let mut out = String::new();
    out.push_str(&provenance_header(ticket, issuetype));
    out.push_str(&meta_block(ticket, issuetype, &steps));
    out.push_str("export default async function () {\n");
    for step in &steps {
        out.push_str(&render_step(&hbs, &ctx, step)?);
    }
    out.push_str("}\n");
    Ok(out)
}

/// Order steps by following the `next_step` chain from the first step, then
/// appending any steps not reachable that way (in declaration order).
fn ordered_steps(it: &IssueType) -> Vec<&StepSchema> {
    let mut order: Vec<&StepSchema> = Vec::new();
    let mut seen: std::collections::HashSet<&str> = std::collections::HashSet::new();

    let mut current = it.first_step();
    while let Some(step) = current {
        if !seen.insert(step.name.as_str()) {
            break;
        }
        order.push(step);
        current = step.next_step.as_deref().and_then(|n| it.get_step(n));
    }
    for step in &it.steps {
        if seen.insert(step.name.as_str()) {
            order.push(step);
        }
    }
    order
}

fn render(hbs: &Handlebars, template: &str, ctx: &Value) -> Result<String> {
    hbs.render_template(template, ctx)
        .context("failed to render step prompt for workflow export")
}

fn provenance_header(ticket: &Ticket, it: &IssueType) -> String {
    format!(
        "/* ───────────── OPERATOR PROVENANCE (audit) ─────────────\n\
         \x20* Generated by: operator workflow export\n\
         \x20* Ticket:    {id}  ({ttype}, project {project})\n\
         \x20* Issuetype: {key} — {name}\n\
         \x20* NOTE: autonomous flattening of an operator issuetype. Human review_type/on_reject\n\
         \x20*       gates are emitted as judge-agent loops (see {gap} markers below). One operator\n\
         \x20*       step = a full session; one agent() call = one background subagent.\n\
         \x20* ──────────────────────────────────────────────────────── */\n",
        id = js::comment_safe(&ticket.id),
        ttype = js::comment_safe(&ticket.ticket_type),
        project = js::comment_safe(&ticket.project),
        key = js::comment_safe(&it.key),
        name = js::comment_safe(&it.name),
        gap = GAP_MARKER,
    )
}

fn meta_block(ticket: &Ticket, it: &IssueType, steps: &[&StepSchema]) -> String {
    let name = if ticket.summary.is_empty() {
        format!("{} — {}", ticket.id, it.name)
    } else {
        format!("{} — {}", ticket.id, ticket.summary)
    };
    let description = format!("{}: {}", it.name, it.description);

    let mut phases = String::new();
    for step in steps {
        phases.push_str(&format!(
            "    {{ title: {} }},\n",
            js::quote(step.display_name())
        ));
    }

    format!(
        "export const meta = {{\n  name: {name},\n  description: {desc},\n  phases: [\n{phases}  ],\n}};\n\n",
        name = js::quote(&name),
        desc = js::quote(&description),
        phases = phases,
    )
}

fn render_step(hbs: &Handlebars, ctx: &Value, step: &StepSchema) -> Result<String> {
    let var = step_map::result_var(&step.name);
    let prompt = render(hbs, &step.prompt, ctx)?;
    let has_review = step.requires_review() || step.on_reject.is_some();

    let mut s = String::new();
    s.push_str(&format!(
        "  await phase({});\n",
        js::quote(step.display_name())
    ));

    match step.step_type {
        StepTypeTag::Task | StepTypeTag::Delegator => {
            // A delegator step may prepend prompt flavor and pin a model.
            let mut effective_prompt = prompt.clone();
            let mut model: Option<String> = step.agent.clone();
            if step.step_type == StepTypeTag::Delegator {
                if let Some(cfg) = &step.delegator_config {
                    model = Some(cfg.delegator.clone());
                    if let Some(flavor) = &cfg.prompt_flavor {
                        let rendered_flavor = render(hbs, flavor, ctx)?;
                        effective_prompt = format!("{rendered_flavor}\n\n{prompt}");
                    }
                }
            }
            if !step.allowed_tools.is_empty() {
                s.push_str(&format!(
                    "  // allowed tools: {}\n",
                    step.allowed_tools.join(", ")
                ));
            }
            if has_review {
                s.push_str(&judge_loop(step, &var, &effective_prompt, model.as_deref()));
            } else {
                s.push_str(&agent_call(
                    &var,
                    &effective_prompt,
                    &step.name,
                    model.as_deref(),
                ));
            }
        }
        StepTypeTag::Classifier => {
            let schema = if let Some(explicit) = &step.json_schema {
                explicit.clone()
            } else if let Some(cfg) = &step.classifier_config {
                step_map::classifier_schema(cfg)
            } else {
                serde_json::json!({ "type": "object" })
            };
            let schema_str = serde_json::to_string(&schema).unwrap_or_else(|_| "{}".to_string());
            s.push_str(&format!(
                "  const {var} = await agent({prompt}, {{ label: {label}, schema: {schema} }});\n",
                prompt = js::quote(&prompt),
                label = js::quote(&step.name),
                schema = schema_str,
            ));
            if has_review {
                s.push_str(&review_comment(step));
            }
        }
        StepTypeTag::MultiModel => {
            s.push_str(&render_multi_model(hbs, ctx, step, &var, &prompt)?);
        }
        StepTypeTag::MultiPrompt => {
            s.push_str(&render_multi_prompt(hbs, ctx, step, &var)?);
        }
        StepTypeTag::Matrixed => {
            s.push_str(&render_matrixed(hbs, ctx, step, &var)?);
        }
        StepTypeTag::Rag => {
            s.push_str(&format!(
                "  // {GAP_MARKER}: rag step — the workflow sandbox has no filesystem; context sources must be gathered by the agent.\n"
            ));
            if let Some(cfg) = &step.rag_config {
                let srcs: Vec<String> = cfg.sources.iter().map(describe_rag_source).collect();
                if !srcs.is_empty() {
                    s.push_str(&format!("  // context sources: {}\n", srcs.join(", ")));
                }
            }
            s.push_str(&agent_call(&var, &prompt, &step.name, None));
        }
        StepTypeTag::Mcp => {
            s.push_str(&format!(
                "  // {GAP_MARKER}: mcp step — the workflow sandbox cannot guarantee MCP tool availability.\n"
            ));
            if let Some(cfg) = &step.mcp_config {
                let tools: Vec<String> = cfg
                    .required_tools
                    .iter()
                    .map(|t| match &t.tool {
                        Some(tool) => format!("{}/{}", t.server, tool),
                        None => t.server.clone(),
                    })
                    .collect();
                if !tools.is_empty() {
                    s.push_str(&format!("  // required tools: {}\n", tools.join(", ")));
                }
            }
            s.push_str(&agent_call(&var, &prompt, &step.name, None));
        }
    }

    s.push('\n');
    Ok(s)
}

/// A single `const r_x = await agent("...", { label, [model] });` line.
fn agent_call(var: &str, prompt: &str, label: &str, model: Option<&str>) -> String {
    let mut opts = format!("label: {}", js::quote(label));
    if let Some(m) = model {
        opts.push_str(&format!(", model: {}", js::quote(m)));
    }
    format!(
        "  const {var} = await agent({prompt}, {{ {opts} }});\n",
        prompt = js::quote(prompt),
    )
}

fn review_label(review: &ReviewType) -> &'static str {
    match review {
        ReviewType::None => "output",
        ReviewType::Plan => "plan",
        ReviewType::Visual => "visual",
        ReviewType::Pr => "pr",
    }
}

/// Autonomous judge-agent retry loop standing in for a human review gate.
fn judge_loop(step: &StepSchema, var: &str, prompt: &str, model: Option<&str>) -> String {
    let review = review_label(&step.review_type);
    let goto = step
        .on_reject
        .as_ref()
        .map(|r| r.goto_step.clone())
        .unwrap_or_else(|| step.name.clone());

    let mut opts = format!("label: {}", js::quote(&step.name));
    if let Some(m) = model {
        opts.push_str(&format!(", model: {}", js::quote(m)));
    }

    format!(
        "  // {gap}: step {name} had human review_type={review}; a human gate cannot run mid-workflow.\n\
         \x20 // Emitted as an autonomous judge loop (max 3 attempts); original on_reject -> goto {goto}.\n\
         \x20 let {var};\n\
         \x20 let {var}_attempt = 0;\n\
         \x20 do {{\n\
         \x20   {var} = await agent({prompt}, {{ {opts} }});\n\
         \x20   var {var}_verdict = await agent({judge} + JSON.stringify({var}), {{ label: {jlabel} }});\n\
         \x20 }} while (String({var}_verdict).includes(\"REVISE\") && ++{var}_attempt < 3);\n\
         \x20 log({logmsg});\n",
        gap = GAP_MARKER,
        name = js::quote(&step.name),
        review = js::quote(review),
        goto = js::quote(&goto),
        var = var,
        prompt = js::quote(prompt),
        opts = opts,
        judge = js::quote(
            "Review the previous step's output against its acceptance criteria. Reply with PASS or REVISE and the reasons.\n\nOutput:\n"
        ),
        jlabel = js::quote(&format!("{}-review", step.name)),
        logmsg = js::quote(&format!(
            "{GAP_MARKER}: step '{}' review was autonomous; a human gate (review_type={review}, on_reject->goto {goto}) was flattened.",
            step.name
        )),
    )
}

fn review_comment(step: &StepSchema) -> String {
    format!(
        "  // {GAP_MARKER}: step '{}' carries review_type={}; verify its output before relying on it.\n",
        step.name,
        review_label(&step.review_type),
    )
}

fn render_multi_model(
    hbs: &Handlebars,
    ctx: &Value,
    step: &StepSchema,
    var: &str,
    prompt: &str,
) -> Result<String> {
    let Some(cfg) = &step.multi_model_config else {
        return Ok(agent_call(var, prompt, &step.name, None));
    };
    let mut branches = String::new();
    for d in &cfg.delegators {
        branches.push_str(&format!(
            "    () => agent({prompt}, {{ model: {model} }}),\n",
            prompt = js::quote(prompt),
            model = js::quote(d),
        ));
    }
    let vote_prompt = match &cfg.voting_prompt {
        Some(p) => render(hbs, p, ctx)?,
        None => {
            "Review the candidate answers and select or synthesize the single best one.".to_string()
        }
    };
    let strategy = serde_json::to_string(&cfg.voting_strategy).unwrap_or_default();
    Ok(format!(
        "  // multi-model fan-out + vote (voting_strategy: {strategy})\n\
         \x20 const {var} = await parallel([\n{branches}  ]).then(answers =>\n\
         \x20   agent({vote} + JSON.stringify(answers), {{ label: {label} }}));\n",
        var = var,
        branches = branches,
        vote = js::quote(&format!("{vote_prompt}\n\nCandidate answers:\n")),
        label = js::quote(&format!("{}-vote", step.name)),
    ))
}

fn render_multi_prompt(
    hbs: &Handlebars,
    ctx: &Value,
    step: &StepSchema,
    var: &str,
) -> Result<String> {
    let Some(cfg) = &step.multi_prompt_config else {
        let prompt = render(hbs, &step.prompt, ctx)?;
        return Ok(agent_call(var, &prompt, &step.name, None));
    };
    let mut branches = String::new();
    for variation in &cfg.prompt_variations {
        let rendered = render(hbs, variation, ctx)?;
        branches.push_str(&format!("    () => agent({}),\n", js::quote(&rendered)));
    }
    let select_prompt = match &cfg.selection_prompt {
        Some(p) => render(hbs, p, ctx)?,
        None => "Review the candidate outputs and select the single best one.".to_string(),
    };
    let strategy = serde_json::to_string(&cfg.selection_strategy).unwrap_or_default();
    Ok(format!(
        "  // multi-prompt variations + select (selection_strategy: {strategy})\n\
         \x20 const {var} = await parallel([\n{branches}  ]).then(outputs =>\n\
         \x20   agent({select} + JSON.stringify(outputs), {{ label: {label} }}));\n",
        var = var,
        branches = branches,
        select = js::quote(&format!("{select_prompt}\n\nCandidate outputs:\n")),
        label = js::quote(&format!("{}-select", step.name)),
    ))
}

fn render_matrixed(hbs: &Handlebars, ctx: &Value, step: &StepSchema, var: &str) -> Result<String> {
    let Some(cfg) = &step.matrixed_config else {
        let prompt = render(hbs, &step.prompt, ctx)?;
        return Ok(agent_call(var, &prompt, &step.name, None));
    };
    let rendered_variations: Vec<String> = cfg
        .prompt_variations
        .iter()
        .map(|v| render(hbs, v, ctx))
        .collect::<Result<_>>()?;

    let format_str = serde_json::to_string(&cfg.output_format).unwrap_or_default();
    let mut rows = String::new();
    for d in &cfg.delegators {
        let mut cells = String::new();
        for v in &rendered_variations {
            cells.push_str(&format!(
                "      () => agent({prompt}, {{ model: {model} }}),\n",
                prompt = js::quote(v),
                model = js::quote(d),
            ));
        }
        rows.push_str(&format!("    () => parallel([\n{cells}    ]),\n"));
    }
    Ok(format!(
        "  // matrixed {n}x{m} (delegators x prompt variations, output_format: {format_str})\n\
         \x20 const {var} = await parallel([\n{rows}  ]);\n",
        n = cfg.delegators.len(),
        m = rendered_variations.len(),
        var = var,
        rows = rows,
    ))
}

fn describe_rag_source(src: &RagSource) -> String {
    match src {
        RagSource::Glob { pattern } => format!("glob:{pattern}"),
        RagSource::File { path } => format!("file:{path}"),
        RagSource::Mcp { server, tool, .. } => format!("mcp:{server}/{tool}"),
    }
}
