//! Orchestration: render a ticket against its issuetype into a Claude
//! dynamic-workflow `.js` source string.

use anyhow::{Context, Result};
use handlebars::Handlebars;
use serde_json::Value;

use super::js;
use super::step_map;
use super::GAP_MARKER;
use crate::issuetypes::IssueType;
use crate::pr_config::PrConfig;
use crate::queue::Ticket;
use crate::steps::manager::StepManager;
use crate::templates::schema::{ItemSource, RagSource, ReviewType, StepSchema, StepTypeTag};

/// Environment inputs needed to resolve pipeline item sources that depend on
/// the machine (project list, glob root). Absent entries (e.g. the issuetype
/// preview path) make those sources fall back to a GAP-marked placeholder.
///
/// Resolving these at export time bakes machine state into the artifact: the
/// export is deterministic *given the same project/filesystem environment* —
/// the same conditional that already applies to step-output loading in
/// `build_ticket_context` — and the output still never contains wall-clock or
/// randomness.
#[derive(Debug, Clone, Default)]
pub struct PipelineEnv {
    /// Configured/discovered project names for `item_source: projects`.
    pub projects: Vec<String>,
    /// Root directory against which `item_source: glob` patterns expand.
    pub glob_root: Option<std::path::PathBuf>,
}

/// Render `ticket` against `issuetype` into a concrete Claude dynamic-workflow
/// `.js` source string.
///
/// Deterministic given the same project/filesystem environment: the output
/// never contains wall-clock, `Date.now`, or `Math.random`, so the same inputs
/// in the same environment always produce byte-identical output.
pub fn export_workflow(
    ticket: &Ticket,
    issuetype: &IssueType,
    pr_config: Option<&PrConfig>,
    pipeline_env: &PipelineEnv,
) -> Result<String> {
    // Reuse the exact variable surface a step prompt sees at launch time.
    let ctx = StepManager::build_ticket_context(ticket, pr_config);

    let hbs = handlebars_renderer();

    let steps = ordered_steps(issuetype);

    // The body is emitted as TOP-LEVEL statements (after `export const meta`),
    // NOT wrapped in `export default async function () { ... }`. This is the
    // form the `@untra/naiveworkflow-compiler` walks — a wrapped body compiles
    // to an empty graph — and mirrors the top-level shape of the Claude
    // Workflow-tool format.
    let mut out = String::new();
    out.push_str(&provenance_header(ticket, issuetype));
    out.push_str(&meta_block(ticket, issuetype, &steps));
    for step in &steps {
        out.push_str(&render_step(&hbs, &ctx, step, pipeline_env)?);
    }
    Ok(out)
}

/// A Handlebars renderer configured the way every workflow emitter needs it:
/// non-strict (missing vars render empty) with escaping disabled (the emitters
/// do their own JS/JSON-literal escaping). Shared by the `.js` and AGNT targets.
pub(super) fn handlebars_renderer() -> Handlebars<'static> {
    let mut hbs = Handlebars::new();
    hbs.set_strict_mode(false);
    hbs.register_escape_fn(handlebars::no_escape);
    hbs
}

/// Order steps by following the `next_step` chain from the first step, then
/// appending any steps not reachable that way (in declaration order).
pub(super) fn ordered_steps(it: &IssueType) -> Vec<&StepSchema> {
    let mut order: Vec<&StepSchema> = Vec::new();
    let mut seen: std::collections::HashSet<&str> = std::collections::HashSet::new();

    let mut current = it.first_step();
    while let Some(step) = current {
        if !seen.insert(step.name.as_str()) {
            break;
        }
        order.push(step);
        current = step.next_step.as_deref().and_then(|n| it.get_step(n));
    }
    for step in &it.steps {
        if seen.insert(step.name.as_str()) {
            order.push(step);
        }
    }
    order
}

fn render(hbs: &Handlebars, template: &str, ctx: &Value) -> Result<String> {
    hbs.render_template(template, ctx)
        .context("failed to render step prompt for workflow export")
}

fn provenance_header(ticket: &Ticket, it: &IssueType) -> String {
    format!(
        "/* ───────────── OPERATOR PROVENANCE (audit) ─────────────\n\
         \x20* Generated by: operator workflow export\n\
         \x20* Ticket:    {id}  ({ttype}, project {project})\n\
         \x20* Issuetype: {key} — {name}\n\
         \x20* NOTE: autonomous flattening of an operator issuetype. Human review_type/on_reject\n\
         \x20*       gates are emitted as judge-agent loops (see {gap} markers below). One operator\n\
         \x20*       step = a full session; one agent() call = one background subagent.\n\
         \x20* ──────────────────────────────────────────────────────── */\n",
        id = js::comment_safe(&ticket.id),
        ttype = js::comment_safe(&ticket.ticket_type),
        project = js::comment_safe(&ticket.project),
        key = js::comment_safe(&it.key),
        name = js::comment_safe(&it.name),
        gap = GAP_MARKER,
    )
}

/// The workflow's display name: `<ticket-id> — <summary>` (falling back to the
/// issuetype name when the ticket has no summary). Shared by the `.js` `meta`
/// block and the AGNT workflow `name`.
pub(super) fn meta_name(ticket: &Ticket, it: &IssueType) -> String {
    if ticket.summary.is_empty() {
        format!("{} — {}", ticket.id, it.name)
    } else {
        format!("{} — {}", ticket.id, ticket.summary)
    }
}

/// The workflow's description: `<issuetype name>: <issuetype description>`.
/// Shared by the `.js` `meta` block and the AGNT workflow `description`.
pub(super) fn meta_description(it: &IssueType) -> String {
    format!("{}: {}", it.name, it.description)
}

fn meta_block(ticket: &Ticket, it: &IssueType, steps: &[&StepSchema]) -> String {
    let name = meta_name(ticket, it);
    let description = meta_description(it);

    let mut phases = String::new();
    for step in steps {
        phases.push_str(&format!(
            "    {{ title: {} }},\n",
            js::quote(step.display_name())
        ));
    }

    format!(
        "export const meta = {{\n  name: {name},\n  description: {desc},\n  phases: [\n{phases}  ],\n}};\n\n",
        name = js::quote(&name),
        desc = js::quote(&description),
        phases = phases,
    )
}

fn render_step(
    hbs: &Handlebars,
    ctx: &Value,
    step: &StepSchema,
    pipeline_env: &PipelineEnv,
) -> Result<String> {
    let var = step_map::result_var(&step.name);
    let prompt = render(hbs, &step.prompt, ctx)?;
    let has_review = step.requires_review() || step.on_reject.is_some();

    let mut s = String::new();
    s.push_str(&format!(
        "await phase({});\n",
        js::quote(step.display_name())
    ));

    match step.step_type {
        StepTypeTag::Task | StepTypeTag::Delegator => {
            // A delegator step may prepend prompt flavor and pin a model.
            let mut effective_prompt = prompt.clone();
            let mut model: Option<String> = step.agent.clone();
            if step.step_type == StepTypeTag::Delegator {
                if let Some(cfg) = &step.delegator_config {
                    model = Some(cfg.delegator.clone());
                    if let Some(flavor) = &cfg.prompt_flavor {
                        let rendered_flavor = render(hbs, flavor, ctx)?;
                        effective_prompt = format!("{rendered_flavor}\n\n{prompt}");
                    }
                }
            }
            if !step.allowed_tools.is_empty() {
                s.push_str(&format!(
                    "// allowed tools: {}\n",
                    step.allowed_tools.join(", ")
                ));
            }
            if has_review {
                s.push_str(&judge_loop(step, &var, &effective_prompt, model.as_deref()));
            } else {
                s.push_str(&agent_call(
                    &var,
                    &effective_prompt,
                    &step.name,
                    model.as_deref(),
                ));
            }
        }
        StepTypeTag::Classifier => {
            let schema = if let Some(explicit) = &step.json_schema {
                explicit.clone()
            } else if let Some(cfg) = &step.classifier_config {
                step_map::classifier_schema(cfg)
            } else {
                serde_json::json!({ "type": "object" })
            };
            let schema_str = serde_json::to_string(&schema).unwrap_or_else(|_| "{}".to_string());
            s.push_str(&format!(
                "const {var} = await agent({prompt}, {{ label: {label}, schema: {schema} }});\n",
                prompt = js::quote(&prompt),
                label = js::quote(&step.name),
                schema = schema_str,
            ));
            if has_review {
                s.push_str(&review_comment(step));
            }
        }
        StepTypeTag::MultiModel => {
            s.push_str(&render_multi_model(hbs, ctx, step, &var, &prompt)?);
        }
        StepTypeTag::MultiPrompt => {
            s.push_str(&render_multi_prompt(hbs, ctx, step, &var)?);
        }
        StepTypeTag::Matrixed => {
            s.push_str(&render_matrixed(hbs, ctx, step, &var)?);
        }
        StepTypeTag::Rag => {
            s.push_str(&format!(
                "// {GAP_MARKER}: rag step — the workflow sandbox has no filesystem; context sources must be gathered by the agent.\n"
            ));
            if let Some(cfg) = &step.rag_config {
                let srcs: Vec<String> = cfg.sources.iter().map(describe_rag_source).collect();
                if !srcs.is_empty() {
                    s.push_str(&format!("// context sources: {}\n", srcs.join(", ")));
                }
            }
            s.push_str(&agent_call(&var, &prompt, &step.name, None));
        }
        StepTypeTag::Pipeline => {
            s.push_str(&render_pipeline(hbs, ctx, step, &var, pipeline_env)?);
        }
        StepTypeTag::Mcp => {
            s.push_str(&format!(
                "// {GAP_MARKER}: mcp step — the workflow sandbox cannot guarantee MCP tool availability.\n"
            ));
            if let Some(cfg) = &step.mcp_config {
                let tools: Vec<String> = cfg
                    .required_tools
                    .iter()
                    .map(|t| match &t.tool {
                        Some(tool) => format!("{}/{}", t.server, tool),
                        None => t.server.clone(),
                    })
                    .collect();
                if !tools.is_empty() {
                    s.push_str(&format!("// required tools: {}\n", tools.join(", ")));
                }
            }
            s.push_str(&agent_call(&var, &prompt, &step.name, None));
        }
    }

    s.push('\n');
    Ok(s)
}

/// A single `const r_x = await agent("...", { label, [model] });` line.
fn agent_call(var: &str, prompt: &str, label: &str, model: Option<&str>) -> String {
    let mut opts = format!("label: {}", js::quote(label));
    if let Some(m) = model {
        opts.push_str(&format!(", model: {}", js::quote(m)));
    }
    format!(
        "const {var} = await agent({prompt}, {{ {opts} }});\n",
        prompt = js::quote(prompt),
    )
}

fn review_label(review: &ReviewType) -> &'static str {
    match review {
        ReviewType::None => "output",
        ReviewType::Plan => "plan",
        ReviewType::Visual => "visual",
        ReviewType::Pr => "pr",
    }
}

/// Autonomous judge-agent retry loop standing in for a human review gate.
fn judge_loop(step: &StepSchema, var: &str, prompt: &str, model: Option<&str>) -> String {
    let review = review_label(&step.review_type);
    let goto = step
        .on_reject
        .as_ref()
        .map(|r| r.goto_step.clone())
        .unwrap_or_else(|| step.name.clone());

    let mut opts = format!("label: {}", js::quote(&step.name));
    if let Some(m) = model {
        opts.push_str(&format!(", model: {}", js::quote(m)));
    }

    // The work call is a `const ..._work` declaration (not a bare reassignment)
    // so the naiveworkflow compiler walks it and shows it inside the loop node.
    // `var ..._verdict` is hoisted out of the `do` block so the `while`
    // condition can read it.
    format!(
        "// {gap}: step {name} had human review_type={review}; a human gate cannot run mid-workflow.\n\
         // Emitted as an autonomous judge loop (max 3 attempts); original on_reject -> goto {goto}.\n\
         let {var};\n\
         let {var}_attempt = 0;\n\
         do {{\n\
         \x20 const {var}_work = await agent({prompt}, {{ {opts} }});\n\
         \x20 {var} = {var}_work;\n\
         \x20 var {var}_verdict = await agent({judge} + JSON.stringify({var}), {{ label: {jlabel} }});\n\
         }} while (String({var}_verdict).includes(\"REVISE\") && ++{var}_attempt < 3);\n\
         log({logmsg});\n",
        gap = GAP_MARKER,
        name = js::quote(&step.name),
        review = js::quote(review),
        goto = js::quote(&goto),
        var = var,
        prompt = js::quote(prompt),
        opts = opts,
        judge = js::quote(
            "Review the previous step's output against its acceptance criteria. Reply with PASS or REVISE and the reasons.\n\nOutput:\n"
        ),
        jlabel = js::quote(&format!("{}-review", step.name)),
        logmsg = js::quote(&format!(
            "{GAP_MARKER}: step '{}' review was autonomous; a human gate (review_type={review}, on_reject->goto {goto}) was flattened.",
            step.name
        )),
    )
}

fn review_comment(step: &StepSchema) -> String {
    format!(
        "// {GAP_MARKER}: step '{}' carries review_type={}; verify its output before relying on it.\n",
        step.name,
        review_label(&step.review_type),
    )
}

fn render_multi_model(
    hbs: &Handlebars,
    ctx: &Value,
    step: &StepSchema,
    var: &str,
    prompt: &str,
) -> Result<String> {
    let Some(cfg) = &step.multi_model_config else {
        return Ok(agent_call(var, prompt, &step.name, None));
    };
    let mut branches = String::new();
    for d in &cfg.delegators {
        branches.push_str(&format!(
            "    () => agent({prompt}, {{ model: {model} }}),\n",
            prompt = js::quote(prompt),
            model = js::quote(d),
        ));
    }
    let vote_prompt = match &cfg.voting_prompt {
        Some(p) => render(hbs, p, ctx)?,
        None => {
            "Review the candidate answers and select or synthesize the single best one.".to_string()
        }
    };
    let strategy = serde_json::to_string(&cfg.voting_strategy).unwrap_or_default();
    // Capture the fan-out in an intermediate `..._answers` binding, then vote
    // with a plain `agent(...)`. A `parallel(...).then(...)` chain would be
    // silently dropped by the naiveworkflow compiler.
    Ok(format!(
        "// multi-model fan-out + vote (voting_strategy: {strategy})\n\
         const {var}_answers = await parallel([\n{branches}]);\n\
         const {var} = await agent({vote} + JSON.stringify({var}_answers), {{ label: {label} }});\n",
        var = var,
        branches = branches,
        vote = js::quote(&format!("{vote_prompt}\n\nCandidate answers:\n")),
        label = js::quote(&format!("{}-vote", step.name)),
    ))
}

fn render_multi_prompt(
    hbs: &Handlebars,
    ctx: &Value,
    step: &StepSchema,
    var: &str,
) -> Result<String> {
    let Some(cfg) = &step.multi_prompt_config else {
        let prompt = render(hbs, &step.prompt, ctx)?;
        return Ok(agent_call(var, &prompt, &step.name, None));
    };
    let mut branches = String::new();
    for variation in &cfg.prompt_variations {
        let rendered = render(hbs, variation, ctx)?;
        branches.push_str(&format!("    () => agent({}),\n", js::quote(&rendered)));
    }
    let select_prompt = match &cfg.selection_prompt {
        Some(p) => render(hbs, p, ctx)?,
        None => "Review the candidate outputs and select the single best one.".to_string(),
    };
    let strategy = serde_json::to_string(&cfg.selection_strategy).unwrap_or_default();
    // Intermediate `..._outputs` binding + plain select `agent(...)` — see the
    // note in `render_multi_model` on why `.then()` is avoided.
    Ok(format!(
        "// multi-prompt variations + select (selection_strategy: {strategy})\n\
         const {var}_outputs = await parallel([\n{branches}]);\n\
         const {var} = await agent({select} + JSON.stringify({var}_outputs), {{ label: {label} }});\n",
        var = var,
        branches = branches,
        select = js::quote(&format!("{select_prompt}\n\nCandidate outputs:\n")),
        label = js::quote(&format!("{}-select", step.name)),
    ))
}

fn render_matrixed(hbs: &Handlebars, ctx: &Value, step: &StepSchema, var: &str) -> Result<String> {
    let Some(cfg) = &step.matrixed_config else {
        let prompt = render(hbs, &step.prompt, ctx)?;
        return Ok(agent_call(var, &prompt, &step.name, None));
    };
    let rendered_variations: Vec<String> = cfg
        .prompt_variations
        .iter()
        .map(|v| render(hbs, v, ctx))
        .collect::<Result<_>>()?;

    let format_str = serde_json::to_string(&cfg.output_format).unwrap_or_default();
    let mut rows = String::new();
    for d in &cfg.delegators {
        let mut cells = String::new();
        for v in &rendered_variations {
            cells.push_str(&format!(
                "      () => agent({prompt}, {{ model: {model} }}),\n",
                prompt = js::quote(v),
                model = js::quote(d),
            ));
        }
        rows.push_str(&format!("    () => parallel([\n{cells}    ]),\n"));
    }
    Ok(format!(
        "// matrixed {n}x{m} (delegators x prompt variations, output_format: {format_str})\n\
         const {var} = await parallel([\n{rows}]);\n",
        n = cfg.delegators.len(),
        m = rendered_variations.len(),
        var = var,
        rows = rows,
    ))
}

/// Render a pipeline step: one top-level `const r_x = await pipeline(items,
/// …stage thunks);`. Items resolve per `ItemSource` (literal array → static
/// fan-out width in the compiled graph; identifier → symbolic). The step graph
/// stays linear — the N-item fan-out lives entirely inside this one statement.
fn render_pipeline(
    hbs: &Handlebars,
    ctx: &Value,
    step: &StepSchema,
    var: &str,
    env: &PipelineEnv,
) -> Result<String> {
    let Some(cfg) = &step.pipeline_config else {
        let prompt = render(hbs, &step.prompt, ctx)?;
        return Ok(agent_call(var, &prompt, &step.name, None));
    };

    let (preamble, items_expr) = pipeline_items_expr(&cfg.item_source, var, env);

    let mut stages = String::new();
    for (i, stage) in cfg.stages.iter().enumerate() {
        let prompt = render(hbs, &stage.prompt, ctx)?;
        // Structurally append the per-item runtime bindings to the quoted
        // prompt (mirrors render_multi_model's `+ JSON.stringify(...)`); a
        // template literal would change escaping rules. Stage 0's `prev` IS
        // the item (Workflow-tool contract), so only later stages append it.
        let mut prompt_expr = format!(
            "{} + \"\\n\\nItem: \" + JSON.stringify(item)",
            js::quote(&prompt)
        );
        if i > 0 {
            prompt_expr.push_str(" + \"\\n\\nPrior stage output:\\n\" + JSON.stringify(prev)");
        }

        let label = stage
            .label
            .clone()
            .unwrap_or_else(|| format!("{}:{i}", step.name));
        // Explicit `phase` opt: stage agents run inside a container, where
        // relying on the global phase() state would race.
        let mut opts = format!(
            "label: {}, phase: {}",
            js::quote(&label),
            js::quote(step.display_name())
        );
        let model = stage
            .model
            .as_deref()
            .or(stage.agent.as_deref())
            .or(step.agent.as_deref());
        if let Some(m) = model {
            opts.push_str(&format!(", model: {}", js::quote(m)));
        }
        if let Some(schema) = &stage.json_schema {
            let schema_str = serde_json::to_string(schema).unwrap_or_else(|_| "{}".to_string());
            opts.push_str(&format!(", schema: {schema_str}"));
        }

        stages.push_str(&format!(
            "  (prev, item, i) => agent({prompt_expr}, {{ {opts} }}),\n"
        ));
    }

    Ok(format!(
        "{preamble}const {var} = await pipeline({items_expr},\n{stages});\n"
    ))
}

/// Resolve a pipeline `ItemSource` to `(preamble lines, items expression)`.
///
/// `Static`, `Projects`, and `Glob` emit a literal array (static ×N in the
/// compiled graph); `FromStep` emits the prior step's result identifier
/// (symbolic ×N). Sources the export environment cannot resolve fall back to
/// an empty, GAP-marked placeholder binding — runtime-safe (zero iterations)
/// and rendered symbolic.
fn pipeline_items_expr(source: &ItemSource, var: &str, env: &PipelineEnv) -> (String, String) {
    match source {
        ItemSource::Static { items } => (String::new(), items_literal(items)),
        ItemSource::FromStep { step } => (
            // The referenced step's existence is validated at schema load; its
            // *shape* is a runtime value operator cannot statically check.
            format!(
                "// {GAP_MARKER}: items are step '{}' output at runtime; operator cannot statically check it is an array.\n",
                js::comment_safe(step)
            ),
            step_map::result_var(step),
        ),
        ItemSource::Projects => {
            if env.projects.is_empty() {
                return unresolved_items(var, "projects");
            }
            // Sorted for determinism regardless of discovery (read_dir) order.
            let mut projects = env.projects.clone();
            projects.sort();
            (String::new(), items_literal(&projects))
        }
        ItemSource::Glob { pattern } => {
            let Some(root) = &env.glob_root else {
                return unresolved_items(var, &format!("glob:{pattern}"));
            };
            let matches = expand_glob(root, pattern);
            if matches.is_empty() {
                return unresolved_items(var, &format!("glob:{pattern} (no matches)"));
            }
            (String::new(), items_literal(&matches))
        }
        // Deferred: ticket field values are not captured at export time (and
        // no list FieldType exists yet), so Field cannot resolve here.
        ItemSource::Field { name } => unresolved_items(var, &format!("field:{name}")),
    }
}

/// Quote a list of items into a JS array literal.
fn items_literal(items: &[String]) -> String {
    let quoted: Vec<String> = items.iter().map(|i| js::quote(i)).collect();
    format!("[{}]", quoted.join(", "))
}

/// Expand `pattern` against `root`, returning matches relative to `root`
/// (host-absolute paths would leak machine state into the artifact), sorted
/// for determinism.
fn expand_glob(root: &std::path::Path, pattern: &str) -> Vec<String> {
    let full = root.join(pattern);
    let mut matches: Vec<String> = glob::glob(&full.to_string_lossy())
        .map(|paths| {
            paths
                .flatten()
                .filter_map(|p| {
                    p.strip_prefix(root)
                        .ok()
                        .map(|rel| rel.to_string_lossy().to_string())
                })
                .collect()
        })
        .unwrap_or_default();
    matches.sort();
    matches
}

/// GAP-marked placeholder for an item source that could not be resolved at
/// export time. Passing the identifier (not a literal) keeps the compiled
/// graph honest: the fan-out width shows as symbolic, not a fake static count.
fn unresolved_items(var: &str, desc: &str) -> (String, String) {
    let ident = format!("{var}_items");
    (
        format!(
            "// {GAP_MARKER}: pipeline items '{}' unresolved at export time; placeholder iterates zero items.\nconst {ident} = [];\n",
            js::comment_safe(desc)
        ),
        ident,
    )
}

fn describe_rag_source(src: &RagSource) -> String {
    match src {
        RagSource::Glob { pattern } => format!("glob:{pattern}"),
        RagSource::File { path } => format!("file:{path}"),
        RagSource::Mcp { server, tool, .. } => format!("mcp:{server}/{tool}"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Minimal issuetype wrapping `steps_json`, used to materialize real
    /// `StepSchema` values (serde defaults fill the rest) for the private
    /// helpers that take a `&StepSchema`.
    fn issuetype_with_steps(steps_json: &str) -> IssueType {
        let json = format!(
            r#"{{
                "key": "FEAT",
                "name": "Feature",
                "description": "A new feature",
                "mode": "autonomous",
                "glyph": "*",
                "fields": [],
                "steps": {steps_json}
            }}"#
        );
        IssueType::from_json(&json).expect("valid issuetype json")
    }

    fn ticket(id: &str, project: &str, summary: &str) -> Ticket {
        Ticket {
            filename: "20241221-1430-FEAT-proj-test.md".to_string(),
            filepath: "/test/path".to_string(),
            timestamp: "20241221-1430".to_string(),
            ticket_type: "FEAT".to_string(),
            project: project.to_string(),
            id: id.to_string(),
            summary: summary.to_string(),
            priority: "P2-medium".to_string(),
            status: "queued".to_string(),
            step: String::new(),
            content: "body".to_string(),
            sessions: std::collections::HashMap::new(),
            step_delegators: std::collections::HashMap::new(),
            llm_task: crate::queue::LlmTask::default(),
            worktree_path: None,
            branch: None,
            external_id: None,
            external_url: None,
            external_provider: None,
        }
    }

    // ── agent_call ──────────────────────────────────────────────────────

    #[test]
    fn test_agent_call_without_model_emits_single_await_line() {
        let out = agent_call("r_plan", "Do the thing", "plan", None);
        assert_eq!(
            out,
            "const r_plan = await agent(\"Do the thing\", { label: \"plan\" });\n"
        );
        assert!(!out.contains("model:"), "no model opt expected:\n{out}");
    }

    #[test]
    fn test_agent_call_with_model_includes_model_opt() {
        let out = agent_call("r_build", "Build it", "build", Some("opus"));
        assert!(
            out.contains("label: \"build\", model: \"opus\""),
            "model opt missing:\n{out}"
        );
    }

    #[test]
    fn test_agent_call_escapes_prompt_quotes() {
        let out = agent_call("r_x", "say \"hi\"", "x", None);
        assert!(
            out.contains(r#"agent("say \"hi\"","#),
            "embedded quotes not escaped:\n{out}"
        );
    }

    // ── items_literal ───────────────────────────────────────────────────

    #[test]
    fn test_items_literal_quotes_and_joins() {
        let items = vec!["a".to_string(), "b".to_string()];
        assert_eq!(items_literal(&items), r#"["a", "b"]"#);
    }

    #[test]
    fn test_items_literal_empty_is_empty_array() {
        assert_eq!(items_literal(&[]), "[]");
    }

    #[test]
    fn test_items_literal_escapes_embedded_quotes() {
        let items = vec![r#"a"b"#.to_string()];
        assert_eq!(items_literal(&items), r#"["a\"b"]"#);
    }

    // ── describe_rag_source ─────────────────────────────────────────────

    #[test]
    fn test_describe_rag_source_glob_prefixes_pattern() {
        let src = RagSource::Glob {
            pattern: "docs/*.md".to_string(),
        };
        assert_eq!(describe_rag_source(&src), "glob:docs/*.md");
    }

    #[test]
    fn test_describe_rag_source_file_prefixes_path() {
        let src = RagSource::File {
            path: "README.md".to_string(),
        };
        assert_eq!(describe_rag_source(&src), "file:README.md");
    }

    #[test]
    fn test_describe_rag_source_mcp_joins_server_and_tool() {
        let src = RagSource::Mcp {
            server: "srv".to_string(),
            tool: "search".to_string(),
            query: None,
        };
        assert_eq!(describe_rag_source(&src), "mcp:srv/search");
    }

    // ── meta_block ──────────────────────────────────────────────────────

    #[test]
    fn test_meta_block_emits_export_const_meta_with_name_and_phases() {
        let it = issuetype_with_steps(
            r#"[{"name":"plan","display_name":"Planning","outputs":["plan"],"prompt":"p"},
                {"name":"build","display_name":"Building","outputs":["code"],"prompt":"b"}]"#,
        );
        let tk = ticket("FEAT-1234", "gamesvc", "Add pagination");
        let steps: Vec<&StepSchema> = it.steps.iter().collect();
        let out = meta_block(&tk, &it, &steps);

        assert!(
            out.contains("export const meta = {"),
            "meta header missing:\n{out}"
        );
        assert!(
            out.contains(r#"name: "FEAT-1234 — Add pagination""#),
            "name should combine ticket id + summary:\n{out}"
        );
        assert!(out.contains("phases: ["), "phases array missing:\n{out}");
        // Each step's display_name becomes a phase title.
        assert!(
            out.contains(r#"{ title: "Planning" }"#) && out.contains(r#"{ title: "Building" }"#),
            "phase titles missing:\n{out}"
        );
    }

    // ── judge_loop ──────────────────────────────────────────────────────

    #[test]
    fn test_judge_loop_emits_bounded_do_while_with_gap_marker() {
        let it = issuetype_with_steps(
            r#"[{"name":"plan","outputs":["plan"],"prompt":"plan it","review_type":"plan"}]"#,
        );
        let step = &it.steps[0];
        let out = judge_loop(step, "r_plan", "plan it", None);

        assert!(out.contains("do {"), "do-block missing:\n{out}");
        assert!(out.contains("} while ("), "while condition missing:\n{out}");
        assert!(out.contains("REVISE"), "REVISE sentinel missing:\n{out}");
        // Bounded retry: at most 3 attempts.
        assert!(
            out.contains("++r_plan_attempt < 3"),
            "attempt bound missing:\n{out}"
        );
        assert!(
            out.contains(GAP_MARKER),
            "human-gate GAP marker missing:\n{out}"
        );
    }

    // ── pipeline_items_expr ─────────────────────────────────────────────

    #[test]
    fn test_pipeline_items_expr_static_emits_literal_array() {
        let src = ItemSource::Static {
            items: vec!["alpha".to_string(), "beta".to_string()],
        };
        let (preamble, expr) = pipeline_items_expr(&src, "r_x", &PipelineEnv::default());
        assert_eq!(preamble, "");
        assert_eq!(expr, r#"["alpha", "beta"]"#);
    }

    #[test]
    fn test_pipeline_items_expr_from_step_references_step_var() {
        let src = ItemSource::FromStep {
            step: "triage".to_string(),
        };
        let (preamble, expr) = pipeline_items_expr(&src, "r_x", &PipelineEnv::default());
        // Symbolic: the prior step's result identifier, no literal array.
        assert_eq!(expr, "r_triage");
        assert!(
            preamble.contains(GAP_MARKER) && preamble.contains("triage"),
            "runtime-shape GAP note missing:\n{preamble}"
        );
    }

    #[test]
    fn test_pipeline_items_expr_projects_sorts_and_emits_literal() {
        let env = PipelineEnv {
            projects: vec!["zeta".to_string(), "alpha".to_string()],
            glob_root: None,
        };
        let (preamble, expr) = pipeline_items_expr(&ItemSource::Projects, "r_x", &env);
        assert_eq!(preamble, "");
        assert_eq!(expr, r#"["alpha", "zeta"]"#, "projects must be sorted");
    }

    #[test]
    fn test_pipeline_items_expr_projects_empty_falls_back_to_placeholder() {
        let (preamble, expr) =
            pipeline_items_expr(&ItemSource::Projects, "r_x", &PipelineEnv::default());
        assert_eq!(expr, "r_x_items", "unresolved → symbolic placeholder ident");
        assert!(
            preamble.contains(GAP_MARKER) && preamble.contains("const r_x_items = [];"),
            "zero-iteration placeholder missing:\n{preamble}"
        );
    }

    #[test]
    fn test_pipeline_items_expr_field_emits_gap_placeholder() {
        let src = ItemSource::Field {
            name: "components".to_string(),
        };
        let (preamble, expr) = pipeline_items_expr(&src, "r_x", &PipelineEnv::default());
        assert_eq!(expr, "r_x_items");
        assert!(
            preamble.contains(GAP_MARKER) && preamble.contains("field:components"),
            "field placeholder note missing:\n{preamble}"
        );
    }

    // ── expand_glob (filesystem) ────────────────────────────────────────

    #[test]
    fn test_expand_glob_returns_sorted_relative_paths() {
        let dir = tempfile::tempdir().expect("tempdir");
        std::fs::write(dir.path().join("b.md"), "b").unwrap();
        std::fs::write(dir.path().join("a.md"), "a").unwrap();
        std::fs::write(dir.path().join("skip.txt"), "no").unwrap();

        let matches = expand_glob(dir.path(), "*.md");
        // Sorted, relative (no absolute path leaking machine state), .txt excluded.
        assert_eq!(matches, vec!["a.md".to_string(), "b.md".to_string()]);
    }

    #[test]
    fn test_expand_glob_no_match_returns_empty() {
        let dir = tempfile::tempdir().expect("tempdir");
        std::fs::write(dir.path().join("a.md"), "a").unwrap();
        assert!(expand_glob(dir.path(), "*.rs").is_empty());
    }
}
