// =============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// =============================================================================
// Generated by: cargo run --bin generate_types
// Source: src/**/*.rs (types with #[derive(TS)] and #[ts(export)])
//
// To regenerate: cargo run --bin generate_types
// To verify:     cargo run --bin generate_types --check
// =============================================================================

export type Project = { 
/**
 * Unique identifier
 */
id: string, 
/**
 * Human-readable project name
 */
name: string, 
/**
 * Filesystem path to the project root
 */
path: string, 
/**
 * Associated git repositories (can be multiple for monorepos)
 */
repos: Array<ProjectRepo>, 
/**
 * Default branch for merging (e.g., "main", "master")
 */
default_branch: string | null, 
/**
 * Path to the AI context file (CLAUDE.md, GEMINI.md, etc.)
 */
ai_context_path: string | null, 
/**
 * Project taxonomy kind (tier 1-5)
 */
kind: string | null, 
/**
 * Tags for categorization
 */
tags: Array<string>, 
/**
 * Development server startup command
 */
dev_script: string | null, 
/**
 * Working directory for dev script execution
 */
dev_script_working_dir: string | null, 
/**
 * Default working directory for AI agents
 */
default_agent_working_dir: string | null, 
/**
 * Setup script to run before agent execution
 */
setup_script: string | null, 
/**
 * Cleanup script to run after agent execution
 */
cleanup_script: string | null, 
/**
 * Link to shared organizational project
 */
remote_project_id: string | null, created_at: string, updated_at: string, };

export type ProjectRepo = { 
/**
 * Unique identifier for this repo association
 */
id: string, 
/**
 * Absolute path to the repository root
 */
path: string, 
/**
 * Whether this is the primary repo for the project
 */
is_primary: boolean, 
/**
 * Setup script to run when creating worktrees for this repo
 */
setup_script: string | null, 
/**
 * Cleanup script to run when deleting worktrees
 */
cleanup_script: string | null, 
/**
 * Files to copy into worktrees (e.g., .env files)
 */
copy_files: Array<string>, };

export type StepAttempt = { 
/**
 * Unique identifier for this attempt
 */
id: string, 
/**
 * Parent ticket ID (e.g., "FEAT-1234")
 */
ticket_id: string, 
/**
 * Which step this attempt is executing (e.g., "plan", "implement", "test")
 */
step_name: string, 
/**
 * Project name this attempt belongs to
 */
project: string, 
/**
 * Git branch for this attempt (e.g., "feat/abc123-add-login")
 */
branch: string, 
/**
 * Target branch to merge into (e.g., "main")
 */
target_branch: string, 
/**
 * Path to isolated git worktree (if using worktree isolation)
 */
worktree_path: string | null, 
/**
 * Whether the worktree has been cleaned up
 */
worktree_deleted: boolean, 
/**
 * Which LLM tool is executing (e.g., "claude", "gemini", "codex")
 */
executor: string, 
/**
 * Executor model override (e.g., "claude-sonnet-4-20250514")
 */
executor_model: string | null, 
/**
 * Current session ID for conversational continuity
 */
session_id: string | null, 
/**
 * Launch mode: "default", "yolo", "docker", "docker-yolo"
 */
launch_mode: string | null, 
/**
 * Current status of this attempt
 */
status: AttemptStatus, 
/**
 * Whether this attempt requires human pairing (SPIKE/INV modes)
 */
paired: boolean, 
/**
 * Terminal session name (for Operator's terminal-based execution)
 */
terminal_session: string | null, 
/**
 * Which session wrapper manages this attempt: "tmux", "vscode", or "cmux"
 */
session_wrapper: string | null, 
/**
 * Hash of last captured terminal content (for change detection)
 */
content_hash: string | null, 
/**
 * Pull request URL if created
 */
pr_url: string | null, 
/**
 * PR number for API tracking
 */
pr_number: bigint | null, 
/**
 * GitHub repo in format "owner/repo"
 */
github_repo: string | null, 
/**
 * Current PR status ("open", "approved", "`changes_requested`", "merged", "closed")
 */
pr_status: string | null, 
/**
 * When setup completed (worktree created, scripts run)
 */
setup_completed_at: string | null, 
/**
 * Last activity timestamp
 */
last_activity: string, 
/**
 * Last time terminal content changed (for hung detection)
 */
last_content_change: string | null, created_at: string, updated_at: string, };

export type AttemptStatus = "pending" | "setting" | "running" | "awaitinginput" | "inreview" | "completed" | "failed" | "cancelled" | "orphaned";

export type ExecutionProcess = { 
/**
 * Unique identifier
 */
id: string, 
/**
 * Parent attempt ID
 */
attempt_id: string, 
/**
 * Why this process was spawned
 */
run_reason: RunReason, 
/**
 * Action chain configuration (for sequential execution)
 */
executor_action: JsonValue | null, 
/**
 * Git HEAD before execution started
 */
before_head_commit: string | null, 
/**
 * Git HEAD after execution completed
 */
after_head_commit: string | null, 
/**
 * Current process status
 */
status: ProcessStatus, 
/**
 * Process exit code (if completed)
 */
exit_code: number | null, 
/**
 * Whether this process is excluded from the timeline (e.g., after retry)
 */
dropped: boolean, started_at: string, completed_at: string | null, };

export type ProcessStatus = "running" | "completed" | "failed" | "killed";

export type RunReason = "setupscript" | "codingagent" | "cleanup" | "followup";

export type Session = { 
/**
 * Unique identifier
 */
id: string, 
/**
 * Parent attempt ID
 */
attempt_id: string, 
/**
 * Terminal session name for terminal-based execution
 */
terminal_session_name: string | null, 
/**
 * Which session wrapper manages this session: "tmux", "vscode", or "cmux"
 */
session_wrapper: string | null, 
/**
 * Hash of terminal content for change detection
 */
content_hash: string | null, 
/**
 * Agent's internal session ID (e.g., Claude's conversation ID)
 */
agent_session_id: string | null, 
/**
 * Summary extracted from message store
 */
summary: string | null, created_at: string, updated_at: string, };

export type Config = { profile: ProfileIdentity, 
/**
 * List of projects operator can assign work to
 */
projects: Array<string>, agents: AgentsConfig, notifications: NotificationsConfig, queue: QueueConfig, paths: PathsConfig, ui: UiConfig, launch: LaunchConfig, templates: TemplatesConfig, api: ApiConfig, logging: LoggingConfig, tmux: TmuxConfig, 
/**
 * Session wrapper configuration (tmux, vscode, or cmux)
 */
sessions: SessionsConfig, llm_tools: LlmToolsConfig, rest_api: RestApiConfig, git: GitConfig, 
/**
 * Kanban provider configuration for syncing issues from Jira, Linear, etc.
 */
kanban: KanbanConfig, 
/**
 * Version check configuration for automatic update notifications
 */
version_check: VersionCheckConfig, 
/**
 * Agent delegator configurations for autonomous ticket launching
 */
delegators: Array<Delegator>, 
/**
 * User-declared model servers (ollama, lmstudio, any OpenAI-compat host).
 * Implicit builtin servers exist for each `llm_tool`'s vendor API and do not need declaration.
 */
model_servers: Array<ModelServer>, 
/**
 * Remote machines agents can be launched on over SSH, referenced by name
 * from `DelegatorLaunchConfig.host`.
 */
hosts: Array<RemoteHost>, 
/**
 * Named execution targets (docker/coder/ssh/local) referenced by `DelegatorLaunchConfig.target`.
 */
targets: Array<TargetDef>, 
/**
 * Relay MCP injection configuration
 */
relay: RelayConfig, 
/**
 * Model Context Protocol (MCP) server configuration
 */
mcp: McpConfig, 
/**
 * Agent Client Protocol (ACP) agent configuration
 */
acp: AcpConfig, };

export type AgentsConfig = { max_parallel: number, cores_reserved: number, 
/**
 * Maximum concurrent agents per project/repo (default: 1).
 * Requires `git.use_worktrees` = true when > 1 to avoid conflicts.
 */
max_agents_per_repo: number, health_check_interval: bigint, 
/**
 * Timeout in seconds for each agent generation (default: 300 = 5 min)
 */
generation_timeout_secs: bigint, 
/**
 * Interval in seconds between ticket-session syncs (default: 60)
 */
sync_interval: bigint, 
/**
 * Maximum seconds a step can run before timing out (default: 1800 = 30 min)
 */
step_timeout: bigint, 
/**
 * Seconds of tmux silence before considering agent awaiting input (default: 30)
 */
silence_threshold: bigint, };

export type NotificationsConfig = { 
/**
 * Global enabled flag for all notifications
 */
enabled: boolean, 
/**
 * OS notification configuration
 */
os: OsNotificationConfig, 
/**
 * Single webhook configuration (for simple setups)
 */
webhook: WebhookConfig | null, 
/**
 * Multiple webhook configurations
 */
webhooks: Array<WebhookConfig>, };

export type QueueConfig = { auto_assign: boolean, priority_order: Array<string>, poll_interval_ms: bigint, };

export type PathsConfig = { tickets: string, projects: string, state: string, 
/**
 * Base directory for per-ticket worktrees (default: ~/.operator/worktrees)
 */
worktrees: string, };

export type UiConfig = { refresh_rate_ms: bigint, completed_history_hours: bigint, summary_max_length: number, panel_names: PanelNamesConfig, };

export type PanelNamesConfig = { status: string, queue: string, in_progress: string, completed: string, };

export type LaunchConfig = { confirm_autonomous: boolean, confirm_paired: boolean, launch_delay_ms: bigint, 
/**
 * Default named execution target. Per-launch and per-delegator choices take precedence.
 */
target: string | null, 
/**
 * Docker execution configuration
 */
docker: DockerConfig, 
/**
 * YOLO (auto-accept) mode configuration
 */
yolo: YoloConfig, };

export type DockerConfig = { 
/**
 * Whether docker mode option is available in launch dialog
 */
enabled: boolean, 
/**
 * Docker image to use (required if enabled)
 */
image: string, 
/**
 * Additional docker run arguments
 */
extra_args: Array<string>, 
/**
 * Container mount path for the project (default: /workspace)
 */
mount_path: string, 
/**
 * Environment variables to pass through to the container
 */
env_vars: Array<string>, };

export type YoloConfig = { 
/**
 * Whether YOLO mode option is available in launch dialog
 */
enabled: boolean, };

export type TmuxConfig = { 
/**
 * Whether custom tmux config has been generated
 */
config_generated: boolean, };

export type RestApiConfig = { 
/**
 * Whether the REST API is enabled
 */
enabled: boolean, 
/**
 * Address the REST API binds to. Defaults to `127.0.0.1` (local only) so the server is not reachable from other hosts. Set to `0.0.0.0` to expose it on all interfaces.
 */
host: string, 
/**
 * Port for the REST API server
 */
port: number, 
/**
 * CORS allowed origins. Empty means **same-origin only**
 */
cors_origins: Array<string>, 
/**
 * Externally reachable base URL (e.g. `https://operator.example.com`). Defaults to request host.
 */
public_url: string | null, 
/**
 * Maximum time to wait for active agents before shutdown cleanup begins.
 */
shutdown_drain_seconds: number, 
/**
 * Maximum time reserved for final callbacks and persistent cleanup.
 */
shutdown_cleanup_seconds: number, };

export type LlmToolsConfig = { 
/**
 * Detected CLI tools (populated on first startup)
 */
detected: Array<DetectedTool>, 
/**
 * Available {tool, model} pairs for launching tickets
 * Built from detected tools + their model aliases
 */
providers: Array<LlmProvider>, 
/**
 * Whether detection has been completed
 */
detection_complete: boolean, 
/**
 * User's preferred default LLM tool (e.g., "claude")
 */
default_tool: string | null, 
/**
 * User's preferred default model alias (e.g., "opus")
 */
default_model: string | null, 
/**
 * Per-tool overrides for skill directories (keyed by `tool_name`)
 */
skill_directory_overrides: { [key in string]: SkillDirectoriesOverride }, };

export type DetectedTool = { 
/**
 * Tool name (e.g., "claude")
 */
name: string, 
/**
 * Path to the binary
 */
path: string, 
/**
 * Version string
 */
version: string, 
/**
 * Minimum required version for Operator compatibility
 */
min_version: string | null, 
/**
 * Whether the installed version meets the minimum requirement
 */
version_ok: boolean, 
/**
 * Available model aliases (e.g., ["opus", "sonnet", "haiku"])
 */
model_aliases: Array<string>, 
/**
 * Command template with {{model}}, {{`session_id`}}, {{`prompt_file`}} placeholders
 */
command_template: string, 
/**
 * Tool capabilities
 */
capabilities: ToolCapabilities, 
/**
 * CLI flags for YOLO (auto-accept) mode
 */
yolo_flags: Array<string>, 
/**
 * Whether the tool passed its health check at detection on startup
 */
health_ok: boolean, };

export type ToolCapabilities = { 
/**
 * Whether the tool supports session continuity via UUID
 */
supports_sessions: boolean, 
/**
 * Whether the tool can run in headless/non-interactive mode
 */
supports_headless: boolean, };

export type LlmProvider = { 
/**
 * CLI tool name (e.g., "claude", "codex", "gemini")
 */
tool: string, 
/**
 * Model alias or name (e.g., "opus", "sonnet", "gpt-4.1")
 */
model: string, 
/**
 * Optional display name for UI (e.g., "Claude Opus", "Codex High")
 */
display_name: string | null, 
/**
 * Additional CLI flags for this provider (e.g., ["--dangerously-skip-permissions"])
 */
flags: Array<string>, 
/**
 * Environment variables to set when launching
 */
env: { [key in string]: string }, 
/**
 * Whether this provider requires approval gates
 */
approvals: boolean, 
/**
 * Whether to run in plan-only mode
 */
plan_only: boolean, 
/**
 * Reasoning effort level (Codex: "low", "medium", "high")
 */
reasoning_effort: string | null, 
/**
 * Sandbox mode (Codex: "danger-full-access", "workspace-write")
 */
sandbox: string | null, };

export type SkillDirectoriesOverride = { 
/**
 * Additional global skill directories
 */
global: Array<string>, 
/**
 * Additional project-relative skill directories
 */
project: Array<string>, };

export type Delegator = { 
/**
 * Optional Git identity, HTTPS credential reference, and runtime settings.
 */
git?: GitExecutionConfig | null, 
/**
 * Unique name for this delegator (e.g., "claude-opus-auto")
 */
name: string, 
/**
 * LLM tool name (must match a detected tool, e.g., "claude", "codex")
 */
llm_tool: string, 
/**
 * Model alias (e.g., "opus", "sonnet", "gpt-4o")
 */
model: string, 
/**
 * Optional display name for UI
 */
display_name: string | null, 
/**
 * Arbitrary model properties (e.g., `reasoning_effort`, sandbox)
 */
model_properties: { [key in string]: string }, 
/**
 * Optional launch configuration
 */
launch_config: DelegatorLaunchConfig | null, 
/**
 * Name of a declared `ModelServer` (from `Config.model_servers`).
 * `None` means use the `llm_tool`'s implicit vendor default
 * (claude → anthropic-api, codex → openai-api, gemini → google-api).
 */
model_server: string | null, 
/**
 * Declarative reference to a remote, named agent on another platform
 * (e.g. an AGNT agent or an `OpenAI` Assistant; see [`crate::config::AgentProfile`]).
 *
 * Export-only: Operator has no runtime client for those platforms, so a
 * delegator carrying this CANNOT be launched locally - resolution errors out
 * (see `delegator_resolution`). It is stored, listed, serialized into an
 * `AgentProfile`, and - for `platform == "agnt"` - surfaced in the
 * `--format agnt` workflow export as a native AGNT `agnt-agent` node, whose
 * `agentId` is this reference's `id` (AGNT identifies agents by UUID, so the
 * `id` must be the agent's UUID, not its display name). `None` = ordinary,
 * locally launchable delegator.
 */
remote_agent?: RemoteAgentRef | null, 
/**
 * Opaque AGNT-namespaced extension fields, preserved verbatim across an
 * `AgentProfile` round-trip so re-export is lossless (e.g. `memory`,
 * `assignedWorkflows`, `creditLimit`). Operator never interprets this.
 */
x_agnt?: JsonValue | null, 
/**
 * Opaque OpenAI-namespaced extension fields, preserved verbatim across an
 * `AgentProfile` round-trip (e.g. `instructions`, `tools`, `tool_resources`,
 * `metadata`, thread refs). Mirror of [`Self::x_agnt`]; never interpreted.
 */
x_openai?: JsonValue | null, 
/**
 * Opaque carry for `AgentProfile` shared-core fields Operator cannot model
 * first-class (`system_prompt` / `skills` / `mcp_servers` / `tools`) so an
 * import→export round-trip is lossless. Distinct from `x_agnt`: these are
 * shared-core fields, not AGNT-specific, so folding them into `x_agnt` would
 * corrupt that namespace. Operator never interprets this.
 */
unmapped_core?: JsonValue | null, };

export type DelegatorLaunchConfig = { 
/**
 * Run in YOLO (auto-accept) mode
 */
yolo: boolean, 
/**
 * Permission mode override
 */
permission_mode: string | null, 
/**
 * Additional CLI flags
 */
flags: Array<string>, 
/**
 * Override global `git.use_worktrees` per-delegator (None = use global setting)
 */
use_worktrees: boolean | null, 
/**
 * Whether to create a git branch for the ticket (None = default behavior)
 */
create_branch: boolean | null, 
/**
 * DEPRECATED: prefer `target`. Run in docker container
 * (None = fall back to `launch.docker.enabled`, then local).
 */
docker: boolean | null, 
/**
 * Prompt text to prepend before the generated step prompt
 */
prompt_prefix: string | null, 
/**
 * Prompt text to append after the generated step prompt
 */
prompt_suffix: string | null, 
/**
 * Override global relay auto-inject MCP setting per-delegator (None = use global setting)
 */
operator_relay: boolean | null, 
/**
 * DEPRECATED: prefer `target`. Name of a declared `RemoteHost` (from
 * `Config.hosts`) to launch the agent CLI on over SSH. `None` = local.
 */
host?: string | null, 
/**
 * Name of an execution target: an explicit `[[targets]]` entry, the
 * synthesized `local`/`docker` targets, or a `[[hosts]]` name.
 * Supersedes `docker` and `host`.
 */
target?: string | null, };

export type AgentProfile = { 
/**
 * Unique agent name (maps to [`Delegator::name`]).
 */
name: string, 
/**
 * Inference provider / CLI tool (maps to [`Delegator::llm_tool`]).
 */
provider: string, 
/**
 * Model alias or id (maps to [`Delegator::model`]).
 */
model: string, 
/**
 * System prompt. This is preserved opaquely across import (see [`Delegator::unmapped_core`]).
 */
system_prompt?: string | null, 
/**
 * Named skills. Preserved opaquely across import.
 */
skills: Array<string>, 
/**
 * MCP server names. Preserved opaquely across import.
 */
mcp_servers: Array<string>, 
/**
 * Tool names. Preserved opaquely across import.
 */
tools: Array<string>, 
/**
 * Declarative reference to a remote, named agent. `None` = a locally launchable agent, not bound to a remote target.
 */
remote_agent?: RemoteAgentRef | null, 
/**
 * Operator-owned extension fields (typed). `None` when the agent carries no Operator-specific configuration.
 */
x_operator?: XOperator | null, 
/**
 * AGNT-owned extension fields, opaque (`memory`, `assignedWorkflows`, `creditLimit`, ...).
 */
x_agnt?: JsonValue | null, 
/**
 * OpenAI-owned extension fields, opaque (`instructions`, `tools`, `tool_resources`, `metadata`, thread refs, ...).
 */
x_openai?: JsonValue | null, };

export type XOperator = { 
/**
 * Optional Git identity, HTTPS credential reference, and runtime settings.
 */
git?: GitExecutionConfig | null, 
/**
 * Optional display name for UI.
 */
display_name?: string | null, 
/**
 * Arbitrary model properties (e.g. `reasoning_effort`, sandbox).
 */
model_properties?: { [key in string]: string }, 
/**
 * Name of a declared `ModelServer` (`None` = implicit vendor default).
 */
model_server?: string | null, 
/**
 * Launch configuration (permission mode, flags, worktree/docker, prompt
 * wrapping, ...).
 */
launch_config?: DelegatorLaunchConfig | null, };

export type RemoteAgentRef = { 
/**
 * Hosting platform (e.g. `"agnt"`, `"openai"`).
 */
platform: string, 
/**
 * Platform-native agent identifier (e.g. an AGNT agent UUID, an `OpenAI` `asst_…` id).
 */
id: string, };

export type CollectionPreset = "simple" | "dev_kanban" | "devops_kanban" | "custom";

export type TemplatesConfig = { 
/**
 * Named preset for issue type collection
 * Options: simple, `dev_kanban`, `devops_kanban`, custom
 */
preset: CollectionPreset, 
/**
 * Custom issuetype collection (only used when preset = custom)
 * List of issue type keys: TASK, FEAT, FIX, SPIKE, INV
 */
collection: Array<string>, 
/**
 * Active collection name (overrides preset if set)
 * Can be a builtin preset name or a user-defined collection
 */
active_collection: string | null, 
/**
 * Enable fetching hosted issuetype collections during setup.
 * When disabled, only the embedded (offline) collections are offered.
 */
collections_fetch_enabled: boolean, 
/**
 * URL of the hosted collection index manifest, fetched during setup.
 * Points at a `CollectionIndex` JSON document listing available collections.
 */
collections_manifest_url: string | null, 
/**
 * Timeout in seconds for hosted collection fetch HTTP requests.
 */
collections_fetch_timeout_secs: bigint, };

export type LoggingConfig = { 
/**
 * Log level filter (trace, debug, info, warn, error)
 */
level: string, 
/**
 * Whether to log to file in TUI mode (false = stderr for debugging)
 */
to_file: boolean, };

export type ApiConfig = { 
/**
 * Interval in seconds between PR status checks (default: 60)
 */
pr_check_interval_secs: bigint, 
/**
 * Interval in seconds between rate limit checks (default: 300)
 */
rate_limit_check_interval_secs: bigint, 
/**
 * Show warning when rate limit remaining is below this percentage (default: 0.2)
 */
rate_limit_warning_threshold: number, };

export type AcpConfig = { 
/**
 * Whether the dashboard advertises the `operator acp` stdio entrypoint
 * (and editor-config snippet actions). Set to false on machines that
 * shouldn't be used as ACP agents.
 */
stdio_advertised: boolean, 
/**
 * Name of the delegator (from `[[delegators]]`) to use for ACP prompts.
 * If unset or not found, falls back to the operator's default delegator
 * resolution.
 */
default_delegator: string | null, 
/**
 * Maximum number of concurrent ACP sessions. New `session/new` requests
 * beyond this limit are rejected with a JSON-RPC error.
 */
max_concurrent_sessions: number, };

export type McpConfig = { 
/**
 * Whether to mount MCP HTTP/SSE endpoints on the REST API server.
 * Toggling requires an API restart (no hot-swap of the axum router).
 */
http_enabled: boolean, 
/**
 * Whether the descriptor endpoint advertises the `operator mcp` stdio
 * command. Set to false on multi-tenant/remote deployments where clients
 * shouldn't spawn local subprocesses.
 */
stdio_advertised: boolean, 
/**
 * Whether to expose ticket-mutating tools (claim, complete, return-to-queue,
 * create) over MCP. Defaults to `false` because any MCP client can call them.
 */
expose_ticket_write_tools: boolean, 
/**
 * External MCP servers to inject into spawned agent sessions.
 * Each entry produces a separate `--mcp-config` file alongside the
 * relay config when launching Claude Code agents.
 */
external_servers: Array<ExternalMcpServer>, };

export type RelayConfig = { 
/**
 * When true, automatically inject the relay MCP server for all delegators.
 * When false (default), relay injection is opt-in per delegator.
 */
auto_inject_mcp: boolean, };

export type VersionCheckConfig = { 
/**
 * Enable automatic version checking on startup
 */
enabled: boolean, 
/**
 * URL to fetch latest version from (optional, can be removed)
 */
url: string | null, 
/**
 * Timeout in seconds for version check HTTP request
 */
timeout_secs: bigint, };

export type SessionsConfig = { 
/**
 * Which session wrapper to use
 */
wrapper: SessionWrapperType, 
/**
 * Tmux-specific configuration
 */
tmux: SessionsTmuxConfig, 
/**
 * VS Code-specific configuration
 */
vscode: SessionsVSCodeConfig, 
/**
 * cmux-specific configuration
 */
cmux: SessionsCmuxConfig, 
/**
 * Zellij-specific configuration
 */
zellij: SessionsZellijConfig, };

export type SessionWrapperType = "tmux" | "vscode" | "cmux" | "zellij";

export type SessionsTmuxConfig = { 
/**
 * Whether custom tmux config has been generated
 */
config_generated: boolean, 
/**
 * Socket name for session isolation
 */
socket_name: string, };

export type SessionsVSCodeConfig = { 
/**
 * Port for extension webhook server
 */
webhook_port: number, 
/**
 * Connection timeout in milliseconds
 */
connect_timeout_ms: bigint, };

export type SessionsCmuxConfig = { 
/**
 * Path to the cmux binary
 */
binary_path: string, 
/**
 * Require running inside cmux (`CMUX_WORKSPACE_ID` env var present)
 */
require_in_cmux: boolean, 
/**
 * Where to place new agent sessions: "auto", "workspace", or "window"
 */
placement: CmuxPlacementPolicy, };

export type CmuxPlacementPolicy = "auto" | "workspace" | "window";

export type SessionsZellijConfig = { 
/**
 * Require running inside Zellij (ZELLIJ env var present)
 */
require_in_zellij: boolean, };

export type ExternalMcpServer = { 
/**
 * Server name used as the key in the `mcpServers` JSON object
 * (e.g., "kanbots"). Must be unique across all external servers.
 */
name: string, 
/**
 * Command to execute. Supports `${VAR}` interpolation.
 */
command: string, 
/**
 * Command arguments. Each element supports `${VAR}` interpolation.
 */
args: Array<string>, 
/**
 * Environment variables passed to the MCP server process.
 * Values support `${VAR}` interpolation.
 */
env: { [key in string]: string }, 
/**
 * Whether this server is enabled. Allows disabling without removing config.
 */
enabled: boolean, 
/**
 * Path to a JSON sidecar discovery file. Relative paths resolve from
 * the project directory. The sidecar must contain `{ "mcpServer": { ... } }`.
 * When the file exists, its `mcpServer` spec is used verbatim (overriding
 * `command`/`args`/`env`). When absent and `command` is empty, the server
 * is silently skipped.
 */
discover_from: string | null, };

export type GitConfig = { 
/**
 * Default commit identity for delegated work.
 */
identity?: GitIdentityConfig | null, gitea: GiteaConfig, forgejo: ForgejoConfig, 
/**
 * Active provider (auto-detected from remote URL if not specified)
 */
provider: GitProviderConfig | null, 
/**
 * GitHub-specific configuration
 */
github: GitHubConfig, 
/**
 * GitLab-specific configuration
 */
gitlab: GitLabConfig, 
/**
 * Branch naming format (e.g., "{type}/{ticket_id}-{slug}")
 */
branch_format: string, 
/**
 * Whether to use git worktrees for per-ticket isolation (default: false)
 * When false, tickets work directly in the project directory with branches
 */
use_worktrees: boolean, };

export type GitHubConfig = { 
/**
 * Whether GitHub integration is enabled
 */
enabled: boolean, 
/**
 * Environment variable containing the GitHub token (default: `GITHUB_TOKEN`)
 */
token_env: string, };

export type GitLabConfig = { 
/**
 * Whether GitLab integration is enabled
 */
enabled: boolean, 
/**
 * Environment variable containing the GitLab token (default: `GITLAB_TOKEN`)
 */
token_env: string, 
/**
 * GitLab host (default: gitlab.com, can be self-hosted)
 */
host: string | null, };

export type GiteaConfig = { enabled: boolean, token_env: string, 
/**
 * HTTPS host or base URL; defaults to gitea.com.
 */
host: string | null, wip_prefix: string, };

export type ForgejoConfig = { enabled: boolean, token_env: string, 
/**
 * HTTPS host or base URL; defaults to codeberg.org.
 */
host: string | null, wip_prefix: string, };

export type KanbanConfig = { 
/**
 * Jira Cloud instances keyed by domain (e.g., "foobar.atlassian.net")
 */
jira: { [key in string]: JiraConfig }, 
/**
 * Linear instances keyed by workspace slug
 */
linear: { [key in string]: LinearConfig }, 
/**
 * GitHub Projects v2 instances keyed by owner login (user or org)
 *
 * NOTE: This is the *kanban* GitHub integration (Projects v2), distinct
 * from `GitHubConfig` which is the *git provider* used for PRs and
 * branches. The two use different env vars and different scopes - see
 * `docs/getting-started/kanban/github.md` for the full disambiguation.
 */
github: { [key in string]: GithubProjectsConfig }, 
/**
 * `OpenSpec` roots keyed by a free-form instance name (e.g., a repo alias).
 * Experimental, pull-only: each active change under `<root_path>/changes/`
 * acts as a kanban "project" whose issues are the tasks.md task groups.
 */
openspec: { [key in string]: OpenspecConfig }, };

export type ModelServer = { 
/**
 * Unique name (e.g., "ollama-local", "vllm-gpu1")
 */
name: string, 
/**
 * Kind: "ollama", "openrouter", "openai-compat", "anthropic-api", "openai-api", "google-api", "lmstudio"
 */
kind: string, 
/**
 * Base URL of the inference endpoint (e.g., `http://localhost:11434`).
 * `None` for implicit vendor servers means use the SDK default.
 */
base_url: string | null, 
/**
 * Name of an env var providing the API key (e.g., `OLLAMA_API_KEY`)
 */
api_key_env: string | null, 
/**
 * Additional environment variables set when spawning agents that use this server
 */
extra_env: { [key in string]: string }, 
/**
 * Optional display name for UI
 */
display_name: string | null, };

export type RemoteHost = { 
/**
 * Unique name referenced by `DelegatorLaunchConfig.host` (e.g., "gpu-vm")
 */
name: string, 
/**
 * SSH destination, resolved via the user's `~/.ssh/config`
 */
ssh_alias: string, 
/**
 * Absolute path to the project root on the remote host
 */
workdir: string, 
/**
 * Optional display name for UI
 */
display_name: string | null, 
/**
 * SSH config fragment passed with `-F` (used by provisioned coder aliases)
 */
ssh_config_path?: string | null, };

export type OsNotificationConfig = { 
/**
 * Whether OS notifications are enabled
 */
enabled: boolean, 
/**
 * Play sound with notifications
 */
sound: boolean, 
/**
 * Events to send (empty = all events)
 * Possible values: agent.started, agent.completed, agent.failed,
 * `agent.awaiting_input`, `agent.session_lost`, pr.created, pr.merged,
 * pr.closed, `pr.ready_to_merge`, `pr.changes_requested`,
 * ticket.returned, investigation.created
 */
events: Array<string>, };

export type WebhookConfig = { 
/**
 * Optional name for this webhook (for logging)
 */
name: string | null, 
/**
 * Whether this webhook is enabled
 */
enabled: boolean, 
/**
 * Webhook URL
 */
url: string, 
/**
 * Authentication type: "bearer" or "basic"
 */
auth_type: string | null, 
/**
 * Environment variable containing the bearer token
 */
token_env: string | null, 
/**
 * Username for basic auth
 */
username: string | null, 
/**
 * Environment variable containing the password for basic auth
 */
password_env: string | null, 
/**
 * Events to send (empty = all events)
 */
events: Array<string> | null, };

export type TargetDef = { 
/**
 * Unique name, referenced by `DelegatorLaunchConfig.target`.
 * `local` and `docker` are reserved for synthesized targets.
 */
name: string, 
/**
 * Human-readable name for UI surfaces
 */
display_name?: string | null, } & ({ "kind": "local" } | { "kind": "docker" } & DockerConfig | { "kind": "coder" } & CoderConfig | { "kind": "ssh" } & SshTarget);

export type TargetKind = { "kind": "local" } | { "kind": "docker" } & DockerConfig | { "kind": "coder" } & CoderConfig | { "kind": "ssh" } & SshTarget;

export type SshTarget = { 
/**
 * Host alias resolved via the user's `~/.ssh/config` (or `ssh_config_path`)
 */
ssh_alias: string, 
/**
 * Absolute project root on the remote machine
 */
workdir: string, 
/**
 * SSH config fragment passed with `-F` (used by provisioned coder aliases)
 */
ssh_config_path?: string | null, };

export type CoderConfig = { 
/**
 * Coder template child workspaces are created from (an allowlist -
 * never per-ticket input)
 */
template: string, 
/**
 * Env var NAME holding the Coder deployment URL
 */
url_env: string, 
/**
 * Env var NAME holding the Coder session token. The variable is stripped
 * from every agent's spawn environment on all target kinds.
 */
token_env: string, 
/**
 * Workspace name prefix for deterministic per-ticket naming
 */
name_prefix: string, 
/**
 * Project root inside the workspace (None = /home/coder/{project})
 */
workdir?: string | null, 
/**
 * Stop the workspace when the ticket completes (never delete)
 */
stop_on_complete: boolean, 
/**
 * Bound on workspace create + agent-ready wait
 */
create_timeout_secs: bigint, 
/**
 * Control-plane-reachable `OPERATOR_API_URL` override for detached
 * multi-step (empty/None = reverse tunnel default)
 */
callback_url?: string | null, 
/**
 * Passthrough `--parameter` template parameters for `coder create`
 */
parameters?: { [key in string]: string }, };

export type ProfileIdentity = { id: string, name: string, };

export type State = { paused: boolean, agents: Array<AgentState>, completed: Array<CompletedTicket>, 
/**
 * Per-project LLM usage statistics
 */
project_llm_stats: { [key in string]: ProjectLlmStats }, 
/**
 * Per-project issue type collection preferences (`project_name` -> `collection_name`)
 */
project_collection_prefs: { [key in string]: string }, 
/**
 * Active multi-agent step groups (`multi_model`, `multi_prompt`, `matrixed`)
 */
multi_agent_groups: Array<MultiAgentGroup>, };

export type AgentState = { 
/**
 * Non-secret Git configuration captured at launch.
 */
git_context: GitExecutionConfig | null, id: string, ticket_id: string, ticket_type: string, project: string, status: string, started_at: string, last_activity: string, last_message: string | null, paired: boolean, 
/**
 * The terminal session name for this agent (for recovery)
 */
session_name: string | null, 
/**
 * Which session wrapper manages this agent: "tmux", "vscode", or "cmux" (None = legacy tmux)
 */
session_wrapper: string | null, 
/**
 * Session window reference ID (top-level grouping: cmux window, tmux session, etc.)
 */
session_window_ref: string | null, 
/**
 * Session context reference ID (mid-level: cmux workspace, tmux window, etc.)
 */
session_context_ref: string | null, 
/**
 * Session pane reference ID (leaf-level: cmux surface, tmux pane, etc.)
 */
session_pane_ref: string | null, 
/**
 * Hash of the last captured pane content (for change detection)
 */
content_hash: string | null, 
/**
 * Current step in the ticket workflow (e.g., "plan", "implement", "test")
 */
current_step: string | null, 
/**
 * When the current step started (for timeout detection)
 */
step_started_at: string | null, 
/**
 * Last time content changed in the session (for hung detection)
 */
last_content_change: string | null, 
/**
 * PR/MR URL if created during the "pr" step
 */
pr_url: string | null, 
/**
 * Code review request (PR/MR) number
 */
pr_number: bigint | null, 
/**
 * Repository in "owner/repo" format on the configured git provider
 */
repo: string | null, 
/**
 * Last known PR/MR status ("open", "approved", "`changes_requested`", "merged", "closed")
 */
pr_status: string | null, 
/**
 * Completed steps for this ticket
 */
completed_steps: Array<string>, 
/**
 * LLM tool used (e.g., "claude", "gemini", "codex")
 */
llm_tool: string | null, 
/**
 * LLM model alias (e.g., "opus", "sonnet", "gpt-4o")
 */
llm_model: string | null, 
/**
 * Launch mode: `default|yolo|docker[-yolo]|coder[-yolo]|ssh[-yolo]`
 */
launch_mode: string | null, 
/**
 * Review state for `awaiting_input` agents
 * Values: "`pending_plan`", "`pending_visual`", "`pending_proof`", "`pending_pr_creation`", "`pending_pr_merge`"
 */
review_state: string | null, 
/**
 * Server process ID for visual review cleanup (if applicable)
 */
dev_server_pid: number | null, 
/**
 * Path to the git worktree for this ticket (per-ticket isolation)
 */
worktree_path: string | null, 
/**
 * Name of the `RemoteHost` this agent's CLI runs on over SSH (None = local)
 */
remote_host: string | null, 
/**
 * Launch context fixed at launch time; `complete_step` reads it back to build subsequent step commands with the same delegator/tool/model.
 */
step_launch_context: StepLaunchContext | null, 
/**
 * Name of the resolved execution target this agent launched on.
 */
target_name: string | null, 
/**
 * Shutdown recovery strategy.
 */
shutdown_recovery?: ShutdownRecovery | null, };

export type CompletedTicket = { ticket_id: string, ticket_type: string, project: string, summary: string, completed_at: string, pr_url: string | null, output_tickets: Array<string>, };

export type MultiAgentGroup = { 
/**
 * Unique group identifier
 */
group_id: string, 
/**
 * Ticket this group belongs to
 */
ticket_id: string, 
/**
 * Step name being executed
 */
step_name: string, 
/**
 * Step type (`multi_model`, `multi_prompt`, `matrixed`)
 */
step_type: string, 
/**
 * Agent IDs in this group (populated as sub-agents launch)
 */
agent_ids: Array<string>, 
/**
 * Current execution phase
 */
phase: MultiAgentPhase, 
/**
 * Collected outputs from completed sub-agents, keyed by `variant_key`
 * (delegator name for `multi_model`, index for `multi_prompt`,
 * `{delegator}:{prompt_idx}` for `matrixed`).
 */
individual_outputs: { [key in string]: JsonValue }, 
/**
 * Final aggregated output (set when phase = Complete)
 */
aggregated_output: JsonValue | null, 
/**
 * Total sub-agents expected (`agent_ids.len() + pending_launches.len()`).
 */
expected_total: number, 
/**
 * Sub-agents that still need launching (waiting for a free slot).
 */
pending_launches: Array<PendingSubAgent>, 
/**
 * Maps launched `agent_id` to the `variant_key` used as the output key.
 */
agent_variant_keys: { [key in string]: string }, };

export type MultiAgentPhase = "fan_out" | "voting" | "complete" | "failed";

export type PendingSubAgent = { 
/**
 * Delegator (from `config.delegators`) this sub-agent should use.
 */
delegator_name: string, 
/**
 * Fully-rendered prompt text for this sub-agent.
 */
prompt: string, 
/**
 * Key under which this sub-agent's output is recorded (see `individual_outputs`).
 */
variant_key: string, };

export type IssueTypeResponse = { key: string, name: string, description: string, mode: string, glyph: string, color: string | null, project_required: boolean, source: string, 
/**
 * Owning collection under resolution-order lookup
 */
collection?: string, fields: Array<FieldResponse>, steps: Array<StepResponse>, };

export type IssueTypeSummary = { key: string, name: string, description: string, mode: string, glyph: string, color?: string, source: string, 
/**
 * Owning collection under resolution-order lookup
 */
collection?: string, stepCount: number, };

export type CreateIssueTypeRequest = { key: string, name: string, description: string, mode: string, glyph: string, color: string | null, project_required: boolean, fields: Array<CreateFieldRequest>, steps: Array<CreateStepRequest>, 
/**
 * Target collection (defaults to the active collection)
 */
collection?: string, };

export type UpdateIssueTypeRequest = { name: string | null, description: string | null, mode: string | null, glyph: string | null, color: string | null, project_required: boolean | null, fields: Array<CreateFieldRequest> | null, steps: Array<CreateStepRequest> | null, };

export type FieldResponse = { name: string, description: string, field_type: string, required: boolean, default: string | null, options: Array<string>, placeholder: string | null, max_length: number | null, user_editable: boolean, };

export type CreateFieldRequest = { name: string, description: string, field_type: string, required: boolean, default: string | null, options: Array<string>, placeholder: string | null, max_length: number | null, user_editable: boolean, };

export type StepResponse = { name: string, display_name: string | null, prompt: string, outputs: Array<string>, allowed_tools: Array<string>, 
/**
 * Type of review required: "none", "plan", "visual", "pr", "proof"
 */
review_type: string, next_step: string | null, permission_mode: string, };

export type CreateStepRequest = { name: string, display_name: string | null, prompt: string, outputs: Array<string>, allowed_tools: Array<string>, 
/**
 * Type of review required: "none", "plan", "visual", "pr", "proof"
 */
review_type: string, next_step: string | null, permission_mode: string, };

export type UpdateStepRequest = { display_name: string | null, prompt: string | null, outputs: Array<string> | null, allowed_tools: Array<string> | null, 
/**
 * Type of review required: "none", "plan", "visual", "pr", "proof"
 */
review_type: string | null, next_step: string | null, permission_mode: string | null, };

export type CollectionResponse = { name: string, description: string, types: Array<string>, is_active: boolean, 
/**
 * Collection semver (present for hosted collections).
 */
version?: string | null, 
/**
 * Publisher identifier (present for hosted collections).
 */
publisher?: string | null, 
/**
 * Human author/attribution (present for hosted collections).
 */
author?: string | null, 
/**
 * Link to the collection's source repository or project page.
 */
url?: string | null, 
/**
 * SPDX license id.
 */
license?: string | null, 
/**
 * Provenance tier: `official` or `community`.
 */
tier: string, 
/**
 * Bare filename of the collection's SVG icon, next to its manifest.
 */
icon_path?: string | null, 
/**
 * ISO-8601 date the collection was first published.
 */
created?: string | null, 
/**
 * ISO-8601 date of the last substantive revision.
 */
updated?: string | null, 
/**
 * Descriptive workflow hints (present for hosted collections).
 */
workflow_hints?: WorkflowHintsDto | null, };

export type WorkflowHintsDto = { loop_kind: string | null, memory_surfaces: Array<string>, review_gates: Array<string>, external_tools: Array<string>, stop_conditions: Array<string>, runner_semantics: string, };

export type HealthResponse = { status: string, version: string, 
/**
 * Top-level directory name of the operator working root (e.g. "acme").
 */
directory_name: string, 
/**
 * Non-reversible fingerprint of the working root's canonical path.
 */
directory_id: string, };

export type StatusResponse = { status: string, version: string, 
/**
 * Top-level directory name of the operator working root (e.g. "acme").
 */
directory_name: string, 
/**
 * Non-reversible fingerprint of the working root's canonical path.
 */
directory_id: string, issuetype_count: number, collection_count: number, active_collection: string, };

export type SectionDto = { 
/**
 * Stable section id (e.g. "config", "connections", "kanban").
 */
id: string, label: string, 
/**
 * Health: "green" | "yellow" | "red" | "gray".
 */
health: string, description: string, 
/**
 * Section ids that must be Green before this section is usable.
 */
prerequisites: Array<string>, 
/**
 * Whether all prerequisites are met. Sections are always returned (the web
 * UI styles unmet ones as locked) rather than hidden by progressive disclosure.
 */
met: boolean, children: Array<SectionRowDto>, };

export type SectionRowDto = { 
/**
 * Stable, section-scoped row id. Clients use it as a tree key and to route
 * row-specific commands without matching on the (mutable) display label.
 * Dynamic rows carry their entity key (issue-type key, project name);
 * static rows carry a fixed slug (e.g. "git-token").
 */
id: string, 
/**
 * Nesting depth within the section (1 = direct child, 2 = grandchild).
 * Lets clients rebuild the tree (e.g. LLM tools → model aliases).
 */
depth: number, label: string, description: string, 
/**
 * Icon hint (e.g. "check", "warning", "tool", "folder").
 */
icon: string, 
/**
 * Optional vendor-brand basename (e.g. "ollama"). When set, the web UI
 * renders `/icons/{brand_icon}.svg` instead of the semantic `icon`.
 */
brand_icon: string | null, 
/**
 * Health: "green" | "yellow" | "red" | "gray".
 */
health: string, 
/**
 * Browser-openable actions for this row (links shown in the web UI).
 */
actions: Array<RowActionDto>, };

export type RowActionDto = { 
/**
 * Display label for the action button/link.
 */
label: string, 
/**
 * Browser URL the action opens.
 */
url: string, };

export type SupportStatus = "proto" | "alpha" | "beta" | "ga";

export type IntegrationCatalogEntryDto = { 
/**
 * Vertical slug (e.g. "kanban", "model", "git", "session", "editor").
 */
vertical: string, 
/**
 * Human label for the vertical (e.g. "Kanban Provider").
 */
vertical_label: string, 
/**
 * Stable entry slug within the vertical (e.g. "jira", "anthropic-api").
 */
slug: string, 
/**
 * Display label for the entry (e.g. "Jira", "Anthropic").
 */
label: string, 
/**
 * Absolute docs URL, or `null` if undocumented.
 */
docs_url: string | null, 
/**
 * Whether this entry carries a curated README badge.
 */
readme_badge: boolean, 
/**
 * Official support / maturity status.
 */
status: SupportStatus, premium: boolean, 
/**
 * Implemented session controllers for an IDE; absent for other categories.
 */
session_wrappers: Array<string> | null, };

export type KanbanProviderCatalogEntry = { 
/**
 * Stable lowercase slug ("jira" | "linear" | "github").
 */
slug: string, 
/**
 * Human-readable name (e.g. "Jira Cloud", "GitHub Projects").
 */
display_name: string, 
/**
 * One-line connect description shown next to the provider.
 */
description: string, 
/**
 * Credential/token page opened when the user chooses to configure it.
 */
setup_url: string, 
/**
 * VS Code codicon hint (rendered as `$(icon)` in the picker).
 */
icon: string, 
/**
 * Whether at least one instance of this provider is already configured.
 */
configured: boolean, };

export type WorkflowExportResponse = { 
/**
 * The ticket the workflow was generated from.
 */
ticket_id: string, 
/**
 * The issue type key that supplied the step structure.
 */
issuetype_key: string, 
/**
 * Suggested filename for saving the workflow (`<ticket-id>.workflow.js`).
 */
suggested_filename: string, 
/**
 * The generated `.js` workflow source.
 */
contents: string, };

export type WorkflowPreviewResponse = { 
/**
 * The issue type key the preview was generated from.
 */
issuetype_key: string, 
/**
 * Suggested filename for saving the preview (`<KEY>.preview.workflow.js`).
 */
suggested_filename: string, 
/**
 * The generated `.js` workflow source (placeholder ticket values).
 */
contents: string, };

export type WorkflowFormatDto = { 
/**
 * Stable slug (e.g. "claude", "agnt") - the value the `format` query param takes.
 */
slug: string, 
/**
 * Display label (e.g. "Claude Workflow").
 */
label: string, 
/**
 * File extension of the emitted artifact, no leading dot (e.g. "js", "json").
 */
extension: string, 
/**
 * Official support / maturity status (from the catalog).
 */
status: SupportStatus, 
/**
 * Absolute docs URL, or `null` if undocumented.
 */
docs_url: string | null, };

export type CreateTicketRequest = { 
/**
 * Template type key (feature, fix, spike, investigation, task).
 */
template: string, 
/**
 * Project the ticket targets (filled into the template's `project` value).
 */
project: string | null, 
/**
 * One-line summary (filled into the template's `summary` value).
 */
summary: string | null, 
/**
 * Additional Handlebars values for the template. Explicit `project`/
 * `summary` fields take precedence over the same keys here.
 */
values: { [key in string]: string }, };

export type CreateTicketResponse = { 
/**
 * The created ticket's id (e.g. `FEAT-1234`).
 */
id: string, 
/**
 * The ticket filename written to the queue.
 */
filename: string, 
/**
 * The absolute path the ticket was written to.
 */
path: string, };

export type CreateAlertRequest = { 
/**
 * Where the alert came from (e.g. `pagerduty`, `sentry`).
 */
source: string, 
/**
 * The alert message / summary.
 */
message: string, 
/**
 * Severity label (e.g. `S1`, `S2`).
 */
severity: string, 
/**
 * Optional project the investigation targets.
 */
project: string | null, };

export type CreateAlertResponse = { 
/**
 * The created investigation ticket's id.
 */
id: string, 
/**
 * The investigation ticket filename written to the queue.
 */
filename: string, };

export type SkillEntry = { 
/**
 * Tool this skill belongs to (e.g., "claude", "codex")
 */
tool_name: string, 
/**
 * Filename of the skill (e.g., "commit.md")
 */
filename: string, 
/**
 * Full path to the skill file
 */
file_path: string, 
/**
 * Scope: "global" or "project"
 */
scope: string, };

export type SkillsResponse = { 
/**
 * List of discovered skills
 */
skills: Array<SkillEntry>, 
/**
 * Total count
 */
total: number, };

export type DelegatorResponse = { 
/**
 * Optional Git identity, HTTPS credential reference, and runtime settings.
 */
git?: GitExecutionConfig | null, 
/**
 * Unique name
 */
name: string, 
/**
 * LLM tool name (e.g., "claude")
 */
llm_tool: string, 
/**
 * Model alias (e.g., "opus")
 */
model: string, 
/**
 * Optional display name
 */
display_name: string | null, 
/**
 * Arbitrary model properties
 */
model_properties: { [key in string]: string }, 
/**
 * Name of a declared `ModelServer`. `None` means use the `llm_tool`'s implicit vendor default.
 */
model_server: string | null, 
/**
 * Optional launch configuration
 */
launch_config: DelegatorLaunchConfigDto | null, 
/**
 * Declarative reference to a remote, named agent (AGNT, `OpenAI`, ...). When
 * set, the delegator is export-only and cannot be launched locally.
 */
remote_agent: RemoteAgentRef | null, };

export type DelegatorsResponse = { 
/**
 * List of delegators
 */
delegators: Array<DelegatorResponse>, 
/**
 * Total count
 */
total: number, };

export type CreateDelegatorRequest = { 
/**
 * Optional Git identity, HTTPS credential reference, and runtime settings.
 */
git?: GitExecutionConfig | null, 
/**
 * Unique name for the delegator
 */
name: string, 
/**
 * LLM tool name (must match a detected tool)
 */
llm_tool: string, 
/**
 * Model alias
 */
model: string, 
/**
 * Optional display name
 */
display_name: string | null, 
/**
 * Arbitrary model properties
 */
model_properties: { [key in string]: string }, 
/**
 * Name of a declared `ModelServer`. `None` means use the `llm_tool`'s implicit vendor default.
 */
model_server: string | null, 
/**
 * Optional launch configuration
 */
launch_config: DelegatorLaunchConfigDto | null, 
/**
 * Declarative reference to a remote, named agent (AGNT, `OpenAI`, ...). When
 * set, the delegator is export-only and cannot be launched locally.
 */
remote_agent: RemoteAgentRef | null, };

export type DelegatorLaunchConfigDto = { 
/**
 * Run in YOLO mode
 */
yolo: boolean, 
/**
 * Permission mode override
 */
permission_mode?: string | null, 
/**
 * Additional CLI flags
 */
flags: Array<string>, 
/**
 * Override global `git.use_worktrees` (None = use global setting)
 */
use_worktrees?: boolean | null, 
/**
 * Whether to create a git branch for the ticket (None = default behavior)
 */
create_branch?: boolean | null, 
/**
 * Run in docker container (None = use global `launch.docker.enabled`)
 */
docker?: boolean | null, 
/**
 * Prompt text to prepend before the generated step prompt
 */
prompt_prefix?: string | null, 
/**
 * Prompt text to append after the generated step prompt
 */
prompt_suffix?: string | null, 
/**
 * Override global relay auto-inject MCP setting per-delegator (None = use global setting)
 */
operator_relay?: boolean | null, 
/**
 * Name of a declared `RemoteHost` to launch the agent CLI on over SSH (None = local).
 * DEPRECATED: prefer `target`.
 */
host?: string | null, 
/**
 * Name of an execution target (explicit `[[targets]]` entry, synthesized
 * `local`/`docker`, or a `[[hosts]]` name). Supersedes `docker`/`host`.
 */
target?: string | null, };

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null;

export type LlmTask = { 
/**
 * LLM task ID (e.g., Claude delegate mode task UUID)
 */
id?: string | null, 
/**
 * LLM task status: "open" or "resolved"
 */
status?: string | null, 
/**
 * List of task IDs that must resolve before this task
 */
blocked_by?: Array<string>, };

export type JiraSearchResponse = { 
/**
 * List of issues matching the JQL query
 */
issues: Array<JiraIssue>, };

export type JiraIssue = { 
/**
 * Internal Jira issue ID
 */
id: string, 
/**
 * Issue key (e.g., "PROJ-123")
 */
key: string, 
/**
 * Issue fields containing summary, status, etc.
 */
fields: JiraIssueFields, };

export type JiraIssueFields = { 
/**
 * Issue summary/title
 */
summary: string, 
/**
 * Issue description in ADF format
 */
description: JiraDescription | null, 
/**
 * Issue type (Bug, Story, Task, etc.)
 */
issuetype: JiraIssueTypeRef, 
/**
 * Current workflow status
 */
status: JiraStatusRef, 
/**
 * Assigned user (if any)
 */
assignee: JiraUser | null, 
/**
 * Issue priority (if set)
 */
priority: JiraPriority | null, };

export type JiraUser = { 
/**
 * Atlassian account ID (e.g., "5e3f7acd9876543210abcdef")
 */
accountId: string, 
/**
 * User's display name
 */
displayName: string, 
/**
 * User's email address (may be hidden by privacy settings)
 */
emailAddress: string | null, 
/**
 * Avatar URLs in various sizes
 */
avatarUrls: JiraAvatarUrls | null, };

export type JiraAvatarUrls = { 
/**
 * 48x48 pixel avatar URL
 */
"48x48": string | null, };

export type JiraDescription = { 
/**
 * ADF content nodes - parsed to extract plain text
 */
content: Array<JsonValue> | null, };

export type JiraIssueTypeRef = { 
/**
 * Issue type ID (e.g., "10001")
 */
id: string | null, 
/**
 * Issue type name (e.g., "Bug", "Story", "Task")
 */
name: string, };

export type JiraStatusRef = { 
/**
 * Status name (e.g., "To Do", "In Progress", "Done")
 */
name: string, };

export type JiraPriority = { 
/**
 * Priority name (e.g., "Highest", "High", "Medium", "Low", "Lowest")
 */
name: string, };

export type JiraProjectStatus = { 
/**
 * List of statuses available for this issue type
 */
statuses: Array<JiraStatus>, };

export type JiraStatus = { 
/**
 * Status name (e.g., "To Do", "In Progress", "Done")
 */
name: string, };

export type VsCodeSessionInfo = { 
/**
 * Wrapper type identifier (always "vscode")
 */
wrapper: string, 
/**
 * Actual port the webhook server is listening on
 */
port: number, 
/**
 * Process ID of VS Code
 */
pid: number, 
/**
 * Extension version
 */
version: string, 
/**
 * ISO timestamp when server started
 */
startedAt: string, 
/**
 * Workspace folder path
 */
workspace: string, };

export type VsCodeHealthResponse = { 
/**
 * Health status (always "ok" when healthy)
 */
status: string, 
/**
 * Extension version
 */
version: string, 
/**
 * Port the server is listening on
 */
port: number, };

export type VsCodeActivityState = "idle" | "running" | "unknown";

export type VsCodeTerminalState = { 
/**
 * Terminal name
 */
name: string, 
/**
 * Process ID if available
 */
pid?: number, 
/**
 * Current activity state
 */
activity: VsCodeActivityState, 
/**
 * Unix timestamp when terminal was created (milliseconds)
 */
createdAt: number, };

export type VsCodeTerminalCreateOptions = { 
/**
 * Terminal name (e.g., "op-FEAT-123")
 */
name: string, 
/**
 * Working directory for the terminal
 */
workingDir?: string, 
/**
 * Environment variables to set
 */
env?: { [key in string]: string }, };

export type VsCodeSendCommandRequest = { 
/**
 * Command to execute
 */
command: string, };

export type VsCodeSuccessResponse = { 
/**
 * Whether the operation succeeded
 */
success: boolean, 
/**
 * Optional terminal name (for create operations)
 */
name?: string, };

export type VsCodeExistsResponse = { 
/**
 * Whether the terminal exists
 */
exists: boolean, };

export type VsCodeActivityResponse = { 
/**
 * Current activity state
 */
activity: VsCodeActivityState, };

export type VsCodeListResponse = { 
/**
 * List of managed terminals
 */
terminals: Array<VsCodeTerminalState>, };

export type VsCodeErrorResponse = { 
/**
 * Error message
 */
error: string, };

export type VsCodeTicketStatus = "in-progress" | "queue" | "completed";

export type VsCodeTicketInfo = { 
/**
 * Ticket ID (e.g., "FEAT-123")
 */
id: string, 
/**
 * Ticket title from markdown heading
 */
title: string, 
/**
 * Ticket type key (e.g., "FEAT", "FIX", or any custom type)
 */
type: string, 
/**
 * Current status
 */
status: VsCodeTicketStatus, 
/**
 * Path to the ticket markdown file
 */
filePath: string, 
/**
 * Terminal name if in-progress (e.g., "op-FEAT-123")
 */
terminalName?: string, };

export type VsCodeModelOption = "sonnet" | "opus" | "haiku";

export type VsCodeLaunchOptions = { 
/**
 * Named delegator to use (takes precedence over model)
 */
delegator: string | null, 
/**
 * Model to use (sonnet, opus, haiku) - fallback when no delegator
 */
model: VsCodeModelOption, 
/**
 * YOLO mode - auto-accept all prompts
 */
yoloMode: boolean, 
/**
 * Resume from existing session (uses `session_id` from ticket)
 */
resumeSession: boolean, 
/**
 * Execution-target override by name (None = delegator/default resolution)
 */
target?: string, };

export type VsCodeTicketMetadata = { 
/**
 * Ticket ID
 */
id: string, 
/**
 * Current status
 */
status: string, 
/**
 * Current step name
 */
step: string, 
/**
 * Priority level
 */
priority: string, 
/**
 * Project name
 */
project: string, 
/**
 * Session UUIDs by step name
 */
sessions?: { [key in string]: string }, 
/**
 * Git worktree path if using per-ticket worktrees
 */
worktreePath?: string, 
/**
 * Git branch name
 */
branch?: string, };

