// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessKeySummary } from "./AccessKeySummary";

/**
 * All access keys, active and revoked.
 */
export type AccessKeyListResponse = { 
/**
 * The keys.
 */
keys: Array<AccessKeySummary>, };
