// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scope } from "./Scope";

/**
 * Access key metadata. Carries no secret and no hash.
 */
export type AccessKeySummary = { 
/**
 * Stable identifier, safe to display and to reference for revocation.
 */
id: string, 
/**
 * Human-readable label.
 */
name: string, 
/**
 * Scopes granted.
 */
scopes: Array<Scope>, 
/**
 * When the key was created.
 */
created_at: string, 
/**
 * When the key expires.
 */
expires_at: string, 
/**
 * When the key was last exchanged for a token; `None` if never used.
 */
last_used_at?: string | null, 
/**
 * When the key was revoked; `None` while active.
 */
revoked_at?: string | null, };
