// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agent Client Protocol (ACP) agent configuration.
 *
 * Operator runs as an ACP agent over stdio when editors (Zed, `JetBrains`,
 * Emacs `agent-shell`, Kiro, etc.) spawn `operator acp`. Each ACP session
 * maps to an in-progress ACP ticket and a delegator subprocess.
 */
export type AcpConfig = { 
/**
 * Whether the dashboard advertises the `operator acp` stdio entrypoint
 * (and editor-config snippet actions). Set to false on machines that
 * shouldn't be used as ACP agents.
 */
stdio_advertised: boolean, 
/**
 * Name of the delegator (from `[[delegators]]`) to use for ACP prompts.
 * If unset or not found, falls back to the operator's default delegator
 * resolution.
 */
default_delegator: string | null, 
/**
 * Maximum number of concurrent ACP sessions. New `session/new` requests
 * beyond this limit are rejected with a JSON-RPC error.
 */
max_concurrent_sessions: number, };
