// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActiveAgentResponse } from "./ActiveAgentResponse";

/**
 * Response for active agents list
 */
export type ActiveAgentsResponse = { 
/**
 * List of active agents
 */
agents: Array<ActiveAgentResponse>, 
/**
 * Total count of active agents
 */
count: number, };
