// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single active agent
 */
export type ActiveAgentResponse = { 
/**
 * Agent ID (e.g., "op-gamesvc-001")
 */
id: string, 
/**
 * Associated ticket ID (e.g., "FEAT-042")
 */
ticket_id: string, 
/**
 * Ticket type: FEAT, FIX, INV, SPIKE
 */
ticket_type: string, 
/**
 * Project being worked on
 */
project: string, 
/**
 * Agent status: running, awaiting_input, completing
 */
status: string, 
/**
 * Execution mode: autonomous, paired
 */
mode: string, 
/**
 * When the agent started (ISO 8601)
 */
started_at: string, 
/**
 * Current workflow step
 */
current_step: string | null, };
