// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentState = { id: string, ticket_id: string, ticket_type: string, project: string, status: string, started_at: string, last_activity: string, last_message: string | null, paired: boolean, 
/**
 * The tmux session name for this agent (for recovery)
 */
session_name: string | null, 
/**
 * Hash of the last captured pane content (for change detection)
 */
content_hash: string | null, 
/**
 * Current step in the ticket workflow (e.g., "plan", "implement", "test")
 */
current_step: string | null, 
/**
 * When the current step started (for timeout detection)
 */
step_started_at: string | null, 
/**
 * Last time content changed in the session (for hung detection)
 */
last_content_change: string | null, 
/**
 * PR URL if created during "pr" step
 */
pr_url: string | null, 
/**
 * PR number for GitHub API tracking
 */
pr_number: bigint | null, 
/**
 * GitHub repo in format "owner/repo"
 */
github_repo: string | null, 
/**
 * Last known PR status ("open", "approved", "changes_requested", "merged", "closed")
 */
pr_status: string | null, 
/**
 * Completed steps for this ticket
 */
completed_steps: Array<string>, 
/**
 * LLM tool used (e.g., "claude", "gemini", "codex")
 */
llm_tool: string | null, 
/**
 * Launch mode: "default", "yolo", "docker", "docker-yolo"
 */
launch_mode: string | null, 
/**
 * Review state for awaiting_input agents
 * Values: "pending_plan", "pending_visual", "pending_pr_creation", "pending_pr_merge"
 */
review_state: string | null, 
/**
 * Server process ID for visual review cleanup (if applicable)
 */
dev_server_pid: number | null, 
/**
 * Path to the git worktree for this ticket (per-ticket isolation)
 */
worktree_path: string | null, };
