// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentsConfiguration = { max_parallel: number, cores_reserved: number, max_agents_per_repo: number, health_check_interval: bigint, generation_timeout_secs: bigint, sync_interval: bigint, step_timeout: bigint, silence_threshold: bigint, };
