// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentsConfig = { max_parallel: number, cores_reserved: number, health_check_interval: bigint, 
/**
 * Timeout in seconds for each agent generation (default: 300 = 5 min)
 */
generation_timeout_secs: bigint, 
/**
 * Interval in seconds between ticket-session syncs (default: 60)
 */
sync_interval: bigint, 
/**
 * Maximum seconds a step can run before timing out (default: 1800 = 30 min)
 */
step_timeout: bigint, 
/**
 * Seconds of tmux silence before considering agent awaiting input (default: 30)
 */
silence_threshold: bigint, };
