// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { RemoteAgentRef } from "./RemoteAgentRef";
import type { XOperator } from "./XOperator";

/**
 * A canonical cross-tool agent definition (serialized as `agent-profile.json`).
 *
 * Shared core (`name`/`provider`/`model`/`system_prompt`/`skills`/`mcp_servers`/
 * `tools`) plus namespaced extension bags. `x_operator` is typed (Operator owns
 * those fields); `x_agnt` and `x_openai` are opaque per-platform pass-throughs.
 */
export type AgentProfile = { 
/**
 * Unique agent name (maps to [`Delegator::name`]).
 */
name: string, 
/**
 * Inference provider / CLI tool (maps to [`Delegator::llm_tool`]).
 */
provider: string, 
/**
 * Model alias or id (maps to [`Delegator::model`]).
 */
model: string, 
/**
 * System prompt. Operator has no first-class system prompt, so this is
 * preserved opaquely across import (see [`Delegator::unmapped_core`]).
 */
system_prompt: string | null, 
/**
 * Named skills. Preserved opaquely across import.
 */
skills: Array<string>, 
/**
 * MCP server names. Preserved opaquely across import.
 */
mcp_servers: Array<string>, 
/**
 * Tool names. Preserved opaquely across import.
 */
tools: Array<string>, 
/**
 * Declarative reference to a remote, named agent (AGNT, `OpenAI`, ...).
 * `None` = a locally launchable agent, not bound to a remote platform.
 */
remote_agent: RemoteAgentRef | null, 
/**
 * Operator-owned extension fields (typed). `None` when the agent carries no
 * Operator-specific configuration.
 */
x_operator: XOperator | null, 
/**
 * AGNT-owned extension fields, opaque (`memory`, `assignedWorkflows`,
 * `creditLimit`, ...). Operator never interprets this — pure pass-through.
 */
x_agnt: JsonValue | null, 
/**
 * OpenAI-owned extension fields, opaque (`instructions`, `tools`,
 * `tool_resources`, `metadata`, thread refs, ...). Mirror of `x_agnt` for a
 * second platform — never interpreted. This field is the whole per-tool cost
 * of adding `OpenAI`: a passthrough bag, no mapping logic.
 */
x_openai: JsonValue | null, };
