// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentsConfigurationPatch = { max_parallel: number | null, cores_reserved: number | null, max_agents_per_repo: number | null, health_check_interval: bigint | null, generation_timeout_secs: bigint | null, sync_interval: bigint | null, step_timeout: bigint | null, silence_threshold: bigint | null, };
