// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StepLaunchContext } from "./StepLaunchContext";

export type AgentState = { id: string, ticket_id: string, ticket_type: string, project: string, status: string, started_at: string, last_activity: string, last_message: string | null, paired: boolean, 
/**
 * The terminal session name for this agent (for recovery)
 */
session_name: string | null, 
/**
 * Which session wrapper manages this agent: "tmux", "vscode", or "cmux" (None = legacy tmux)
 */
session_wrapper: string | null, 
/**
 * Session window reference ID (top-level grouping: cmux window, tmux session, etc.)
 */
session_window_ref: string | null, 
/**
 * Session context reference ID (mid-level: cmux workspace, tmux window, etc.)
 */
session_context_ref: string | null, 
/**
 * Session pane reference ID (leaf-level: cmux surface, tmux pane, etc.)
 */
session_pane_ref: string | null, 
/**
 * Hash of the last captured pane content (for change detection)
 */
content_hash: string | null, 
/**
 * Current step in the ticket workflow (e.g., "plan", "implement", "test")
 */
current_step: string | null, 
/**
 * When the current step started (for timeout detection)
 */
step_started_at: string | null, 
/**
 * Last time content changed in the session (for hung detection)
 */
last_content_change: string | null, 
/**
 * PR/MR URL if created during the "pr" step
 */
pr_url: string | null, 
/**
 * Code review request (PR/MR) number
 */
pr_number: bigint | null, 
/**
 * Repository in "owner/repo" format on the configured git provider
 */
repo: string | null, 
/**
 * Last known PR/MR status ("open", "approved", "`changes_requested`", "merged", "closed")
 */
pr_status: string | null, 
/**
 * Completed steps for this ticket
 */
completed_steps: Array<string>, 
/**
 * LLM tool used (e.g., "claude", "gemini", "codex")
 */
llm_tool: string | null, 
/**
 * LLM model alias (e.g., "opus", "sonnet", "gpt-4o")
 */
llm_model: string | null, 
/**
 * Launch mode: `default|yolo|docker[-yolo]|coder[-yolo]|ssh[-yolo]`
 * (derived from the resolved execution target; parse with `agents::parse_launch_mode`, never substring-match)
 */
launch_mode: string | null, 
/**
 * Review state for `awaiting_input` agents
 * Values: "`pending_plan`", "`pending_visual`", "`pending_pr_creation`", "`pending_pr_merge`"
 */
review_state: string | null, 
/**
 * Server process ID for visual review cleanup (if applicable)
 */
dev_server_pid: number | null, 
/**
 * Path to the git worktree for this ticket (per-ticket isolation)
 */
worktree_path: string | null, 
/**
 * Name of the `RemoteHost` this agent's CLI runs on over SSH (None = local)
 */
remote_host: string | null, 
/**
 * Launch context fixed at launch time; `complete_step` reads it back to build subsequent step commands with the same delegator/tool/model.
 */
step_launch_context: StepLaunchContext | null, 
/**
 * Name of the resolved execution target this agent launched on
 */
target_name: string | null, };
