// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Full details for a single agent
 */
export type AgentDetailResponse = { 
/**
 * Agent ID (UUID)
 */
id: string, 
/**
 * Associated ticket ID (e.g., "FEAT-042")
 */
ticket_id: string, 
/**
 * Ticket type: FEAT, FIX, INV, SPIKE
 */
ticket_type: string, 
/**
 * Project being worked on
 */
project: string, 
/**
 * Agent status: running, `awaiting_input`, completing, orphaned
 */
status: string, 
/**
 * When the agent started (ISO 8601)
 */
started_at: string, 
/**
 * Last activity timestamp (ISO 8601)
 */
last_activity: string, 
/**
 * Current workflow step
 */
current_step: string | null, 
/**
 * LLM tool used (e.g., "claude", "gemini", "codex")
 */
llm_tool: string | null, 
/**
 * LLM model alias (e.g., "opus", "sonnet", "gpt-4o")
 */
llm_model: string | null, 
/**
 * Launch mode: "default", "yolo", "docker", "docker-yolo"
 */
launch_mode: string | null, 
/**
 * PR URL if created during "pr" step
 */
pr_url: string | null, 
/**
 * Last known PR status ("open", "approved", "`changes_requested`", "merged", "closed")
 */
pr_status: string | null, 
/**
 * Which session wrapper is in use: "tmux", "vscode", "cmux", or "zellij"
 */
session_wrapper: string | null, 
/**
 * Review state for `awaiting_input` agents
 */
review_state: string | null, 
/**
 * Completed steps for this ticket
 */
completed_steps: Array<string>, 
/**
 * Path to the git worktree for this ticket
 */
worktree_path: string | null, 
/**
 * Whether this is a paired (interactive) agent
 */
paired: boolean, };
