// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API integrations configuration
 */
export type ApiConfig = { 
/**
 * Interval in seconds between PR status checks (default: 60)
 */
pr_check_interval_secs: bigint, 
/**
 * Interval in seconds between rate limit checks (default: 300)
 */
rate_limit_check_interval_secs: bigint, 
/**
 * Show warning when rate limit remaining is below this percentage (default: 0.2)
 */
rate_limit_warning_threshold: number, };
