// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from creating an ASSESS ticket
 */
export type AssessTicketResponse = { 
/**
 * Ticket ID (e.g., "ASSESS-1234")
 */
ticket_id: string, 
/**
 * Path to the created ticket file
 */
ticket_path: string, 
/**
 * Project name that was assessed
 */
project_name: string, };
