// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of a step attempt
 */
export type AttemptStatus = "pending" | "setting" | "running" | "awaitinginput" | "inreview" | "completed" | "failed" | "cancelled" | "orphaned";
