// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Auto-generation strategies for fields
 */
export type AutoGenStrategy = "id" | "date" | "branch" | "status";
