// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrandingConfig } from "./BrandingConfig";

/**
 * Backstage integration configuration
 */
export type BackstageConfig = { 
/**
 * Whether Backstage integration is enabled
 */
enabled: boolean, 
/**
 * Port for the Backstage server
 */
port: number, 
/**
 * Auto-start Backstage server when TUI launches
 */
auto_start: boolean, 
/**
 * Subdirectory within state_path for Backstage installation
 */
subpath: string, 
/**
 * Subdirectory within backstage path for branding customization
 */
branding_subpath: string, 
/**
 * Base URL for downloading backstage-server binary
 */
release_url: string, 
/**
 * Optional local path to backstage-server binary
 * If set, this is used instead of downloading from release_url
 */
local_binary_path: string | null, 
/**
 * Branding and theming configuration
 */
branding: BrandingConfig, };
