// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the deployment sits in the one-time admin-creation sequence.
 */
export type BootstrapState = "uninitialized" | "awaiting_password" | "complete";
