// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Claim the admin account and set its password.
 */
export type BootstrapSubmitRequest = { 
/**
 * The out-of-band temporary password, when
 * `requires_temporary_password` is set. Never persisted or logged.
 */
temporary_password?: string | null, 
/**
 * The admin password to set. Never persisted in plaintext or logged.
 */
new_password: string, };
