// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BootstrapState } from "./BootstrapState";

/**
 * Result of a successful bootstrap.
 */
export type BootstrapSubmitResponse = { 
/**
 * The state after submission - `Complete` on success.
 */
state: BootstrapState, 
/**
 * The account name created by bootstrap.
 */
username: string, };
