// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BootstrapState } from "./BootstrapState";

/**
 * Current bootstrap state, readable without authentication so a client can
 * route a first-time visitor to setup rather than to login.
 */
export type BootstrapStatusResponse = { 
/**
 * The state this deployment is in.
 */
state: BootstrapState, 
/**
 * Whether a temporary password was supplied out of band (a mounted
 * bootstrap secret). When true, submission must present it.
 */
requires_temporary_password: boolean, };
