// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThemeColors } from "./ThemeColors";

/**
 * Branding configuration for Backstage portal
 */
export type BrandingConfig = { 
/**
 * App title shown in header
 */
app_title: string, 
/**
 * Organization name
 */
org_name: string, 
/**
 * Path to logo SVG (relative to branding path)
 */
logo_path: string | null, 
/**
 * Theme colors (uses Operator defaults if not set)
 */
colors: ThemeColors, };
