// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output types for classifier steps
 */
export type ClassifierOutputType = "boolean" | "number" | "short_string" | "big_text" | "enum";
