// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassifierOutputType } from "./ClassifierOutputType";

/**
 * Configuration for classifier steps that return structured typed output
 */
export type ClassifierConfig = { 
/**
 * What type of answer the classifier returns
 */
output_type: ClassifierOutputType, 
/**
 * For enum type: the allowed options
 */
options?: Array<string> | null, 
/**
 * For `short_string`: max character length (default 255)
 */
max_length?: number | null, 
/**
 * Agent/delegator to use (overrides issuetype default)
 */
agent?: string | null, };
