// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Placement policy for cmux sessions: where to create new agent terminals
 */
export type CmuxPlacementPolicy = "auto" | "workspace" | "window";
