// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coder workspace target: lifecycle + alias provisioning around the shared
 * SSH remote-launch path. There is no `enabled` field — presence in
 * `[[targets]]` is the enablement.
 */
export type CoderConfig = { 
/**
 * Coder template child workspaces are created from (an allowlist —
 * never per-ticket input)
 */
template: string, 
/**
 * Env var NAME holding the Coder deployment URL
 */
url_env: string, 
/**
 * Env var NAME holding the Coder session token. The variable is stripped
 * from every agent's spawn environment on all target kinds.
 */
token_env: string, 
/**
 * Workspace name prefix for deterministic per-ticket naming
 */
name_prefix: string, 
/**
 * Project root inside the workspace (None = workspace $HOME)
 */
workdir?: string | null, 
/**
 * Stop the workspace when the ticket completes (never delete)
 */
stop_on_complete: boolean, 
/**
 * Bound on workspace create + agent-ready wait
 */
create_timeout_secs: bigint, 
/**
 * Control-plane-reachable `OPERATOR_API_URL` override for detached
 * multi-step (empty/None = reverse tunnel default)
 */
callback_url?: string | null, 
/**
 * Passthrough `-p` template parameters for `coder create`
 */
parameters?: { [key in string]: string }, };
