// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Predefined issue type collections
 */
export type CollectionPreset = "simple" | "dev_kanban" | "devops_kanban" | "custom";
