// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowHintsDto } from "./WorkflowHintsDto";

/**
 * Response for a collection
 */
export type CollectionResponse = { name: string, description: string, types: Array<string>, is_active: boolean, 
/**
 * Collection semver (present for hosted collections).
 */
version?: string | null, 
/**
 * Publisher identifier (present for hosted collections).
 */
publisher?: string | null, 
/**
 * Human author/attribution (present for hosted collections).
 */
author?: string | null, 
/**
 * Link to the collection's source repository or project page.
 */
url?: string | null, 
/**
 * SPDX license id.
 */
license?: string | null, 
/**
 * Provenance tier: `official` or `community`.
 */
tier: string, 
/**
 * Bare filename of the collection's SVG icon, next to its manifest.
 */
icon_path?: string | null, 
/**
 * ISO-8601 date the collection was first published.
 */
created?: string | null, 
/**
 * ISO-8601 date of the last substantive revision.
 */
updated?: string | null, 
/**
 * Descriptive workflow hints (present for hosted collections).
 */
workflow_hints?: WorkflowHintsDto | null, };
