// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowHintsDto } from "./WorkflowHintsDto";

/**
 * Response for a collection
 */
export type CollectionResponse = { name: string, description: string, types: Array<string>, is_active: boolean, 
/**
 * Collection semver (present for hosted collections).
 */
version?: string | null, 
/**
 * Publisher identifier (present for hosted collections).
 */
publisher?: string | null, 
/**
 * Descriptive workflow hints (present for hosted collections).
 */
workflow_hints?: WorkflowHintsDto | null, };
