// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for a collection
 */
export type CollectionResponse = { name: string, description: string, types: Array<string>, is_active: boolean, };
