// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentsConfig } from "./AgentsConfig";
import type { ApiConfig } from "./ApiConfig";
import type { BackstageConfig } from "./BackstageConfig";
import type { GitConfig } from "./GitConfig";
import type { KanbanConfig } from "./KanbanConfig";
import type { LaunchConfig } from "./LaunchConfig";
import type { LlmToolsConfig } from "./LlmToolsConfig";
import type { LoggingConfig } from "./LoggingConfig";
import type { NotificationsConfig } from "./NotificationsConfig";
import type { PathsConfig } from "./PathsConfig";
import type { QueueConfig } from "./QueueConfig";
import type { RestApiConfig } from "./RestApiConfig";
import type { TemplatesConfig } from "./TemplatesConfig";
import type { TmuxConfig } from "./TmuxConfig";
import type { UiConfig } from "./UiConfig";
import type { VersionCheckConfig } from "./VersionCheckConfig";

export type Config = { 
/**
 * List of projects operator can assign work to
 */
projects: Array<string>, agents: AgentsConfig, notifications: NotificationsConfig, queue: QueueConfig, paths: PathsConfig, ui: UiConfig, launch: LaunchConfig, templates: TemplatesConfig, api: ApiConfig, logging: LoggingConfig, tmux: TmuxConfig, llm_tools: LlmToolsConfig, backstage: BackstageConfig, rest_api: RestApiConfig, git: GitConfig, 
/**
 * Kanban provider configuration for syncing issues from Jira, Linear, etc.
 */
kanban: KanbanConfig, 
/**
 * Version check configuration for automatic update notifications
 */
version_check: VersionCheckConfig, };
