// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcpConfig } from "./AcpConfig";
import type { AgentsConfig } from "./AgentsConfig";
import type { ApiConfig } from "./ApiConfig";
import type { Delegator } from "./Delegator";
import type { GitConfig } from "./GitConfig";
import type { KanbanConfig } from "./KanbanConfig";
import type { LaunchConfig } from "./LaunchConfig";
import type { LlmToolsConfig } from "./LlmToolsConfig";
import type { LoggingConfig } from "./LoggingConfig";
import type { McpConfig } from "./McpConfig";
import type { ModelServer } from "./ModelServer";
import type { NotificationsConfig } from "./NotificationsConfig";
import type { PathsConfig } from "./PathsConfig";
import type { QueueConfig } from "./QueueConfig";
import type { RelayConfig } from "./RelayConfig";
import type { RestApiConfig } from "./RestApiConfig";
import type { SessionsConfig } from "./SessionsConfig";
import type { TemplatesConfig } from "./TemplatesConfig";
import type { TmuxConfig } from "./TmuxConfig";
import type { UiConfig } from "./UiConfig";
import type { VersionCheckConfig } from "./VersionCheckConfig";

export type Config = { 
/**
 * List of projects operator can assign work to
 */
projects: Array<string>, agents: AgentsConfig, notifications: NotificationsConfig, queue: QueueConfig, paths: PathsConfig, ui: UiConfig, launch: LaunchConfig, templates: TemplatesConfig, api: ApiConfig, logging: LoggingConfig, tmux: TmuxConfig, 
/**
 * Session wrapper configuration (tmux, vscode, or cmux)
 */
sessions: SessionsConfig, llm_tools: LlmToolsConfig, rest_api: RestApiConfig, git: GitConfig, 
/**
 * Kanban provider configuration for syncing issues from Jira, Linear, etc.
 */
kanban: KanbanConfig, 
/**
 * Version check configuration for automatic update notifications
 */
version_check: VersionCheckConfig, 
/**
 * Agent delegator configurations for autonomous ticket launching
 */
delegators: Array<Delegator>, 
/**
 * User-declared model servers (ollama, lmstudio, any OpenAI-compat host).
 * Implicit builtin servers exist for each `llm_tool`'s vendor API and do not need declaration.
 */
model_servers: Array<ModelServer>, 
/**
 * Relay MCP injection configuration
 */
relay: RelayConfig, 
/**
 * Model Context Protocol (MCP) server configuration
 */
mcp: McpConfig, 
/**
 * Agent Client Protocol (ACP) agent configuration
 */
acp: AcpConfig, };
