// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentsConfiguration } from "./AgentsConfiguration";
import type { LaunchConfiguration } from "./LaunchConfiguration";
import type { QueueConfiguration } from "./QueueConfiguration";
import type { UiConfiguration } from "./UiConfiguration";

/**
 * The deliberately supported, integration-safe configuration surface.
 */
export type ConfigurationResponse = { agents: AgentsConfiguration, queue: QueueConfiguration, ui: UiConfiguration, launch: LaunchConfiguration, };
