// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to create a new model server
 */
export type CreateModelServerRequest = { 
/**
 * Unique name for this model server
 */
name: string, 
/**
 * Kind: "ollama", "openai-compat", "anthropic-api", "openai-api", "google-api", "lmstudio"
 */
kind: string, 
/**
 * Base URL of the inference endpoint
 */
base_url: string | null, 
/**
 * Name of an env var providing the API key
 */
api_key_env: string | null, 
/**
 * Additional environment variables
 */
extra_env: { [key in string]: string }, 
/**
 * Optional display name for UI
 */
display_name: string | null, };
