// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response after raising an alert.
 */
export type CreateAlertResponse = { 
/**
 * The created investigation ticket's id.
 */
id: string, 
/**
 * The investigation ticket filename written to the queue.
 */
filename: string, };
