// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DelegatorLaunchConfigDto } from "./DelegatorLaunchConfigDto";
import type { RemoteAgentRef } from "./RemoteAgentRef";

/**
 * Request to create a new delegator
 */
export type CreateDelegatorRequest = { 
/**
 * Unique name for the delegator
 */
name: string, 
/**
 * LLM tool name (must match a detected tool)
 */
llm_tool: string, 
/**
 * Model alias
 */
model: string, 
/**
 * Optional display name
 */
display_name: string | null, 
/**
 * Arbitrary model properties
 */
model_properties: { [key in string]: string }, 
/**
 * Name of a declared `ModelServer`. `None` means use the `llm_tool`'s implicit vendor default.
 */
model_server: string | null, 
/**
 * Optional launch configuration
 */
launch_config: DelegatorLaunchConfigDto | null, 
/**
 * Declarative reference to a remote, named agent (AGNT, `OpenAI`, ...). When
 * set, the delegator is export-only and cannot be launched locally.
 */
remote_agent: RemoteAgentRef | null, };
