// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DelegatorLaunchConfigDto } from "./DelegatorLaunchConfigDto";

/**
 * Request to create a delegator from a detected LLM tool
 *
 * Pre-populates delegator fields from the detected tool, requiring minimal input.
 * If `name` is omitted, auto-generates as `"{tool_name}-{model}"`.
 * If `model` is omitted, uses the tool's first model alias.
 */
export type CreateDelegatorFromToolRequest = { 
/**
 * Name of the detected tool (e.g., "claude", "codex", "gemini")
 */
tool_name: string, 
/**
 * Model alias to use (e.g., "opus"). If omitted, uses the tool's first model alias.
 */
model: string | null, 
/**
 * Custom delegator name. If omitted, auto-generates as `"{tool_name}-{model}"`.
 */
name: string | null, 
/**
 * Optional display name for UI
 */
display_name: string | null, 
/**
 * Optional launch configuration
 */
launch_config: DelegatorLaunchConfigDto | null, };
