// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response after creating a ticket.
 */
export type CreateTicketResponse = { 
/**
 * The created ticket's id (e.g. `FEAT-1234`).
 */
id: string, 
/**
 * The ticket filename written to the queue.
 */
filename: string, 
/**
 * The absolute path the ticket was written to.
 */
path: string, };
