// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to create a new ticket from a template.
 */
export type CreateTicketRequest = { 
/**
 * Template type key (feature, fix, spike, investigation, task).
 */
template: string, 
/**
 * Project the ticket targets (filled into the template's `project` value).
 */
project: string | null, 
/**
 * One-line summary (filled into the template's `summary` value).
 */
summary: string | null, 
/**
 * Additional Handlebars values for the template. Explicit `project`/
 * `summary` fields take precedence over the same keys here.
 */
values: { [key in string]?: string }, };
