// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scope } from "./Scope";

/**
 * Create a service access key for an integration.
 */
export type CreateAccessKeyRequest = { 
/**
 * Human-readable label identifying what holds this key.
 */
name: string, 
/**
 * Scopes to grant. Only what the integration needs.
 */
scopes: Array<Scope>, 
/**
 * Days until the key expires. Expiry is mandatory - there is no
 * non-expiring key.
 */
expires_in_days: bigint, };
