// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to raise an external alert as an investigation ticket.
 */
export type CreateAlertRequest = { 
/**
 * Where the alert came from (e.g. `pagerduty`, `sentry`).
 */
source: string, 
/**
 * The alert message / summary.
 */
message: string, 
/**
 * Severity label (e.g. `S1`, `S2`).
 */
severity: string, 
/**
 * Optional project the investigation targets.
 */
project: string | null, };
