// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateFieldRequest } from "./CreateFieldRequest";
import type { CreateStepRequest } from "./CreateStepRequest";

/**
 * Request to create a new issue type
 */
export type CreateIssueTypeRequest = { key: string, name: string, description: string, mode: string, glyph: string, color: string | null, project_required: boolean, fields: Array<CreateFieldRequest>, steps: Array<CreateStepRequest>, };
