// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessKeySummary } from "./AccessKeySummary";

/**
 * A newly created access key. **The secret appears here and nowhere else,
 * ever** — only its hash is stored, so it cannot be shown again.
 */
export type CreateAccessKeyResponse = { 
/**
 * Metadata for the created key.
 */
key: AccessKeySummary, 
/**
 * The key secret, returned exactly once. Store it now; it is unrecoverable.
 */
secret: string, };
