// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A freshly minted CSRF token for the current session.
 */
export type CsrfTokenResponse = { 
/**
 * Send as the CSRF header on cookie-authenticated mutations.
 */
csrf_token: string, };
