// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrincipalKind } from "./PrincipalKind";
import type { Scope } from "./Scope";

/**
 * The caller's current authenticated identity.
 */
export type CurrentSessionResponse = { 
/**
 * Account name - always `admin`, the single human account.
 */
subject: string, 
/**
 * Scopes this credential holds.
 */
scopes: Array<Scope>, 
/**
 * How the caller authenticated.
 */
principal_kind: PrincipalKind, 
/**
 * When this credential expires, if it does.
 */
expires_at?: string | null, };
