// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Per-provider custom configuration flags
 */
export type CustomFlags = { 
/**
 * Claude-specific configuration flags
 */
claude: { [key in string]: JsonValue }, 
/**
 * Gemini-specific configuration flags
 */
gemini: { [key in string]: JsonValue }, 
/**
 * Codex-specific configuration flags
 */
codex: { [key in string]: JsonValue }, };
