// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response with the current default LLM tool and model
 */
export type DefaultLlmResponse = { 
/**
 * Default tool name (empty string if not set)
 */
tool: string, 
/**
 * Default model alias (empty string if not set)
 */
model: string, };
