// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Launch configuration DTO for delegators
 */
export type DelegatorLaunchConfigDto = { 
/**
 * Run in YOLO mode
 */
yolo: boolean, 
/**
 * Permission mode override
 */
permission_mode: string | null, 
/**
 * Additional CLI flags
 */
flags: Array<string>, };
