// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DelegatorResponse } from "./DelegatorResponse";

/**
 * Response listing all delegators
 */
export type DelegatorsResponse = { 
/**
 * List of delegators
 */
delegators: Array<DelegatorResponse>, 
/**
 * Total count
 */
total: number, };
