// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DelegatorLaunchConfig } from "./DelegatorLaunchConfig";

/**
 * Agent delegator configuration for autonomous ticket launching
 *
 * A delegator is a named {tool, model} pairing with optional launch configuration
 * that can be used to launch agents for tickets.
 */
export type Delegator = { 
/**
 * Unique name for this delegator (e.g., "claude-opus-auto")
 */
name: string, 
/**
 * LLM tool name (must match a detected tool, e.g., "claude", "codex")
 */
llm_tool: string, 
/**
 * Model alias (e.g., "opus", "sonnet", "gpt-4o")
 */
model: string, 
/**
 * Optional display name for UI
 */
display_name: string | null, 
/**
 * Arbitrary model properties (e.g., reasoning_effort, sandbox)
 */
model_properties: { [key in string]?: string }, 
/**
 * Optional launch configuration
 */
launch_config: DelegatorLaunchConfig | null, };
