// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Launch configuration DTO for delegators
 *
 * Optional fields use tri-state semantics: `None` = inherit global config,
 * `Some(true/false)` = explicit override per-delegator.
 */
export type DelegatorLaunchConfigDto = { 
/**
 * Run in YOLO mode
 */
yolo: boolean, 
/**
 * Permission mode override
 */
permission_mode: string | null, 
/**
 * Additional CLI flags
 */
flags: Array<string>, 
/**
 * Override global `git.use_worktrees` (None = use global setting)
 */
use_worktrees: boolean | null, 
/**
 * Whether to create a git branch for the ticket (None = default behavior)
 */
create_branch: boolean | null, 
/**
 * Run in docker container (None = use global `launch.docker.enabled`)
 */
docker: boolean | null, 
/**
 * Prompt text to prepend before the generated step prompt
 */
prompt_prefix: string | null, 
/**
 * Prompt text to append after the generated step prompt
 */
prompt_suffix: string | null, };
