// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Launch configuration for a delegator
 *
 * Controls how the delegator launches agents. Optional fields use tri-state
 * semantics: `None` = inherit from global config, `Some(true/false)` = override.
 */
export type DelegatorLaunchConfig = { 
/**
 * Run in YOLO (auto-accept) mode
 */
yolo: boolean, 
/**
 * Permission mode override
 */
permission_mode: string | null, 
/**
 * Additional CLI flags
 */
flags: Array<string>, 
/**
 * Override global `git.use_worktrees` per-delegator (None = use global setting)
 */
use_worktrees: boolean | null, 
/**
 * Whether to create a git branch for the ticket (None = default behavior)
 */
create_branch: boolean | null, 
/**
 * Run in docker container (None = use global `launch.docker.enabled`)
 */
docker: boolean | null, 
/**
 * Prompt text to prepend before the generated step prompt
 */
prompt_prefix: string | null, 
/**
 * Prompt text to append after the generated step prompt
 */
prompt_suffix: string | null, 
/**
 * Override global relay auto-inject MCP setting per-delegator (None = use global setting)
 */
operator_relay: boolean | null, };
