// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DelegatorLaunchConfig } from "./DelegatorLaunchConfig";
import type { JsonValue } from "./serde_json/JsonValue";
import type { RemoteAgentRef } from "./RemoteAgentRef";

/**
 * Agent delegator configuration for autonomous ticket launching
 *
 * A delegator is a named {tool, model} pairing with optional launch configuration
 * that can be used to launch agents for tickets.
 */
export type Delegator = { 
/**
 * Unique name for this delegator (e.g., "claude-opus-auto")
 */
name: string, 
/**
 * LLM tool name (must match a detected tool, e.g., "claude", "codex")
 */
llm_tool: string, 
/**
 * Model alias (e.g., "opus", "sonnet", "gpt-4o")
 */
model: string, 
/**
 * Optional display name for UI
 */
display_name: string | null, 
/**
 * Arbitrary model properties (e.g., `reasoning_effort`, sandbox)
 */
model_properties: { [key in string]?: string }, 
/**
 * Optional launch configuration
 */
launch_config: DelegatorLaunchConfig | null, 
/**
 * Name of a declared `ModelServer` (from `Config.model_servers`).
 * `None` means use the `llm_tool`'s implicit vendor default
 * (claude → anthropic-api, codex → openai-api, gemini → google-api).
 */
model_server: string | null, 
/**
 * Declarative reference to a remote, named agent on another platform
 * (e.g. an AGNT agent or an `OpenAI` Assistant; see [`crate::config::AgentProfile`]).
 *
 * Export-only: Operator has no runtime client for those platforms, so a
 * delegator carrying this CANNOT be launched locally — resolution errors out
 * (see `delegator_resolution`). It is stored, listed, serialized into an
 * `AgentProfile`, and — for `platform == "agnt"` — surfaced in the
 * `--format agnt` workflow export as an `agnt-agent` node. `None` = ordinary,
 * locally launchable delegator.
 */
remote_agent: RemoteAgentRef | null, 
/**
 * Opaque AGNT-namespaced extension fields, preserved verbatim across an
 * `AgentProfile` round-trip so re-export is lossless (e.g. `memory`,
 * `assignedWorkflows`, `creditLimit`). Operator never interprets this.
 */
x_agnt: JsonValue | null, 
/**
 * Opaque OpenAI-namespaced extension fields, preserved verbatim across an
 * `AgentProfile` round-trip (e.g. `instructions`, `tools`, `tool_resources`,
 * `metadata`, thread refs). Mirror of [`Self::x_agnt`]; never interpreted.
 */
x_openai: JsonValue | null, 
/**
 * Opaque carry for `AgentProfile` shared-core fields Operator cannot model
 * first-class (`system_prompt` / `skills` / `mcp_servers` / `tools`) so an
 * import→export round-trip is lossless. Distinct from `x_agnt`: these are
 * shared-core fields, not AGNT-specific, so folding them into `x_agnt` would
 * corrupt that namespace. Operator never interprets this.
 */
unmapped_core: JsonValue | null, };
