// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StepPermissions } from "./StepPermissions";

/**
 * Configuration for delegator steps that run with a specific model+flavor
 */
export type DelegatorStepConfig = { 
/**
 * Named delegator reference (from config.delegators)
 */
delegator: string, 
/**
 * Additional prompt flavor text prepended to the step prompt
 */
prompt_flavor?: string | null, 
/**
 * Tools allowed
 */
allowed_tools: Array<string>, 
/**
 * Permissions
 */
permissions?: StepPermissions | null, };
