// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DelegatorLaunchConfigDto } from "./DelegatorLaunchConfigDto";

/**
 * Response for a single delegator
 */
export type DelegatorResponse = { 
/**
 * Unique name
 */
name: string, 
/**
 * LLM tool name (e.g., "claude")
 */
llm_tool: string, 
/**
 * Model alias (e.g., "opus")
 */
model: string, 
/**
 * Optional display name
 */
display_name: string | null, 
/**
 * Arbitrary model properties
 */
model_properties: { [key in string]?: string }, 
/**
 * Optional launch configuration
 */
launch_config: DelegatorLaunchConfigDto | null, };
