// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCapabilities } from "./ToolCapabilities";

/**
 * A detected CLI tool (e.g., claude binary)
 */
export type DetectedTool = { 
/**
 * Tool name (e.g., "claude")
 */
name: string, 
/**
 * Path to the binary
 */
path: string, 
/**
 * Version string
 */
version: string, 
/**
 * Minimum required version for Operator compatibility
 */
min_version: string | null, 
/**
 * Whether the installed version meets the minimum requirement
 */
version_ok: boolean, 
/**
 * Available model aliases (e.g., ["opus", "sonnet", "haiku"])
 */
model_aliases: Array<string>, 
/**
 * Command template with {{model}}, {{session_id}}, {{prompt_file}} placeholders
 */
command_template: string, 
/**
 * Tool capabilities
 */
capabilities: ToolCapabilities, 
/**
 * CLI flags for YOLO (auto-accept) mode
 */
yolo_flags: Array<string>, };
