// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCapabilitiesSummary } from "./ToolCapabilitiesSummary";

/**
 * Public view of a detected agent tool without local paths or command flags.
 */
export type DetectedToolSummary = { name: string, version: string, min_version: string | null, version_ok: boolean, model_aliases: Array<string>, capabilities: ToolCapabilitiesSummary, health_ok: boolean, };
