// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scope } from "./Scope";

/**
 * A client authorized through the device flow.
 */
export type DeviceSummary = { 
/**
 * Stable identifier, safe to display and to reference for revocation.
 */
id: string, 
/**
 * Client identifier supplied at authorization (e.g. `vscode`).
 */
client_id: string, 
/**
 * Scopes granted to this device.
 */
scopes: Array<Scope>, 
/**
 * When the device was approved.
 */
created_at: string, 
/**
 * When the device's refresh credential reaches its absolute deadline.
 */
expires_at: string, 
/**
 * When the device last refreshed.
 */
last_used_at?: string | null, 
/**
 * When the device was revoked; `None` while active.
 */
revoked_at?: string | null, };
