// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Approve a pending device authorization from an authenticated session.
 */
export type DeviceApprovalRequest = { 
/**
 * The user code shown on the requesting device.
 */
user_code: string, };
