// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scope } from "./Scope";

/**
 * Result of approving a device.
 */
export type DeviceApprovalResponse = { 
/**
 * Client that requested authorization, echoed so the approver can confirm.
 */
client_id: string, 
/**
 * Scopes granted.
 */
scopes: Array<Scope>, 
/**
 * Whether approval completed.
 */
approved: boolean, };
