// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * RFC 8628 device authorization response.
 */
export type DeviceAuthorizationResponse = { 
/**
 * Opaque code the client polls the token endpoint with. Never logged.
 */
device_code: string, 
/**
 * Short code the human types into the approval screen.
 */
user_code: string, 
/**
 * Where the human goes to approve.
 */
verification_uri: string, 
/**
 * `verification_uri` with the user code pre-filled.
 */
verification_uri_complete: string, 
/**
 * Seconds until the device code expires.
 */
expires_in: bigint, 
/**
 * Minimum seconds the client must wait between polls.
 */
interval: bigint, };
