// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scope } from "./Scope";

/**
 * Begin device authorization for a public client that cannot hold a secret.
 */
export type DeviceAuthorizationRequest = { 
/**
 * Identifier for the requesting client (e.g. `vscode`).
 */
client_id: string, 
/**
 * Scopes requested. IDE clients request all four, because such a client
 * acts as the human admin.
 */
scopes: Array<Scope>, };
