// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Directory-level permissions
 */
export type DirectoryPermissions = { 
/**
 * Additional directories to allow access to (glob patterns)
 */
allow: Array<string>, 
/**
 * Directories to deny access to (glob patterns)
 */
deny: Array<string>, };
