// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitRepoInfo } from "./GitRepoInfo";

/**
 * A discovered project with git and LLM tool information
 */
export type DiscoveredProject = { 
/**
 * Project name (directory name)
 */
name: string, 
/**
 * Absolute path to project root
 */
path: string, 
/**
 * LLM tools available (from marker files)
 */
llm_tools: Array<string>, 
/**
 * Git repository info (if .git exists)
 */
git_info: GitRepoInfo | null, };
