// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Docker execution configuration for running agents in containers
 */
export type DockerConfig = { 
/**
 * Whether docker mode option is available in launch dialog
 */
enabled: boolean, 
/**
 * Docker image to use (required if enabled)
 */
image: string, 
/**
 * Additional docker run arguments
 */
extra_args: Array<string>, 
/**
 * Container mount path for the project (default: /workspace)
 */
mount_path: string, 
/**
 * Environment variables to pass through to the container
 */
env_vars: Array<string>, };
