// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { ProcessStatus } from "./ProcessStatus";
import type { RunReason } from "./RunReason";

/**
 * An individual execution process within an attempt
 *
 * Each attempt can spawn multiple processes: setup script, coding agent, cleanup.
 * This maps to vibe-kanban's ExecutionProcess concept.
 */
export type ExecutionProcess = { 
/**
 * Unique identifier
 */
id: string, 
/**
 * Parent attempt ID
 */
attempt_id: string, 
/**
 * Why this process was spawned
 */
run_reason: RunReason, 
/**
 * Action chain configuration (for sequential execution)
 */
executor_action: JsonValue | null, 
/**
 * Git HEAD before execution started
 */
before_head_commit: string | null, 
/**
 * Git HEAD after execution completed
 */
after_head_commit: string | null, 
/**
 * Current process status
 */
status: ProcessStatus, 
/**
 * Process exit code (if completed)
 */
exit_code: number | null, 
/**
 * Whether this process is excluded from the timeline (e.g., after retry)
 */
dropped: boolean, started_at: string, completed_at: string | null, };
