// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Execution target transport category.
 */
export type ExecutionTargetKind = "local" | "docker" | "coder" | "ssh";
