// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionTargetKind } from "./ExecutionTargetKind";

/**
 * A named execution target without connection or credential plumbing.
 */
export type ExecutionTargetSummary = { name: string, display_name: string | null, kind: ExecutionTargetKind, available: boolean, };
