// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Execution mode for an issuetype
 */
export type ExecutionMode = "autonomous" | "paired";
