// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionTargetSummary } from "./ExecutionTargetSummary";

export type ExecutionTargetsResponse = { targets: Array<ExecutionTargetSummary>, total: number, };
