// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of an issue type from an external kanban provider (Jira, Linear)
 */
export type ExternalIssueTypeSummary = { 
/**
 * Provider-specific unique identifier
 */
id: string, 
/**
 * Issue type name (e.g., "Bug", "Story", "Task")
 */
name: string, 
/**
 * Description of the issue type
 */
description: string | null, 
/**
 * Icon/avatar URL from the provider
 */
icon_url: string | null, };
