// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An external MCP server to inject into spawned agent sessions.
 *
 * Values in `command`, `args`, and `env` support `${VAR}` interpolation,
 * expanded at spawn time from the operator process environment.
 *
 * When `discover_from` is set, operator reads an MCP server spec from that
 * JSON sidecar file at spawn time. The sidecar must contain a top-level
 * `mcpServer` object with `command`, `args`, and `env` fields. If the file
 * is absent and `command` is empty, the server is silently skipped.
 */
export type ExternalMcpServer = { 
/**
 * Server name used as the key in the `mcpServers` JSON object
 * (e.g., "kanbots"). Must be unique across all external servers.
 */
name: string, 
/**
 * Command to execute. Supports `${VAR}` interpolation.
 */
command: string, 
/**
 * Command arguments. Each element supports `${VAR}` interpolation.
 */
args: Array<string>, 
/**
 * Environment variables passed to the MCP server process.
 * Values support `${VAR}` interpolation.
 */
env: { [key in string]: string }, 
/**
 * Whether this server is enabled. Allows disabling without removing config.
 */
enabled: boolean, 
/**
 * Path to a JSON sidecar discovery file. Relative paths resolve from
 * the project directory. The sidecar must contain `{ "mcpServer": { ... } }`.
 * When the file exists, its `mcpServer` spec is used verbatim (overriding
 * `command`/`args`/`env`). When absent and `command` is empty, the server
 * is silently skipped.
 */
discover_from: string | null, };
