// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for a field
 */
export type FieldResponse = { name: string, description: string, field_type: string, required: boolean, default: string | null, options: Array<string>, placeholder: string | null, max_length: number | null, user_editable: boolean, };
