// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Types of fields supported in template schemas
 */
export type FieldType = "string" | "enum" | "bool" | "date" | "text" | "integer";
