// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoGenStrategy } from "./AutoGenStrategy";
import type { FieldType } from "./FieldType";

/**
 * Schema definition for a single field in a template
 */
export type FieldSchema = { 
/**
 * Field identifier (matches handlebar variable name)
 */
name: string, 
/**
 * Help text for the field
 */
description: string, 
/**
 * Type of the field
 */
type: FieldType, 
/**
 * Whether this field must be filled
 */
required: boolean, 
/**
 * Default value if any
 */
default?: string | null, 
/**
 * Auto-generation strategy for this field
 */
auto?: AutoGenStrategy | null, 
/**
 * Options for enum fields
 */
options: Array<string>, 
/**
 * Placeholder text shown in template
 */
placeholder?: string | null, 
/**
 * Maximum length for string fields
 */
max_length?: number | null, 
/**
 * Display order in form (lower = first)
 */
display_order?: number | null, 
/**
 * Whether the user can edit this field (false for auto-generated)
 */
user_editable: boolean, };
