// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ForgejoConfig = { enabled: boolean, token_env: string, 
/**
 * HTTPS host or base URL; defaults to codeberg.org.
 */
host: string | null, wip_prefix: string, };
