// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request recovery instructions without revealing whether an account exists.
 */
export type ForgotPasswordRequest = { username: string, };
