// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Generic recovery guidance for a self-hosted Operator deployment.
 */
export type ForgotPasswordResponse = { message: string, };
