// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supplied HTTPS credential, bound to a repository; contains no secret value.
 */
export type GitCredentialConfig = { repository_url: string, username: string, token_env: string, };
