// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitHubConfig } from "./GitHubConfig";
import type { GitLabConfig } from "./GitLabConfig";
import type { GitProviderConfig } from "./GitProviderConfig";

/**
 * Git provider configuration for PR/MR operations
 */
export type GitConfig = { 
/**
 * Active provider (auto-detected from remote URL if not specified)
 */
provider: GitProviderConfig | null, 
/**
 * GitHub-specific configuration
 */
github: GitHubConfig, 
/**
 * GitLab-specific configuration (planned)
 */
gitlab: GitLabConfig, 
/**
 * Branch naming format (e.g., "{type}/{ticket_id}-{slug}")
 */
branch_format: string, };
