// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForgejoConfig } from "./ForgejoConfig";
import type { GitHubConfig } from "./GitHubConfig";
import type { GitIdentityConfig } from "./GitIdentityConfig";
import type { GitLabConfig } from "./GitLabConfig";
import type { GitProviderConfig } from "./GitProviderConfig";
import type { GiteaConfig } from "./GiteaConfig";

/**
 * Git provider configuration for PR/MR operations
 */
export type GitConfig = { 
/**
 * Default commit identity for delegated work.
 */
identity?: GitIdentityConfig | null, gitea: GiteaConfig, forgejo: ForgejoConfig, 
/**
 * Active provider (auto-detected from remote URL if not specified)
 */
provider: GitProviderConfig | null, 
/**
 * GitHub-specific configuration
 */
github: GitHubConfig, 
/**
 * GitLab-specific configuration
 */
gitlab: GitLabConfig, 
/**
 * Branch naming format (e.g., "{type}/{ticket_id}-{slug}")
 */
branch_format: string, 
/**
 * Whether to use git worktrees for per-ticket isolation (default: false)
 * When false, tickets work directly in the project directory with branches
 */
use_worktrees: boolean, };
