// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitConfigEntry } from "./GitConfigEntry";
import type { GitCredentialConfig } from "./GitCredentialConfig";
import type { GitIdentityConfig } from "./GitIdentityConfig";

/**
 * Git settings owned by a named delegator.
 */
export type GitExecutionConfig = { identity: GitIdentityConfig | null, credentials: GitCredentialConfig | null, settings: Array<GitConfigEntry>, };
