// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ephemeral GitHub Projects credentials supplied by a client during onboarding.
 *
 * The token must have `project` (or `read:project`) scope. A repo-only token
 * (the kind used for `GITHUB_TOKEN` and operator's git provider) will be
 * rejected at validation time with a friendly "lacks `project` scope" error.
 */
export type GithubCredentials = { 
/**
 * GitHub PAT, fine-grained PAT, or app installation token
 */
token: string, };
