// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GitHub-specific configuration
 */
export type GitHubConfig = { 
/**
 * Whether GitHub integration is enabled
 */
enabled: boolean, 
/**
 * Environment variable containing the GitHub token (default: GITHUB_TOKEN)
 */
token_env: string, };
