// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectSyncConfig } from "./ProjectSyncConfig";

/**
 * GitHub Projects v2 (kanban) provider configuration
 *
 * The owner login (user or org) is specified as the `HashMap` key in
 * `KanbanConfig.github`. Project keys inside `projects` are `GraphQL` node
 * IDs (e.g., `PVT_kwDOABcdefg`) — opaque, stable identifiers used directly
 * by every GitHub Projects v2 mutation without needing a lookup.
 *
 * **Distinct from `GitHubConfig`** (the git provider used for PR/branch
 * operations). They live in different parts of the config tree, use
 * different env vars (`OPERATOR_GITHUB_TOKEN` vs `GITHUB_TOKEN`), and
 * require different OAuth scopes (`project` vs `repo`). See
 * `docs/getting-started/kanban/github.md` for the full rationale.
 */
export type GithubProjectsConfig = { 
/**
 * Whether this provider is enabled
 */
enabled: boolean, 
/**
 * Environment variable name containing the GitHub token (default:
 * `OPERATOR_GITHUB_TOKEN`). The token must have `project` (or
 * `read:project`) scope, NOT just `repo` — see the disambiguation
 * guide in the kanban github docs.
 */
api_key_env: string, 
/**
 * Per-project sync configuration. Keys are `GraphQL` project node IDs.
 */
projects: { [key in string]: ProjectSyncConfig }, };
