// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A GitHub Project v2 surfaced during onboarding for project picker UIs.
 */
export type GithubProjectInfoDto = { 
/**
 * `GraphQL` node ID (e.g., `PVT_kwDOABcdefg`) — used as the project key
 */
node_id: string, 
/**
 * Project number (e.g., 42) within the owner
 */
number: number, 
/**
 * Human-readable project title
 */
title: string, 
/**
 * Owner login (org or user name)
 */
owner_login: string, 
/**
 * "Organization" or "User"
 */
owner_kind: string, };
