// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GithubProjectInfoDto } from "./GithubProjectInfoDto";

/**
 * GitHub-specific validation details (returned on success).
 */
export type GithubValidationDetailsDto = { 
/**
 * Authenticated user's login (e.g., "octocat")
 */
user_login: string, 
/**
 * Authenticated user's numeric `databaseId` as a string (used as `sync_user_id`)
 */
user_id: string, 
/**
 * All Projects v2 visible to the token (across viewer + organizations)
 */
projects: Array<GithubProjectInfoDto>, 
/**
 * The env var name the validated token came from. Used by clients to
 * display "Connected via `OPERATOR_GITHUB_TOKEN`" so users can rotate the
 * right token. See Token Disambiguation in the kanban github docs.
 */
resolved_env_var: string, };
