// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GitHub Projects session env body — includes the actual secret to set in env.
 */
export type GithubSessionEnv = { token: string, api_key_env: string, };
