// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GitHub repository info parsed from remote URL
 */
export type GitHubRepoInfo = { 
/**
 * Repository owner (user or organization)
 */
owner: string, 
/**
 * Repository name
 */
repo_name: string, };
