// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Commit identity template for delegated work.
 */
export type GitIdentityConfig = { name: string, email: string, };
