// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GitLab-specific configuration (planned)
 */
export type GitLabConfig = { 
/**
 * Whether GitLab integration is enabled
 */
enabled: boolean, 
/**
 * Environment variable containing the GitLab token (default: GITLAB_TOKEN)
 */
token_env: string, 
/**
 * GitLab host (default: gitlab.com, can be self-hosted)
 */
host: string | null, };
