// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Git provider selection
 */
export type GitProviderConfig = "github" | "gitlab" | "bitbucket" | "azuredevops";
