// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepoInfo } from "./RepoInfo";

/**
 * Git repository information
 */
export type GitRepoInfo = { 
/**
 * Remote origin URL
 */
remote_url: string | null, 
/**
 * Parsed GitHub info (if GitHub remote)
 */
github_info: RepoInfo | null, 
/**
 * Default branch name
 */
default_branch: string, 
/**
 * Whether repo has uncommitted changes
 */
is_dirty: boolean, };
