// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Health check response
 */
export type HealthResponse = { status: string, version: string, };
