// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SupportStatus } from "./SupportStatus";

/**
 * One advertised integration: its vertical, identity, docs link, and support
 * status.
 */
export type IntegrationCatalogEntryDto = { 
/**
 * Vertical slug (e.g. "kanban", "model", "git", "session", "editor").
 */
vertical: string, 
/**
 * Human label for the vertical (e.g. "Kanban Provider").
 */
vertical_label: string, 
/**
 * Stable entry slug within the vertical (e.g. "jira", "anthropic-api").
 */
slug: string, 
/**
 * Display label for the entry (e.g. "Jira", "Anthropic").
 */
label: string, 
/**
 * Absolute docs URL, or `null` if undocumented.
 */
docs_url: string | null, 
/**
 * Whether this entry carries a curated README badge.
 */
readme_badge: boolean, 
/**
 * Official support / maturity status.
 */
status: SupportStatus, };
