// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionMode } from "./ExecutionMode";
import type { FieldSchema } from "./FieldSchema";
import type { IssueTypeSource } from "./IssueTypeSource";
import type { StepSchema } from "./StepSchema";

/**
 * An issue type definition (dynamic version of `TemplateSchema`)
 */
export type IssueType = { 
/**
 * Unique issuetype key (e.g., FEAT, FIX, STORY, BUG)
 */
key: string, 
/**
 * Display name of the issue type
 */
name: string, 
/**
 * Brief description of when to use this issue type
 */
description: string, 
/**
 * Whether this issue type runs autonomously or requires human pairing
 */
mode: ExecutionMode, 
/**
 * Glyph character displayed in UI for this issue type
 */
glyph: string, 
/**
 * Optional color for glyph display in TUI
 */
color?: string | null, 
/**
 * Whether a project must be specified for this issue type
 */
project_required: boolean, 
/**
 * Field definitions for this issue type
 */
fields: Array<FieldSchema>, 
/**
 * Lifecycle steps for completing this ticket type
 */
steps: Array<StepSchema>, 
/**
 * Prompt for generating this issue type's operator agent via `claude -p`
 */
agent_prompt?: string | null, 
/**
 * Default delegator name for this issuetype (overridden by step.agent)
 */
agent?: string | null, 
/**
 * Source of this issue type (builtin, user, import)
 */
source: IssueTypeSource, 
/**
 * Original external ID (for imported types)
 */
external_id?: string | null, };
