// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldResponse } from "./FieldResponse";
import type { StepResponse } from "./StepResponse";

/**
 * Response for a single issue type
 */
export type IssueTypeResponse = { key: string, name: string, description: string, mode: string, glyph: string, color: string | null, project_required: boolean, source: string, fields: Array<FieldResponse>, steps: Array<StepResponse>, };
