// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Source of an issue type definition
 */
export type IssueTypeSource = "builtin" | "user" | { "import": { 
/**
 * Provider name (e.g., "jira", "linear")
 */
provider: string, 
/**
 * Project/team identifier
 */
project: string, } };
