// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary response for listing issue types
 */
export type IssueTypeSummary = { key: string, name: string, description: string, mode: string, glyph: string, source: string, step_count: number, };
