// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a pipeline's iterated items come from. The variant determines *when*
 * the list resolves: export-time (a literal array → static fan-out width in
 * the compiled graph) vs runtime (an identifier → symbolic width).
 */
export type ItemSource = { "type": "projects" } | { "type": "from_step", 
/**
 * Name of the prior step whose (array) output is iterated.
 */
step: string, } | { "type": "glob", 
/**
 * Glob pattern, relative to the project root.
 */
pattern: string, } | { "type": "static", 
/**
 * The items to iterate.
 */
items: Array<string>, } | { "type": "field", 
/**
 * Name of the ticket field to read.
 */
name: string, };
