// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Jira-specific validation details (returned on success).
 */
export type JiraValidationDetailsDto = { 
/**
 * Atlassian accountId (used as `sync_user_id`)
 */
account_id: string, 
/**
 * User display name
 */
display_name: string, };
