// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ephemeral Jira credentials supplied by a client during onboarding.
 *
 * These are never persisted to disk by the onboarding endpoints that take
 * this struct — the actual secret stays in the env var named in
 * `api_key_env` once set via `/api/v1/kanban/session-env`.
 */
export type JiraCredentials = { 
/**
 * Jira Cloud domain (e.g., "acme.atlassian.net")
 */
domain: string, 
/**
 * Atlassian account email for Basic Auth
 */
email: string, 
/**
 * API token / personal access token
 */
api_token: string, };
