// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JiraDescription } from "./JiraDescription";
import type { JiraIssueTypeRef } from "./JiraIssueTypeRef";
import type { JiraPriority } from "./JiraPriority";
import type { JiraStatusRef } from "./JiraStatusRef";
import type { JiraUser } from "./JiraUser";

/**
 * Fields of a Jira issue
 */
export type JiraIssueFields = { 
/**
 * Issue summary/title
 */
summary: string, 
/**
 * Issue description in ADF format
 */
description: JiraDescription | null, 
/**
 * Issue type (Bug, Story, Task, etc.)
 */
issuetype: JiraIssueTypeRef, 
/**
 * Current workflow status
 */
status: JiraStatusRef, 
/**
 * Assigned user (if any)
 */
assignee: JiraUser | null, 
/**
 * Issue priority (if set)
 */
priority: JiraPriority | null, };
