// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Jira session env body — includes the actual secret to set in env.
 */
export type JiraSessionEnv = { domain: string, email: string, api_token: string, api_key_env: string, };
