// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectSyncConfig } from "./ProjectSyncConfig";

/**
 * Jira Cloud provider configuration
 *
 * The domain is specified as the HashMap key in KanbanConfig.jira
 */
export type JiraConfig = { 
/**
 * Whether this provider is enabled
 */
enabled: boolean, 
/**
 * Environment variable name containing the API key (default: OPERATOR_JIRA_API_KEY)
 */
api_key_env: string, 
/**
 * Atlassian account email for authentication
 */
email: string, 
/**
 * Per-project sync configuration
 */
projects: { [key in string]?: ProjectSyncConfig }, };
