// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reference to an issue type
 */
export type JiraIssueTypeRef = { 
/**
 * Issue type name (e.g., "Bug", "Story", "Task")
 */
name: string, };
