// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JiraIssue } from "./JiraIssue";

/**
 * Search response from Jira JQL query
 * GET /rest/api/3/search?jql=...
 */
export type JiraSearchResponse = { 
/**
 * List of issues matching the JQL query
 */
issues: Array<JiraIssue>, };
