// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Issue priority level
 */
export type JiraPriority = { 
/**
 * Priority name (e.g., "Highest", "High", "Medium", "Low", "Lowest")
 */
name: string, };
