// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Workflow status in Jira
 */
export type JiraStatus = { 
/**
 * Status name (e.g., "To Do", "In Progress", "Done")
 */
name: string, };
