// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JiraAvatarUrls } from "./JiraAvatarUrls";

/**
 * Jira user information from assignable users API
 * GET /rest/api/3/user/assignable/search?project={key}
 */
export type JiraUser = { 
/**
 * Atlassian account ID (e.g., "5e3f7acd9876543210abcdef")
 */
accountId: string, 
/**
 * User's display name
 */
displayName: string, 
/**
 * User's email address (may be hidden by privacy settings)
 */
emailAddress: string | null, 
/**
 * Avatar URLs in various sizes
 */
avatarUrls: JiraAvatarUrls | null, };
