// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JiraStatus } from "./JiraStatus";

/**
 * Project status information from Jira
 * GET /rest/api/3/project/{key}/statuses
 */
export type JiraProjectStatus = { 
/**
 * List of statuses available for this issue type
 */
statuses: Array<JiraStatus>, };
