// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JiraIssueFields } from "./JiraIssueFields";

/**
 * A Jira issue from search results
 */
export type JiraIssue = { 
/**
 * Internal Jira issue ID
 */
id: string, 
/**
 * Issue key (e.g., "PROJ-123")
 */
key: string, 
/**
 * Issue fields containing summary, status, etc.
 */
fields: JiraIssueFields, };
