// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Avatar URLs for a Jira user
 */
export type JiraAvatarUrls = { 
/**
 * 48x48 pixel avatar URL
 */
"48x48": string | null, };
