// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Jira description in Atlassian Document Format (ADF)
 */
export type JiraDescription = { 
/**
 * ADF content nodes - parsed to extract plain text
 */
content: Array<JsonValue> | null, };
