// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JudgeConfig = { 
/**
 * Name of a declared or implicit model server (e.g. "anthropic-api")
 */
model_server: string, 
/**
 * Full API model id (e.g. "claude-sonnet-5"), not a CLI alias like "sonnet"
 */
model: string, 
/**
 * Seconds before the judge is abandoned and the deterministic rule applies
 */
timeout_secs: bigint, };
