// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JudgeAttempt = { attempt_id: string, started_at: string, 
/**
 * Judge timeout copied at start, so a config edit can't strand the attempt
 */
timeout_secs: bigint, };
