// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TicketPriority } from "./TicketPriority";
import type { TicketStatus } from "./TicketStatus";

/**
 * A ticket card for the kanban board
 */
export type KanbanTicketCard = { 
/**
 * Ticket ID (e.g., "FEAT-7598")
 */
id: string, 
/**
 * Ticket summary/title
 */
summary: string, 
/**
 * Ticket type: FEAT, FIX, INV, SPIKE
 */
ticket_type: string, 
/**
 * Project name
 */
project: string, 
/**
 * Current status
 */
status: TicketStatus, 
/**
 * Current step name
 */
step: string, 
/**
 * Human-readable step name
 */
step_display_name: string | null, 
/**
 * Priority level
 */
priority: TicketPriority, 
/**
 * Timestamp for sorting (YYYYMMDD-HHMM format)
 */
timestamp: string, 
/**
 * Ticket markdown filename (joins with the tickets dir + status folder
 * for co-located clients; remote clients treat tickets as API-only)
 */
filename: string, };
