// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A ticket card for the kanban board
 */
export type KanbanTicketCard = { 
/**
 * Ticket ID (e.g., "FEAT-7598")
 */
id: string, 
/**
 * Ticket summary/title
 */
summary: string, 
/**
 * Ticket type: FEAT, FIX, INV, SPIKE
 */
ticket_type: string, 
/**
 * Project name
 */
project: string, 
/**
 * Current status: queued, running, awaiting, completed
 */
status: string, 
/**
 * Current step name
 */
step: string, 
/**
 * Human-readable step name
 */
step_display_name: string | null, 
/**
 * Priority: P0-critical, P1-high, P2-medium, P3-low
 */
priority: string, 
/**
 * Timestamp for sorting (YYYYMMDD-HHMM format)
 */
timestamp: string, };
