// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which kanban provider an onboarding request targets.
 */
export type KanbanProviderKind = "jira" | "linear" | "github";
