// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GithubProjectsConfig } from "./GithubProjectsConfig";
import type { JiraConfig } from "./JiraConfig";
import type { LinearConfig } from "./LinearConfig";

/**
 * Kanban provider configuration for syncing issues from external systems
 *
 * Providers are keyed by domain/workspace:
 * - Jira: keyed by domain (e.g., "foobar.atlassian.net")
 * - Linear: keyed by workspace slug (e.g., "myworkspace")
 * - GitHub Projects: keyed by owner login (e.g., "my-org")
 */
export type KanbanConfig = { 
/**
 * Jira Cloud instances keyed by domain (e.g., "foobar.atlassian.net")
 */
jira: { [key in string]: JiraConfig }, 
/**
 * Linear instances keyed by workspace slug
 */
linear: { [key in string]: LinearConfig }, 
/**
 * GitHub Projects v2 instances keyed by owner login (user or org)
 *
 * NOTE: This is the *kanban* GitHub integration (Projects v2), distinct
 * from `GitHubConfig` which is the *git provider* used for PRs and
 * branches. The two use different env vars and different scopes — see
 * `docs/getting-started/kanban/github.md` for the full disambiguation.
 */
github: { [key in string]: GithubProjectsConfig }, };
