// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KanbanTicketCard } from "./KanbanTicketCard";

/**
 * Kanban board response with tickets grouped by column
 */
export type KanbanBoardResponse = { 
/**
 * Tickets in queue (not yet started)
 */
queue: Array<KanbanTicketCard>, 
/**
 * Tickets currently being worked on
 */
running: Array<KanbanTicketCard>, 
/**
 * Tickets awaiting review or input
 */
awaiting: Array<KanbanTicketCard>, 
/**
 * Completed tickets
 */
done: Array<KanbanTicketCard>, 
/**
 * Total ticket count across all columns
 */
total_count: number, 
/**
 * ISO 8601 timestamp of last data refresh
 */
last_updated: string, };
