// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JiraConfig } from "./JiraConfig";
import type { LinearConfig } from "./LinearConfig";

/**
 * Kanban provider configuration for syncing issues from external systems
 *
 * Providers are keyed by domain/workspace:
 * - Jira: keyed by domain (e.g., "foobar.atlassian.net")
 * - Linear: keyed by workspace slug (e.g., "myworkspace")
 */
export type KanbanConfig = { 
/**
 * Jira Cloud instances keyed by domain (e.g., "foobar.atlassian.net")
 */
jira: { [key in string]?: JiraConfig }, 
/**
 * Linear instances keyed by workspace slug
 */
linear: { [key in string]?: LinearConfig }, };
