// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for kanban sync operations
 */
export type KanbanSyncResponse = { 
/**
 * Ticket IDs that were created
 */
created: Array<string>, 
/**
 * Ticket IDs that were skipped (already exist)
 */
skipped: Array<string>, 
/**
 * Error messages for failed syncs
 */
errors: Array<string>, 
/**
 * Total count of issues processed
 */
total_processed: number, };
