// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A project/team entry returned by `list_projects`.
 */
export type KanbanProjectInfo = { id: string, key: string, name: string, };
