// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explicit mapping from operator's strict todo/doing/done states to the
 * external board's column/status names.
 *
 * Drives bidirectional sync: issues are pulled from the `todo` column,
 * pushed to `doing` when a ticket is claimed, to `done` when completed, and
 * back to `todo` when requeued. Unset fields fall back per-transition
 * (`doing` → "In Progress", `done` → "Done"); requeue only pushes when
 * `todo` is explicitly mapped.
 */
export type KanbanStatusMapping = { 
/**
 * External column for operator "todo" (queued work; also the pull source)
 */
todo?: string | null, 
/**
 * External column for operator "doing" (claimed/launched tickets)
 */
doing?: string | null, 
/**
 * External column for operator "done" (completed tickets)
 */
done?: string | null, };
