// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A synced kanban issue type from the persisted catalog.
 */
export type KanbanIssueTypeResponse = { 
/**
 * Provider-specific ID (Jira type ID, Linear label ID)
 */
id: string, 
/**
 * Display name (e.g., "Bug", "Story", "Task")
 */
name: string, 
/**
 * Description from the provider
 */
description: string | null, 
/**
 * Icon/avatar URL from the provider
 */
icon_url: string | null, 
/**
 * Provider name ("jira", "linear", or "github")
 */
provider: string, 
/**
 * Project/team key
 */
project: string, 
/**
 * What this type represents in the provider ("issuetype" or "label")
 */
source_kind: string, 
/**
 * ISO 8601 timestamp of last sync
 */
synced_at: string, };
