// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which external kanban provider an onboarding request targets.
 * Deliberately one variant smaller than [`KanbanProviderType`]
 *
 * [`KanbanProviderType`]: crate::api::providers::kanban::KanbanProviderType
 */
export type KanbanProviderKind = "jira" | "linear" | "github" | "openspec";
