// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One supported kanban provider, as advertised by
 * `GET /api/v1/kanban/providers`.
 *
 * This is the single source of truth (derived from
 * `KanbanProviderType::ALL`) that the web `/#/kanban` list view and the VS
 * Code onboarding picker both render against, so the available options can't
 * drift between surfaces.
 */
export type KanbanProviderCatalogEntry = { 
/**
 * Stable lowercase slug ("jira" | "linear" | "github").
 */
slug: string, 
/**
 * Human-readable name (e.g. "Jira Cloud", "GitHub Projects").
 */
display_name: string, 
/**
 * One-line connect description shown next to the provider.
 */
description: string, 
/**
 * Credential/token page opened when the user chooses to configure it.
 */
setup_url: string, 
/**
 * VS Code codicon hint (rendered as `$(icon)` in the picker).
 */
icon: string, 
/**
 * Whether at least one instance of this provider is already configured.
 */
configured: boolean, };
