// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from launching a ticket
 */
export type LaunchTicketResponse = { 
/**
 * Agent ID assigned to this launch
 */
agent_id: string, 
/**
 * Ticket ID that was launched
 */
ticket_id: string, 
/**
 * Working directory (worktree if created, else project path)
 */
working_directory: string, 
/**
 * Command to execute in terminal
 */
command: string, 
/**
 * Terminal name to use
 */
terminal_name: string, 
/**
 * Session UUID for the LLM tool
 */
session_id: string, 
/**
 * Whether a worktree was created
 */
worktree_created: boolean, 
/**
 * Branch name (if worktree was created)
 */
branch: string | null, };
