// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DockerConfig } from "./DockerConfig";
import type { YoloConfig } from "./YoloConfig";

export type LaunchConfig = { confirm_autonomous: boolean, confirm_paired: boolean, launch_delay_ms: bigint, 
/**
 * Docker execution configuration
 */
docker: DockerConfig, 
/**
 * YOLO (auto-accept) mode configuration
 */
yolo: YoloConfig, };
