// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to launch a ticket
 */
export type LaunchTicketRequest = { 
/**
 * Named delegator to use (takes precedence over provider/model)
 */
delegator: string | null, 
/**
 * LLM provider to use (e.g., "claude") — legacy fallback when no delegator
 */
provider: string | null, 
/**
 * Model to use (e.g., "sonnet", "opus") — legacy fallback when no delegator
 */
model: string | null, 
/**
 * Ad-hoc model server to target (e.g. "ollama-local") — legacy fallback when
 * no delegator. Injects the server's base URL / API key env at spawn.
 */
model_server: string | null, 
/**
 * Run in YOLO mode (auto-accept all prompts)
 */
yolo_mode: boolean, 
/**
 * Session wrapper type: "vscode", "tmux", "cmux", "terminal"
 */
wrapper: string | null, 
/**
 * Feedback for relaunch (what went wrong on previous attempt)
 */
retry_reason: string | null, 
/**
 * Existing session ID to resume (for continuing from where it left off)
 */
resume_session_id: string | null, };
