// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to launch a ticket
 */
export type LaunchTicketRequest = { 
/**
 * LLM provider to use (e.g., "claude")
 */
provider: string | null, 
/**
 * Model to use (e.g., "sonnet", "opus")
 */
model: string | null, 
/**
 * Run in YOLO mode (auto-accept all prompts)
 */
yolo_mode: boolean, 
/**
 * Session wrapper type: "vscode", "tmux", "terminal"
 */
wrapper: string | null, };
