// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LicenseStatus } from "./LicenseStatus";
import type { LicenseTerms } from "./LicenseTerms";

export type LicenseResponse = { status: LicenseStatus, profile_id: string, premium: boolean, terms: LicenseTerms | null, purchase_url: string | null, };
