// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LicenseStatus = "missing" | "valid" | "expired" | "not_yet_valid" | "invalid";
