// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LicenseTerms = { version: number, iss: string, aud: string, sub: string, jti: string, profile_id: string, tier: string, iat: bigint, nbf: bigint, exp: bigint, };
