// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ephemeral Linear credentials supplied by a client during onboarding.
 */
export type LinearCredentials = { 
/**
 * Linear API key (prefixed `lin_api_`)
 */
api_key: string, };
