// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Linear team exposed to onboarding clients for project selection.
 */
export type LinearTeamInfoDto = { id: string, key: string, name: string, };
