// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinearTeamInfoDto } from "./LinearTeamInfoDto";

/**
 * Linear-specific validation details (returned on success).
 */
export type LinearValidationDetailsDto = { 
/**
 * Linear viewer user ID (used as `sync_user_id`)
 */
user_id: string, user_name: string, org_name: string, teams: Array<LinearTeamInfoDto>, };
