// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectSyncConfig } from "./ProjectSyncConfig";

/**
 * Linear provider configuration
 *
 * The workspace slug is specified as the HashMap key in KanbanConfig.linear
 */
export type LinearConfig = { 
/**
 * Whether this provider is enabled
 */
enabled: boolean, 
/**
 * Environment variable name containing the API key (default: OPERATOR_LINEAR_API_KEY)
 */
api_key_env: string, 
/**
 * Per-team sync configuration
 */
projects: { [key in string]?: ProjectSyncConfig }, };
