// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GithubCredentials } from "./GithubCredentials";
import type { JiraCredentials } from "./JiraCredentials";
import type { KanbanProviderKind } from "./KanbanProviderKind";
import type { LinearCredentials } from "./LinearCredentials";
import type { OpenspecSourceDto } from "./OpenspecSourceDto";

/**
 * Request to list workflow statuses/columns for a specific project using
 * ephemeral creds (onboarding wizard — before any config is persisted).
 */
export type ListKanbanStatusesRequest = { provider: KanbanProviderKind, 
/**
 * Project/team key to list statuses for
 */
project_key: string, jira?: JiraCredentials | null, linear?: LinearCredentials | null, github?: GithubCredentials | null, openspec?: OpenspecSourceDto | null, };
