// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KanbanProjectInfo } from "./KanbanProjectInfo";

/**
 * Response wrapper for list-projects (wrapped for utoipa compatibility).
 */
export type ListKanbanProjectsResponse = { projects: Array<KanbanProjectInfo>, };
