// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GithubCredentials } from "./GithubCredentials";
import type { JiraCredentials } from "./JiraCredentials";
import type { KanbanProviderKind } from "./KanbanProviderKind";
import type { LinearCredentials } from "./LinearCredentials";

/**
 * Request to list projects/teams from a provider using ephemeral creds.
 */
export type ListKanbanProjectsRequest = { provider: KanbanProviderKind, jira?: JiraCredentials | null, linear?: LinearCredentials | null, github?: GithubCredentials | null, };
