// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Usage statistics for a specific model
 */
export type LlmModelUsage = { 
/**
 * Model name/alias
 */
model: string, 
/**
 * Number of tickets
 */
ticket_count: bigint, 
/**
 * Success count
 */
success_count: bigint, 
/**
 * Failure count
 */
failure_count: bigint, 
/**
 * Total time (seconds)
 */
total_time_secs: bigint, };
