// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A {tool, model} pair that can be selected when launching tickets.
 * Includes optional variant fields adopted from vibe-kanban's profile system.
 */
export type LlmProvider = { 
/**
 * CLI tool name (e.g., "claude", "codex", "gemini")
 */
tool: string, 
/**
 * Model alias or name (e.g., "opus", "sonnet", "gpt-4.1")
 */
model: string, 
/**
 * Optional display name for UI (e.g., "Claude Opus", "Codex High")
 */
display_name: string | null, 
/**
 * Additional CLI flags for this provider (e.g., ["--dangerously-skip-permissions"])
 */
flags: Array<string>, 
/**
 * Environment variables to set when launching
 */
env: { [key in string]?: string }, 
/**
 * Whether this provider requires approval gates
 */
approvals: boolean, 
/**
 * Whether to run in plan-only mode
 */
plan_only: boolean, 
/**
 * Reasoning effort level (Codex: "low", "medium", "high")
 */
reasoning_effort: string | null, 
/**
 * Sandbox mode (Codex: "danger-full-access", "workspace-write")
 */
sandbox: string | null, };
