// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetectedToolSummary } from "./DetectedToolSummary";

/**
 * Response listing detected LLM tools
 */
export type LlmToolsResponse = { 
/**
 * Detected CLI tools with model aliases and capabilities
 */
tools: Array<DetectedToolSummary>, 
/**
 * Total count
 */
total: number, };
