// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * LLM task metadata for delegate mode integration
 */
export type LlmTask = { 
/**
 * LLM task ID (e.g., Claude delegate mode task UUID)
 */
id: string | null, 
/**
 * LLM task status: "open" or "resolved"
 */
status: string | null, 
/**
 * List of task IDs that must resolve before this task
 */
blocked_by: Array<string>, };
