// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetectedTool } from "./DetectedTool";
import type { LlmProvider } from "./LlmProvider";
import type { SkillDirectoriesOverride } from "./SkillDirectoriesOverride";

/**
 * LLM CLI tools configuration
 */
export type LlmToolsConfig = { 
/**
 * Detected CLI tools (populated on first startup)
 */
detected: Array<DetectedTool>, 
/**
 * Available {tool, model} pairs for launching tickets
 * Built from detected tools + their model aliases
 */
providers: Array<LlmProvider>, 
/**
 * Whether detection has been completed
 */
detection_complete: boolean, 
/**
 * User's preferred default LLM tool (e.g., "claude")
 */
default_tool: string | null, 
/**
 * User's preferred default model alias (e.g., "opus")
 */
default_model: string | null, 
/**
 * Per-tool overrides for skill directories (keyed by `tool_name`)
 */
skill_directory_overrides: { [key in string]: SkillDirectoriesOverride }, };
