// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LlmModelUsage } from "./LlmModelUsage";

/**
 * Usage statistics for a specific LLM tool
 */
export type LlmToolUsage = { 
/**
 * Tool name (e.g., "claude", "gemini")
 */
tool: string, 
/**
 * Total number of tickets processed
 */
ticket_count: bigint, 
/**
 * Number of successful completions
 */
success_count: bigint, 
/**
 * Number of failures/abandonments
 */
failure_count: bigint, 
/**
 * Total time spent (in seconds)
 */
total_time_secs: bigint, 
/**
 * Last used timestamp
 */
last_used: string, 
/**
 * Per-model breakdown
 */
model_usage: { [key in string]?: LlmModelUsage }, };
