// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Logging configuration
 */
export type LoggingConfig = { 
/**
 * Log level filter (trace, debug, info, warn, error)
 */
level: string, 
/**
 * Whether to log to file in TUI mode (false = stderr for debugging)
 */
to_file: boolean, };
