// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Password login, exchanged for an opaque server-side session cookie.
 */
export type LoginRequest = { 
/**
 * The account name. Required even while Operator supports one human account.
 */
username: string, 
/**
 * The admin password. Never persisted in plaintext or logged.
 */
password: string, };
