// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scope } from "./Scope";

/**
 * Successful login. The session itself rides in a `Set-Cookie` header, not in
 * this body — a body-borne session identifier would be readable by script.
 */
export type LoginResponse = { 
/**
 * Scopes the session holds.
 */
scopes: Array<Scope>, 
/**
 * When the session expires.
 */
expires_at: string, 
/**
 * CSRF token to send on subsequent cookie-authenticated mutations.
 */
csrf_token: string, };
