// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of destroying the current session server-side.
 */
export type LogoutResponse = { 
/**
 * Always true; present so the response has a stable, non-empty shape.
 */
ended: boolean, };
