// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatrixedOutputFormat } from "./MatrixedOutputFormat";

/**
 * Configuration for matrixed work output steps (N x M delegators x prompts)
 */
export type MatrixedConfig = { 
/**
 * Named delegator references (N), minimum 2
 */
delegators: Array<string>, 
/**
 * Prompt variations (M) — Handlebars templates, minimum 2
 */
prompt_variations: Array<string>, 
/**
 * How to organize/present the N x M output
 */
output_format: MatrixedOutputFormat, 
/**
 * Optional aggregation prompt (receives the full matrix of results)
 */
aggregation_prompt?: string | null, };
