// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output format for matrixed steps
 */
export type MatrixedOutputFormat = "directory" | "structured";
