// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalMcpServer } from "./ExternalMcpServer";

/**
 * Model Context Protocol (MCP) server configuration
 */
export type McpConfig = { 
/**
 * Whether to mount MCP HTTP/SSE endpoints on the REST API server.
 * Toggling requires an API restart (no hot-swap of the axum router).
 */
http_enabled: boolean, 
/**
 * Whether the descriptor endpoint advertises the `operator mcp` stdio
 * command. Set to false on multi-tenant/remote deployments where clients
 * shouldn't spawn local subprocesses.
 */
stdio_advertised: boolean, 
/**
 * Whether to expose ticket-mutating tools (claim, complete, return-to-queue,
 * create) over MCP. Defaults to `false` because any MCP client can call them.
 */
expose_ticket_write_tools: boolean, 
/**
 * External MCP servers to inject into spawned agent sessions.
 * Each entry produces a separate `--mcp-config` file alongside the
 * relay config when launching Claude Code agents.
 */
external_servers: Array<ExternalMcpServer>, };
