// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * MCP server descriptor for client discovery
 */
export type McpDescriptorResponse = { 
/**
 * Server name used in MCP registration (e.g. "operator")
 */
server_name: string, 
/**
 * Unique server identifier (e.g. "operator-mcp")
 */
server_id: string, 
/**
 * Server version from Cargo.toml
 */
version: string, 
/**
 * Full URL of the MCP SSE transport endpoint
 */
transport_url: string, 
/**
 * Human-readable label for the server
 */
label: string, 
/**
 * URL of the OpenAPI spec for reference
 */
openapi_url: string | null, };
