// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * MCP server permissions (server-level enable/disable only)
 */
export type McpServerPermissions = { 
/**
 * MCP servers to enable for this step
 */
enable: Array<string>, 
/**
 * MCP servers to disable for this step
 */
disable: Array<string>, };
