// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpToolRef } from "./McpToolRef";

/**
 * Configuration for MCP steps that require specific MCP tools
 */
export type McpStepConfig = { 
/**
 * MCP tools that MUST be available (step fails if missing)
 */
required_tools: Array<McpToolRef>, 
/**
 * MCP tools that SHOULD be available (warning if missing)
 */
optional_tools: Array<McpToolRef>, 
/**
 * Agent/delegator to use
 */
agent?: string | null, 
/**
 * Tools allowed (in addition to MCP tools)
 */
allowed_tools: Array<string>, };
