// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reference to a specific MCP server tool
 */
export type McpToolRef = { 
/**
 * MCP server name
 */
server: string, 
/**
 * Specific tool name (None = all tools from this server)
 */
tool?: string | null, };
