// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelServerResponse } from "./ModelServerResponse";

/**
 * Response listing all model servers (declared + implicit builtins)
 */
export type ModelServersResponse = { 
/**
 * List of model servers
 */
servers: Array<ModelServerResponse>, 
/**
 * Total count
 */
total: number, };
