// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A model-server kind from the shared catalog (single source of truth).
 */
export type ModelServerKindEntry = { 
/**
 * Stable slug stored as `ModelServer.kind` (e.g. "ollama")
 */
slug: string, 
/**
 * Human-friendly display name
 */
display_name: string, 
/**
 * One-line connect blurb
 */
description: string, 
/**
 * Help/credential setup page
 */
setup_url: string, 
/**
 * Codicon hint
 */
icon: string, 
/**
 * Whether this is an implicit vendor builtin (always present, not deletable)
 */
is_builtin: boolean, };
