// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A named host that serves models via an inference API.
 *
 * Model servers are orthogonal to `llm_tools`: a delegator pairs an agentic CLI
 * (`llm_tool`, e.g. claude/codex/gemini) with a model-serving endpoint
 * (`model_server`, e.g. ollama-local, openai-api, a custom vllm host).
 *
 * Implicit builtin servers (`anthropic-api`, `openai-api`, `google-api`) are
 * returned by [`implicit_model_server_for_tool`] and do not need to be declared
 * in config.
 */
export type ModelServer = { 
/**
 * Unique name (e.g., "ollama-local", "vllm-gpu1")
 */
name: string, 
/**
 * Kind: "ollama", "openai-compat", "anthropic-api", "openai-api", "google-api", "lmstudio"
 */
kind: string, 
/**
 * Base URL of the inference endpoint (e.g., `http://localhost:11434`).
 * `None` for implicit vendor servers means use the SDK default.
 */
base_url: string | null, 
/**
 * Name of an env var providing the API key (e.g., `OLLAMA_API_KEY`)
 */
api_key_env: string | null, 
/**
 * Additional environment variables set when spawning agents that use this server
 */
extra_env: { [key in string]?: string }, 
/**
 * Optional display name for UI
 */
display_name: string | null, };
