// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelEntry } from "./ModelEntry";

/**
 * Response listing the models a server offers, plus reachability.
 */
export type ModelServerModelsResponse = { 
/**
 * Server name probed
 */
server: string, 
/**
 * Whether the endpoint was reachable
 */
reachable: boolean, 
/**
 * Models offered (empty when unreachable)
 */
models: Array<ModelEntry>, 
/**
 * Error message when unreachable
 */
error: string | null, };
