// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single model offered by a server (from a live probe).
 */
export type ModelEntry = { 
/**
 * Model id passed to `--model`
 */
id: string, 
/**
 * Display name when the server provides one
 */
display_name: string | null, };
