// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for a single model server
 */
export type ModelServerResponse = { 
/**
 * Unique name (e.g., "ollama-local")
 */
name: string, 
/**
 * Kind: "ollama", "openai-compat", "anthropic-api", "openai-api", "google-api", "lmstudio"
 */
kind: string, 
/**
 * Base URL of the inference endpoint (e.g., `http://localhost:11434`)
 */
base_url: string | null, 
/**
 * Name of an env var providing the API key (e.g., `OLLAMA_API_KEY`)
 */
api_key_env: string | null, 
/**
 * Additional environment variables set when spawning agents that use this server
 */
extra_env: { [key in string]?: string }, 
/**
 * Optional display name for UI
 */
display_name: string | null, 
/**
 * Whether this is a user-declared server (true) or an implicit builtin (false)
 */
user_declared: boolean, };
