// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Execution phase for a multi-agent group
 */
export type MultiAgentPhase = "fan_out" | "voting" | "complete" | "failed";
