// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VotingMode } from "./VotingMode";
import type { VotingStrategy } from "./VotingStrategy";

/**
 * Configuration for multi-model delegation steps (fan-out + vote)
 */
export type MultiModelConfig = { 
/**
 * Named delegator references (from config.delegators), minimum 2
 */
delegators: Array<string>, 
/**
 * How to aggregate/select the final answer
 */
voting_strategy: VotingStrategy, 
/**
 * Whether to share all answers with all models in the voting round
 */
share_answers: boolean, 
/**
 * Prompt for the voting round (Handlebars, receives {{ answers }} array)
 */
voting_prompt?: string | null, 
/**
 * How the voting round executes
 */
voting_mode: VotingMode, };
