// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectionStrategy } from "./SelectionStrategy";

/**
 * Configuration for multi-prompt interrogation steps (N variations, select best)
 */
export type MultiPromptConfig = { 
/**
 * Prompt variations (Handlebars templates), minimum 2
 */
prompt_variations: Array<string>, 
/**
 * How to select the best result
 */
selection_strategy: SelectionStrategy, 
/**
 * Agent/delegator to use for all variations
 */
agent?: string | null, 
/**
 * Instruction for the judge that picks the best variation with
 * `model_choice` (Handlebars, rendered with the ticket context)
 */
selection_prompt?: string | null, };
