// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { MultiAgentPhase } from "./MultiAgentPhase";
import type { PendingSubAgent } from "./PendingSubAgent";

/**
 * Tracks a group of agents working on a single multi-agent step
 */
export type MultiAgentGroup = { 
/**
 * Unique group identifier
 */
group_id: string, 
/**
 * Ticket this group belongs to
 */
ticket_id: string, 
/**
 * Step name being executed
 */
step_name: string, 
/**
 * Step type (`multi_model`, `multi_prompt`, `matrixed`)
 */
step_type: string, 
/**
 * Agent IDs in this group (populated as sub-agents launch)
 */
agent_ids: Array<string>, 
/**
 * Current execution phase
 */
phase: MultiAgentPhase, 
/**
 * Collected outputs from completed sub-agents, keyed by `variant_key`
 * (delegator name for `multi_model`, index for `multi_prompt`,
 * `{delegator}:{prompt_idx}` for `matrixed`).
 */
individual_outputs: { [key in string]?: JsonValue }, 
/**
 * Final aggregated output (set when phase = Complete)
 */
aggregated_output: JsonValue | null, 
/**
 * Total sub-agents expected (`agent_ids.len() + pending_launches.len()`).
 */
expected_total: number, 
/**
 * Sub-agents that still need launching (waiting for a free slot).
 */
pending_launches: Array<PendingSubAgent>, 
/**
 * Maps launched `agent_id` to the `variant_key` used as the output key.
 */
agent_variant_keys: { [key in string]?: string }, };
