// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JudgeConfig } from "./JudgeConfig";

/**
 * In-daemon LLM calls (built with the `native-llm` feature). Distinct from
 * delegators: these are single typed API calls, not agent CLI sessions.
 */
export type NativeLlmConfig = { 
/**
 * Model that picks the winner of `multi_model` (`voting_mode = single_judge`)
 * and `multi_prompt` (`selection_strategy = model_choice`) steps. Unset keeps
 * the deterministic first/longest rule.
 */
judge?: JudgeConfig | null, };
