// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about the next step in the workflow
 */
export type NextStepInfo = { 
/**
 * Step name
 */
name: string, 
/**
 * Display name for the step
 */
display_name: string, 
/**
 * Review type: "none", "plan", "visual", "pr"
 */
review_type: string, 
/**
 * Prompt template for the step
 */
prompt: string | null, };
