// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OsNotificationConfig } from "./OsNotificationConfig";
import type { WebhookConfig } from "./WebhookConfig";

/**
 * Notifications configuration with support for multiple integrations.
 */
export type NotificationsConfig = { 
/**
 * Global enabled flag for all notifications
 */
enabled: boolean, 
/**
 * OS notification configuration
 */
os: OsNotificationConfig, 
/**
 * Single webhook configuration (for simple setups)
 */
webhook: WebhookConfig | null, 
/**
 * Multiple webhook configurations
 */
webhooks: Array<WebhookConfig>, };
