// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * OAuth error codes Operator emits.
 */
export type OAuthErrorCode = "authorization_pending" | "slow_down" | "expired_token" | "access_denied" | "invalid_grant" | "invalid_request" | "invalid_client" | "invalid_scope" | "unsupported_grant_type";
