// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OAuthErrorCode } from "./OAuthErrorCode";

/**
 * Standardized OAuth error, shaped per RFC 6749 §5.2 so stock clients can
 * interpret it - notably `authorization_pending` and `slow_down`, which a
 * device-flow client polls against.
 */
export type OAuthErrorResponse = { 
/**
 * Machine-readable error code.
 */
error: OAuthErrorCode, 
/**
 * Human-readable explanation.
 */
error_description?: string | null, 
/**
 * Documentation link.
 */
error_uri?: string | null, };
