// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Action to take when a step is rejected
 */
export type OnReject = { 
/**
 * Step name to return to on rejection
 */
goto_step: string, 
/**
 * Prompt to use when restarting after rejection
 */
prompt: string, };
