// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `OpenSpec` source location supplied during onboarding. Not a credential —
 * `OpenSpec` reads local markdown; there is no secret to validate or store.
 */
export type OpenspecSourceDto = { 
/**
 * Directory containing the `OpenSpec` `changes/` tree (e.g. "/repo/openspec")
 */
root_path: string, };
