// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `OpenSpec` provider configuration (experimental, pull-only)
 *
 * The instance name is the `HashMap` key in `KanbanConfig.openspec`. There
 * are no credentials — the provider reads local markdown under `root_path`.
 */
export type OpenspecConfig = { 
/**
 * Whether this provider is enabled
 */
enabled: boolean, 
/**
 * Directory containing the `OpenSpec` `changes/` tree (typically `<repo>/openspec`)
 */
root_path: string, 
/**
 * Operator project stamped on imported tickets (defaults to the change id)
 */
project?: string | null, };
