// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Standardized agent output for progress tracking and step transitions.
 *
 * Agents output a status block in their response which is parsed into this structure.
 * Used for progress tracking, loop detection, and intelligent step transitions.
 */
export type OperatorOutput = { 
/**
 * Current work status: in_progress, complete, blocked, failed
 */
status: string, 
/**
 * Agent signals done with step (true) or more work remains (false)
 */
exit_signal: boolean, 
/**
 * Agent's confidence in completion (0-100%)
 */
confidence: number | null, 
/**
 * Number of files changed this iteration
 */
files_modified: number | null, 
/**
 * Test suite status: passing, failing, skipped, not_run
 */
tests_status: string | null, 
/**
 * Number of errors encountered
 */
error_count: number | null, 
/**
 * Number of sub-tasks completed this iteration
 */
tasks_completed: number | null, 
/**
 * Estimated remaining sub-tasks
 */
tasks_remaining: number | null, 
/**
 * Brief description of work done (max 500 chars)
 */
summary: string | null, 
/**
 * Suggested next action (max 200 chars)
 */
recommendation: string | null, 
/**
 * Issues preventing progress (signals intervention needed)
 */
blockers: Array<string> | null, };
