// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * OS notification configuration.
 */
export type OsNotificationConfig = { 
/**
 * Whether OS notifications are enabled
 */
enabled: boolean, 
/**
 * Play sound with notifications
 */
sound: boolean, 
/**
 * Events to send (empty = all events)
 * Possible values: agent.started, agent.completed, agent.failed,
 * agent.awaiting_input, agent.session_lost, pr.created, pr.merged,
 * pr.closed, pr.ready_to_merge, pr.changes_requested,
 * ticket.returned, investigation.created
 */
events: Array<string>, };
