// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PanelNamesConfig = { status: string, queue: string, in_progress: string, completed: string, };
