// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PanelNamesConfig = { queue: string, agents: string, awaiting: string, completed: string, };
