// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PathsConfig = { tickets: string, projects: string, state: string, 
/**
 * Base directory for per-ticket worktrees (default: ~/.operator/worktrees)
 */
worktrees: string, };
