// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A sub-agent that has been planned but not yet launched (slot queue).
 */
export type PendingSubAgent = { 
/**
 * Delegator (from `config.delegators`) this sub-agent should use.
 */
delegator_name: string, 
/**
 * Fully-rendered prompt text for this sub-agent.
 */
prompt: string, 
/**
 * Key under which this sub-agent's output is recorded (see `individual_outputs`).
 */
variant_key: string, };
