// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Permission mode for LLM interaction
 */
export type PermissionMode = "default" | "plan" | "acceptEdits" | "delegate";
