// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemSource } from "./ItemSource";
import type { PipelineStage } from "./PipelineStage";

/**
 * Configuration for pipeline steps: iterate a list of items through ordered
 * stages with no barrier (each item flows through all stages independently).
 *
 * The step graph stays linear — a pipeline step still has exactly one
 * `next_step`. The fan-out (N items x M stages) lives entirely inside this one
 * step; iteration is an intra-step concern, never a step-to-step edge.
 */
export type PipelineConfig = { 
/**
 * Where the iterated items come from.
 */
item_source: ItemSource, 
/**
 * Ordered mini-steps each item flows through. Must be non-empty.
 */
stages: Array<PipelineStage>, };
