// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A single stage in a pipeline — deliberately flat (not a recursive
 * `StepSchema`): "prompt + optional agent/model/schema" only. It has no
 * `next_step`/`review_type`/`on_reject`, so a stage cannot reopen the
 * step-graph linearity question.
 */
export type PipelineStage = { 
/**
 * Handlebars prompt. The per-item value is appended as a JS binding at
 * export time (see `workflow_gen::export`), not via a Handlebars variable.
 */
prompt: string, 
/**
 * Optional agent/delegator name (falls back to the step/issuetype agent).
 */
agent?: string | null, 
/**
 * Optional model pin (emitted as `{ model: … }`).
 */
model?: string | null, 
/**
 * Optional structured-output JSON schema (emitted as `{ schema: … }`).
 */
jsonSchema?: JsonValue | null, 
/**
 * Optional display label override (defaults to `<step>:<stage-index>`).
 */
label?: string | null, };
