// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of credential authenticated a request.
 */
export type PrincipalKind = "session" | "access_token" | "local_process" | "agent_callback";
