// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Process execution status
 */
export type ProcessStatus = "running" | "completed" | "failed" | "killed";
