// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProfileSummary = { id: string, name: string, initialized: boolean, is_default: boolean, };
