// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-project/team sync configuration for a kanban provider
 */
export type ProjectSyncConfig = { 
/**
 * User ID to sync issues for (provider-specific format)
 * - Jira: accountId (e.g., "5e3f7acd9876543210abcdef")
 * - Linear: user ID (e.g., "abc12345-6789-0abc-def0-123456789abc")
 */
sync_user_id: string, 
/**
 * Workflow statuses to sync (empty = default/first status only)
 */
sync_statuses: Array<string>, 
/**
 * IssueTypeCollection name this project maps to
 */
collection_name: string, };
