// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectRepo } from "./ProjectRepo";

/**
 * Unified Project - combines git-focus (vibe-kanban) + AI-focus (Operator)
 *
 * A Project represents a codebase that can be worked on by AI agents.
 * It may contain multiple git repositories and has configuration for
 * both git operations and AI agent execution.
 */
export type Project = { 
/**
 * Unique identifier
 */
id: string, 
/**
 * Human-readable project name
 */
name: string, 
/**
 * Filesystem path to the project root
 */
path: string, 
/**
 * Associated git repositories (can be multiple for monorepos)
 */
repos: Array<ProjectRepo>, 
/**
 * Default branch for merging (e.g., "main", "master")
 */
default_branch: string | null, 
/**
 * Path to the AI context file (CLAUDE.md, GEMINI.md, etc.)
 */
ai_context_path: string | null, 
/**
 * Backstage taxonomy kind (tier 1-5)
 */
kind: string | null, 
/**
 * Tags for categorization
 */
tags: Array<string>, 
/**
 * Development server startup command
 */
dev_script: string | null, 
/**
 * Working directory for dev script execution
 */
dev_script_working_dir: string | null, 
/**
 * Default working directory for AI agents
 */
default_agent_working_dir: string | null, 
/**
 * Setup script to run before agent execution
 */
setup_script: string | null, 
/**
 * Cleanup script to run after agent execution
 */
cleanup_script: string | null, 
/**
 * Link to shared organizational project
 */
remote_project_id: string | null, created_at: string, updated_at: string, };
