// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A git repository associated with a project
 *
 * Projects can have multiple repos (monorepo pattern) or a single repo.
 * Each repo can have its own setup/cleanup scripts for worktree operations.
 */
export type ProjectRepo = { 
/**
 * Unique identifier for this repo association
 */
id: string, 
/**
 * Absolute path to the repository root
 */
path: string, 
/**
 * Whether this is the primary repo for the project
 */
is_primary: boolean, 
/**
 * Setup script to run when creating worktrees for this repo
 */
setup_script: string | null, 
/**
 * Cleanup script to run when deleting worktrees
 */
cleanup_script: string | null, 
/**
 * Files to copy into worktrees (e.g., .env files)
 */
copy_files: Array<string>, };
