// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of a project with analysis data
 */
export type ProjectSummary = { 
/**
 * Project directory name
 */
project_name: string, 
/**
 * Absolute path to project root
 */
project_path: string, 
/**
 * Whether the project directory exists on disk
 */
exists: boolean, 
/**
 * Whether catalog-info.yaml exists
 */
has_catalog_info: boolean, 
/**
 * Whether project-context.json exists
 */
has_project_context: boolean, 
/**
 * Primary Kind from kind_assessment (e.g., "microservice")
 */
kind: string | null, 
/**
 * Kind confidence score 0.0-1.0
 */
kind_confidence: number | null, 
/**
 * Taxonomy tier (e.g., "engines")
 */
kind_tier: string | null, 
/**
 * Language display names
 */
languages: Array<string>, 
/**
 * Framework display names
 */
frameworks: Array<string>, 
/**
 * Database display names
 */
databases: Array<string>, 
/**
 * Has Dockerfile or docker-compose
 */
has_docker: boolean | null, 
/**
 * Has test frameworks detected
 */
has_tests: boolean | null, 
/**
 * Detected port numbers
 */
ports: Array<number>, 
/**
 * Number of environment variables
 */
env_var_count: number, 
/**
 * Number of entry points
 */
entry_point_count: number, 
/**
 * Available command names (start, dev, test, etc.)
 */
commands: Array<string>, };
