// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LlmToolUsage } from "./LlmToolUsage";

/**
 * LLM usage statistics for a project
 */
export type ProjectLlmStats = { 
/**
 * Project name
 */
project: string, 
/**
 * Preferred LLM tool for this project (user override)
 */
preferred_tool: string | null, 
/**
 * Preferred model for this project (user override)
 */
preferred_model: string | null, 
/**
 * Usage history per LLM tool
 */
tool_usage: { [key in string]?: LlmToolUsage }, 
/**
 * Last updated timestamp
 */
updated_at: string, };
