// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-project/team sync configuration for a kanban provider
 */
export type ProjectSyncConfig = { 
/**
 * User ID to sync issues for (provider-specific format)
 * - Jira: accountId (e.g., "5e3f7acd9876543210abcdef")
 * - Linear: user ID (e.g., "abc12345-6789-0abc-def0-123456789abc")
 * - GitHub Projects: numeric GitHub `databaseId` (e.g., "12345678")
 */
sync_user_id: string, 
/**
 * Workflow statuses to sync (empty = default/first status only)
 */
sync_statuses: Array<string>, 
/**
 * Optional `IssueTypeCollection` name this project maps to.
 * Not required for kanban onboarding or sync.
 */
collection_name: string | null, 
/**
 * Explicit mapping: kanban issue type ID → operator issue type key (e.g., TASK, FEAT, FIX).
 * Multiple kanban types can map to the same operator template.
 */
type_mappings: { [key in string]?: string }, };
