// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration for proof review steps
 */
export type ProofReviewConfig = { 
/**
 * Assertion command run via `sh -c` in the worktree root; exit code 0 = pass.
 * Supports handlebars: `{{ticket_id}}`, `{{step}}`, `{{proof_dir}}`
 */
assertion_command: string, 
/**
 * Artifact-producing command (e.g. screenshot capture), run after the assertion regardless of its result
 */
artifact_command?: string | null, 
/**
 * Glob patterns (relative to worktree root) copied into `.proof/{ticket_id}/{step}/`
 */
artifact_patterns: Array<string>, 
/**
 * Per-command timeout in seconds (default 120)
 */
timeout_secs?: number | null, };
