// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Arbitrary CLI arguments per provider
 */
export type ProviderCliArgs = { 
/**
 * CLI arguments for Claude
 */
claude: Array<string>, 
/**
 * CLI arguments for Gemini
 */
gemini: Array<string>, 
/**
 * CLI arguments for Codex
 */
codex: Array<string>, };
