// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PR state (open, merged, closed)
 */
export type PrState = "OPEN" | "MERGED" | "CLOSED";
