// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrState } from "./PrState";

/**
 * PR info returned from GitHub
 */
export type PullRequestInfo = { 
/**
 * PR number
 */
number: bigint, 
/**
 * PR URL on GitHub
 */
url: string, 
/**
 * Current PR state
 */
state: PrState, 
/**
 * Merge commit SHA (if merged)
 */
merge_commit_sha: string | null, 
/**
 * PR title
 */
title: string | null, 
/**
 * Whether PR is a draft
 */
is_draft: boolean, };
