// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ticket counts keyed by issuetype.
 *
 * Issuetypes are an open set defined by collections, so this is a map rather
 * than fixed fields. `BTreeMap` keeps the JSON key order stable.
 */
export type QueueByType = { [key in string]: number };
