// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ticket counts by type for queue status
 */
export type QueueByType = { inv: number, fix: number, feat: number, spike: number, };
