// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QueueConfigurationPatch = { auto_assign: boolean | null, priority_order: Array<string> | null, poll_interval_ms: bigint | null, };
