// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueueByType } from "./QueueByType";

/**
 * Queue status response with ticket counts
 */
export type QueueStatusResponse = { 
/**
 * Tickets waiting in queue
 */
queued: number, 
/**
 * Tickets currently being worked on
 */
in_progress: number, 
/**
 * Tickets awaiting review or input
 */
awaiting: number, 
/**
 * Completed tickets (today)
 */
completed: number, 
/**
 * Breakdown by ticket type
 */
by_type: QueueByType, };
