// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QueueConfig = { auto_assign: boolean, priority_order: Array<string>, poll_interval_ms: bigint, };
