// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for queue pause/resume operations
 */
export type QueueControlResponse = { 
/**
 * Whether the queue is currently paused
 */
paused: boolean, 
/**
 * Human-readable message about the operation
 */
message: string, };
