// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RagSource } from "./RagSource";

/**
 * Configuration for RAG (retrieval-augmented generation) steps
 */
export type RagConfig = { 
/**
 * Context sources to retrieve before running the prompt
 */
sources: Array<RagSource>, 
/**
 * Maximum tokens of context to inject (default: 50000)
 */
max_context_tokens?: number | null, 
/**
 * Agent/delegator to use
 */
agent?: string | null, 
/**
 * Tools allowed for the agent
 */
allowed_tools: Array<string>, };
