// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A source of context for RAG steps
 */
export type RagSource = { "type": "glob", 
/**
 * Glob pattern relative to project root
 */
pattern: string, } | { "type": "file", 
/**
 * File path relative to project root
 */
path: string, } | { "type": "mcp", 
/**
 * MCP server name
 */
server: string, 
/**
 * Tool name on the MCP server
 */
tool: string, 
/**
 * Optional query template (Handlebars)
 */
query: string | null, };
