// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to reject an agent's review
 */
export type RejectReviewRequest = { 
/**
 * Reason for rejection (feedback for the agent)
 */
reason: string, };
