// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Relay MCP injection configuration
 */
export type RelayConfig = { 
/**
 * When true, automatically inject the relay MCP server for all delegators.
 * When false (default), relay injection is opt-in per delegator.
 */
auto_inject_mcp: boolean, };
