// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A named remote machine that agent CLI processes can be launched on over SSH.
 *
 * Distinct from [`ModelServer`] (where model *inference* lives) and from
 * [`RemoteAgentRef`] (an export-only agent owned by another platform): a
 * `RemoteHost` is where the agent *CLI process* runs. Referenced by name from
 * [`DelegatorLaunchConfig::host`].
 */
export type RemoteHost = { 
/**
 * Unique name referenced by `DelegatorLaunchConfig.host` (e.g., "gpu-vm")
 */
name: string, 
/**
 * SSH destination, resolved via the user's `~/.ssh/config`
 */
ssh_alias: string, 
/**
 * Absolute path to the project root on the remote host
 */
workdir: string, 
/**
 * Optional display name for UI
 */
display_name: string | null, };
