// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A declarative reference to a remote, named agent hosted by another platform.
 *
 * `platform` is the hosting service (`"agnt"`, `"openai"`) — deliberately
 * distinct from the core `provider`/`llm_tool` (the model or coding CLI). These
 * agents are API/memory-native and live on the remote side; Operator has no
 * runtime client for them, so a delegator carrying one is **export-only** and
 * cannot be launched locally (see the guard in `delegator_resolution`).
 */
export type RemoteAgentRef = { 
/**
 * Hosting platform (e.g. `"agnt"`, `"openai"`).
 */
platform: string, 
/**
 * Platform-native agent identifier (e.g. an AGNT agent UUID, an `OpenAI` `asst_…` id).
 */
id: string, };
