// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitProvider } from "./GitProvider";

/**
 * Repository info parsed from remote URL (provider-agnostic)
 */
export type RepoInfo = { 
/**
 * Repository hostname, retained for routing and monitor isolation.
 */
host: string | null, 
/**
 * Git hosting provider
 */
provider: GitProvider, 
/**
 * Repository owner (user or organization)
 */
owner: string, 
/**
 * Repository name
 */
repo_name: string, };
