// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Change the account password after proving knowledge of the current one.
 */
export type ResetPasswordRequest = { username: string, current_password: string, new_password: string, };
