// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of changing the account password.
 */
export type ResetPasswordResponse = { changed: boolean, };
