// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * REST API server configuration
 */
export type RestApiConfig = { 
/**
 * Whether the REST API is enabled
 */
enabled: boolean, 
/**
 * Address the REST API binds to. Defaults to `127.0.0.1` (local only) so the server is not reachable from other hosts. Set to `0.0.0.0` to expose it on all interfaces.
 */
host: string, 
/**
 * Port for the REST API server
 */
port: number, 
/**
 * CORS allowed origins. Empty means **same-origin only**
 */
cors_origins: Array<string>, 
/**
 * Externally reachable base URL (e.g. `https://operator.example.com`). Defaults to request host.
 */
public_url: string | null, };
