// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * REST API server configuration
 */
export type RestApiConfig = { 
/**
 * Whether the REST API is enabled
 */
enabled: boolean, 
/**
 * Address the REST API binds to. Defaults to `127.0.0.1` (local only) so
 * the server — which reports the project directory name — is not reachable
 * from other hosts. Set to `0.0.0.0` to expose it on all interfaces.
 */
host: string, 
/**
 * Port for the REST API server
 */
port: number, 
/**
 * CORS allowed origins. Empty means **same-origin only**
 */
cors_origins: Array<string>, 
/**
 * Externally reachable base URL (e.g. `https://operator.example.com`).
 *
 * OAuth and MCP descriptor URLs are generated from this rather than from the request's `Host` header,
 * which a caller controls. Defaults to request host, which is correct for a loopback bind and wrong behind a reverse proxy.
 */
public_url: string | null, };
