// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for agent review operations (approve/reject)
 */
export type ReviewResponse = { 
/**
 * Agent ID that was reviewed
 */
agent_id: string, 
/**
 * Review status: "approved" or "rejected"
 */
status: string, 
/**
 * Human-readable message about the operation
 */
message: string, };
