// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Type of review required for a step
 */
export type ReviewType = "none" | "plan" | "visual" | "pr" | "proof";
