// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of revoking an access key.
 */
export type RevokeAccessKeyResponse = { 
/**
 * The revoked key's identifier.
 */
id: string, 
/**
 * When revocation took effect.
 */
revoked_at: string, };
