// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A browser-openable action on a status section row (e.g. "Open Web UI",
 * "Swagger"). Only URL-style actions surface to the web UI; TUI-only actions
 * (toggles, env edits) are omitted.
 */
export type RowActionDto = { 
/**
 * Display label for the action button/link.
 */
label: string, 
/**
 * Browser URL the action opens.
 */
url: string, };
