// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why an execution process was spawned
 */
export type RunReason = "setupscript" | "codingagent" | "cleanup" | "followup";
