// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A typed authorization scope.
 *
 * Scopes are **not hierarchical**: `Write` does not imply `Read`. A credential
 * is granted each scope it needs explicitly, so an integration's authority is
 * legible from its scope list alone rather than requiring the reader to reason
 * about implication.
 */
export type Scope = "read" | "write" | "execute" | "admin";
