// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Health state of a section — controls the header color.
 */
export type SectionHealth = "Green" | "Yellow" | "Red" | "Gray";
