// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a collapsible section in the status tree.
 *
 * String values match the `sectionId` used in the `VSCode` extension tree routing.
 */
export type SectionId = "config" | "connections" | "kanban" | "llm" | "git" | "issuetypes" | "delegators" | "projects";
