// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionId } from "./SectionId";

/**
 * Declarative section metadata — shared between TUI and `VSCode`.
 */
export type SectionDefinition = { id: SectionId, label: string, prerequisites: Array<SectionId>, };
