// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionRowDto } from "./SectionRowDto";

/**
 * A status section with its health and child rows.
 */
export type SectionDto = { 
/**
 * Stable section id (e.g. "config", "connections", "kanban").
 */
id: string, label: string, 
/**
 * Health: "green" | "yellow" | "red" | "gray".
 */
health: string, description: string, 
/**
 * Section ids that must be Green before this section is usable.
 */
prerequisites: Array<string>, 
/**
 * Whether all prerequisites are met. Sections are always returned (the web
 * UI styles unmet ones as locked) rather than hidden by progressive disclosure.
 */
met: boolean, children: Array<SectionRowDto>, };
