// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RowActionDto } from "./RowActionDto";

/**
 * A child row within a status section.
 */
export type SectionRowDto = { 
/**
 * Stable, section-scoped row id. Clients use it as a tree key and to route
 * row-specific commands without matching on the (mutable) display label.
 * Dynamic rows carry their entity key (issue-type key, project name);
 * static rows carry a fixed slug (e.g. "git-token").
 */
id: string, 
/**
 * Nesting depth within the section (1 = direct child, 2 = grandchild).
 * Lets clients rebuild the tree (e.g. LLM tools → model aliases).
 */
depth: number, label: string, description: string, 
/**
 * Icon hint (e.g. "check", "warning", "tool", "folder").
 */
icon: string, 
/**
 * Health: "green" | "yellow" | "red" | "gray".
 */
health: string, 
/**
 * Browser-openable actions for this row (links shown in the web UI).
 */
actions: Array<RowActionDto>, };
