// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selection strategy for multi-prompt steps
 */
export type SelectionStrategy = "model_choice" | "scored";
