// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A conversational session within an attempt
 *
 * Sessions provide continuity for follow-up interactions.
 * This merges Operator's tmux session tracking with vibe-kanban's agent session concept.
 */
export type Session = { 
/**
 * Unique identifier
 */
id: string, 
/**
 * Parent attempt ID
 */
attempt_id: string, 
/**
 * Tmux session name for terminal-based execution
 */
tmux_session_name: string | null, 
/**
 * Hash of terminal content for change detection
 */
content_hash: string | null, 
/**
 * Agent's internal session ID (e.g., Claude's conversation ID)
 */
agent_session_id: string | null, 
/**
 * Summary extracted from message store
 */
summary: string | null, created_at: string, updated_at: string, };
