// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionWrapperType } from "./SessionWrapperType";
import type { SessionsTmuxConfig } from "./SessionsTmuxConfig";
import type { SessionsVSCodeConfig } from "./SessionsVSCodeConfig";

/**
 * Session wrapper configuration
 *
 * Controls how operator creates and manages terminal sessions for agents.
 * Two modes are supported:
 * - tmux: Standalone tmux sessions (default)
 * - vscode: VS Code integrated terminal (requires extension)
 */
export type SessionsConfig = { 
/**
 * Which session wrapper to use
 */
wrapper: SessionWrapperType, 
/**
 * Tmux-specific configuration
 */
tmux: SessionsTmuxConfig, 
/**
 * VS Code-specific configuration
 */
vscode: SessionsVSCodeConfig, };
