// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionWrapperType } from "./SessionWrapperType";
import type { SessionsCmuxConfig } from "./SessionsCmuxConfig";
import type { SessionsTmuxConfig } from "./SessionsTmuxConfig";
import type { SessionsVSCodeConfig } from "./SessionsVSCodeConfig";
import type { SessionsZellijConfig } from "./SessionsZellijConfig";

/**
 * Session wrapper configuration
 *
 * Controls how operator creates and manages terminal sessions for agents.
 * Four modes are supported:
 * - tmux: Standalone tmux sessions (default)
 * - vscode: VS Code integrated terminal (requires extension)
 * - cmux: macOS terminal multiplexer (requires running inside cmux)
 * - zellij: Zellij terminal workspace manager
 */
export type SessionsConfig = { 
/**
 * Which session wrapper to use
 */
wrapper: SessionWrapperType, 
/**
 * Tmux-specific configuration
 */
tmux: SessionsTmuxConfig, 
/**
 * VS Code-specific configuration
 */
vscode: SessionsVSCodeConfig, 
/**
 * cmux-specific configuration
 */
cmux: SessionsCmuxConfig, 
/**
 * Zellij-specific configuration
 */
zellij: SessionsZellijConfig, };
