// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * VS Code extension session configuration
 */
export type SessionsVSCodeConfig = { 
/**
 * Port for extension webhook server
 */
webhook_port: number, 
/**
 * Connection timeout in milliseconds
 */
connect_timeout_ms: bigint, };
