// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Zellij terminal workspace manager session configuration
 */
export type SessionsZellijConfig = { 
/**
 * Require running inside Zellij (ZELLIJ env var present)
 */
require_in_zellij: boolean, };
