// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceSummary } from "./DeviceSummary";
import type { SessionSummary } from "./SessionSummary";

/**
 * All sessions and devices for the admin account.
 */
export type SessionListResponse = { 
/**
 * Browser sessions.
 */
sessions: Array<SessionSummary>, 
/**
 * Device-flow clients.
 */
devices: Array<DeviceSummary>, };
