// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tmux-specific session configuration
 */
export type SessionsTmuxConfig = { 
/**
 * Whether custom tmux config has been generated
 */
config_generated: boolean, 
/**
 * Socket name for session isolation
 */
socket_name: string, };
