// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An active or expired browser session. Carries no session identifier — the
 * cookie value is never readable back out, only the session's `id` for
 * revocation.
 */
export type SessionSummary = { 
/**
 * Stable identifier, safe to display and to reference for revocation.
 */
id: string, 
/**
 * When the session began.
 */
created_at: string, 
/**
 * When the session expires.
 */
expires_at: string, 
/**
 * When the session was last used.
 */
last_used_at?: string | null, 
/**
 * When the session was revoked; `None` while active.
 */
revoked_at?: string | null, 
/**
 * Whether this is the session making the request.
 */
current: boolean, };
