// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Session wrapper type for terminal session management
 */
export type SessionWrapperType = "tmux" | "vscode";
