// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CmuxPlacementPolicy } from "./CmuxPlacementPolicy";

/**
 * cmux macOS terminal multiplexer session configuration
 */
export type SessionsCmuxConfig = { 
/**
 * Path to the cmux binary
 */
binary_path: string, 
/**
 * Require running inside cmux (`CMUX_WORKSPACE_ID` env var present)
 */
require_in_cmux: boolean, 
/**
 * Where to place new agent sessions: "auto", "workspace", or "window"
 */
placement: CmuxPlacementPolicy, };
