// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to set the global default LLM tool and model
 */
export type SetDefaultLlmRequest = { 
/**
 * Tool name (must match a detected tool, e.g., "claude")
 */
tool: string, 
/**
 * Model alias (e.g., "opus", "sonnet")
 */
model: string, };
