// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GithubSessionEnv } from "./GithubSessionEnv";
import type { JiraSessionEnv } from "./JiraSessionEnv";
import type { KanbanProviderKind } from "./KanbanProviderKind";
import type { LinearSessionEnv } from "./LinearSessionEnv";

/**
 * Request to set kanban-related env vars on the server for the current
 * session so subsequent `from_config` calls find the API key.
 */
export type SetKanbanSessionEnvRequest = { provider: KanbanProviderKind, jira?: JiraSessionEnv | null, linear?: LinearSessionEnv | null, github?: GithubSessionEnv | null, };
