// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from setting session env vars.
 *
 * `shell_export_block` uses `<your-token>` placeholders, NOT the actual
 * secret — it is meant for the user to copy into their shell profile.
 */
export type SetKanbanSessionEnvResponse = { 
/**
 * Names (not values) of env vars that were set in the server process.
 */
env_vars_set: Array<string>, 
/**
 * Multi-line `export FOO="<your-token>"` block for the user to copy
 * into `~/.zshrc` / `~/.bashrc`.
 */
shell_export_block: string, };
