// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetupStep } from "./SetupStep";

export type SetupStepResponse = { slug: SetupStep, name: string, description: string, help_text: string, order: number, };
