// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetupInitializeResponse = { initialized: boolean, config_path: string, tickets_path: string, files_created: Array<string>, files_skipped: Array<string>, projects: Array<string>, };
