// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionPreset } from "./CollectionPreset";
import type { HostedCollectionSelection } from "./HostedCollectionSelection";
import type { SessionWrapperType } from "./SessionWrapperType";
import type { SetupExecutionTarget } from "./SetupExecutionTarget";

export type SetupInitializeRequest = { preset: CollectionPreset, task_fields: Array<string>, wrapper: SessionWrapperType, execution_target: SetupExecutionTarget, use_worktrees: boolean, acceptance_criteria: string, model_servers: Array<string>, hosted_collections: Array<HostedCollectionSelection>, };
