// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetupStatusResponse = { initialized: boolean, admin_configured: boolean, config_path: string, tickets_path: string, projects_by_tool: { [key in string]: Array<string> }, default_acceptance_criteria: string, };
