// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetupCollectionResponse = { id: string, name: string, description: string, types: Array<string>, default_selected: Array<string>, origin: string, note?: string | null, checksum: string, };
