// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetupExecutionTarget = { "kind": "local" } | { "kind": "coder", name: string, template: string, parameters: { [key in string]: string }, };
