// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single discovered skill file
 */
export type SkillEntry = { 
/**
 * Tool this skill belongs to (e.g., "claude", "codex")
 */
tool_name: string, 
/**
 * Filename of the skill (e.g., "commit.md")
 */
filename: string, 
/**
 * Full path to the skill file
 */
file_path: string, 
/**
 * Scope: "global" or "project"
 */
scope: string, };
