// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillEntry } from "./SkillEntry";

/**
 * Response for skills listing
 */
export type SkillsResponse = { 
/**
 * List of discovered skills
 */
skills: Array<SkillEntry>, 
/**
 * Total count
 */
total: number, };
