// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-tool skill directory overrides
 */
export type SkillDirectoriesOverride = { 
/**
 * Additional global skill directories
 */
global: Array<string>, 
/**
 * Additional project-relative skill directories
 */
project: Array<string>, };
