// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SSH target payload. Name and display name live on `TargetDef`; this is the
 * connection shape (`RemoteHost` minus identity).
 */
export type SshTarget = { 
/**
 * Host alias resolved via the user's `~/.ssh/config` (or `ssh_config_path`)
 */
ssh_alias: string, 
/**
 * Absolute project root on the remote machine
 */
workdir: string, 
/**
 * SSH config fragment passed with `-F` (used by provisioned coder aliases)
 */
ssh_config_path?: string | null, };
