// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentState } from "./AgentState";
import type { CompletedTicket } from "./CompletedTicket";
import type { ProjectLlmStats } from "./ProjectLlmStats";

export type State = { paused: boolean, agents: Array<AgentState>, completed: Array<CompletedTicket>, 
/**
 * Per-project LLM usage statistics
 */
project_llm_stats: { [key in string]?: ProjectLlmStats }, 
/**
 * Per-project issue type collection preferences (project_name -> collection_name)
 */
project_collection_prefs: { [key in string]?: string }, };
