// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status response with registry info
 */
export type StatusResponse = { status: string, version: string, issuetype_count: number, collection_count: number, active_collection: string, };
