// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status response with registry info
 */
export type StatusResponse = { status: string, version: string, 
/**
 * Top-level directory name of the operator working root (e.g. "acme").
 */
directory_name: string, 
/**
 * Non-reversible fingerprint of the working root's canonical path.
 */
directory_id: string, issuetype_count: number, collection_count: number, active_collection: string, };
