// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stdio entrypoint advertised in the descriptor when
 * `[mcp].stdio_advertised = true`. Clients use this to spawn operator
 * as an MCP subprocess instead of (or alongside) the SSE transport.
 */
export type StdioCommand = { 
/**
 * Absolute path to the operator binary (the same binary serving this descriptor)
 */
command: string, 
/**
 * Args to pass: typically `["mcp"]`
 */
args: Array<string>, 
/**
 * Working directory the client should set when spawning. Defaults to the
 * operator process's current working directory.
 */
cwd: string, };
