// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttemptStatus } from "./AttemptStatus";

/**
 * An isolated execution attempt for a workflow step
 *
 * This is the Operator equivalent of vibe-kanban's TaskAttempt/Workspace.
 * Each attempt runs in its own git worktree with a dedicated branch,
 * allowing for retry/reset without affecting the main codebase.
 */
export type StepAttempt = { 
/**
 * Unique identifier for this attempt
 */
id: string, 
/**
 * Parent ticket ID (e.g., "FEAT-1234")
 */
ticket_id: string, 
/**
 * Which step this attempt is executing (e.g., "plan", "implement", "test")
 */
step_name: string, 
/**
 * Project name this attempt belongs to
 */
project: string, 
/**
 * Git branch for this attempt (e.g., "feat/abc123-add-login")
 */
branch: string, 
/**
 * Target branch to merge into (e.g., "main")
 */
target_branch: string, 
/**
 * Path to isolated git worktree (if using worktree isolation)
 */
worktree_path: string | null, 
/**
 * Whether the worktree has been cleaned up
 */
worktree_deleted: boolean, 
/**
 * Which LLM tool is executing (e.g., "claude", "gemini", "codex")
 */
executor: string, 
/**
 * Executor model override (e.g., "claude-sonnet-4-20250514")
 */
executor_model: string | null, 
/**
 * Current session ID for conversational continuity
 */
session_id: string | null, 
/**
 * Launch mode: "default", "yolo", "docker", "docker-yolo"
 */
launch_mode: string | null, 
/**
 * Current status of this attempt
 */
status: AttemptStatus, 
/**
 * Whether this attempt requires human pairing (SPIKE/INV modes)
 */
paired: boolean, 
/**
 * Tmux session name (for Operator's terminal-based execution)
 */
tmux_session: string | null, 
/**
 * Hash of last captured terminal content (for change detection)
 */
content_hash: string | null, 
/**
 * Pull request URL if created
 */
pr_url: string | null, 
/**
 * PR number for API tracking
 */
pr_number: bigint | null, 
/**
 * GitHub repo in format "owner/repo"
 */
github_repo: string | null, 
/**
 * Current PR status ("open", "approved", "changes_requested", "merged", "closed")
 */
pr_status: string | null, 
/**
 * When setup completed (worktree created, scripts run)
 */
setup_completed_at: string | null, 
/**
 * Last activity timestamp
 */
last_activity: string, 
/**
 * Last time terminal content changed (for hung detection)
 */
last_content_change: string | null, created_at: string, updated_at: string, };
