// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassifierConfig } from "./ClassifierConfig";
import type { DelegatorStepConfig } from "./DelegatorStepConfig";
import type { MatrixedConfig } from "./MatrixedConfig";
import type { McpStepConfig } from "./McpStepConfig";
import type { MultiModelConfig } from "./MultiModelConfig";
import type { MultiPromptConfig } from "./MultiPromptConfig";
import type { OnReject } from "./OnReject";
import type { PermissionMode } from "./PermissionMode";
import type { PipelineConfig } from "./PipelineConfig";
import type { ProviderCliArgs } from "./ProviderCliArgs";
import type { RagConfig } from "./RagConfig";
import type { ReviewType } from "./ReviewType";
import type { StepOutput } from "./StepOutput";
import type { StepPermissions } from "./StepPermissions";
import type { StepTypeTag } from "./StepTypeTag";
import type { VisualReviewConfig } from "./VisualReviewConfig";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Schema definition for a lifecycle step
 */
export type StepSchema = { 
/**
 * Step identifier (lowercase)
 */
name: string, 
/**
 * Human-readable step name
 */
display_name?: string | null, 
/**
 * Step type discriminator (defaults to "task" for backward compatibility)
 */
type: StepTypeTag, 
/**
 * Types of outputs this step produces
 */
outputs: Array<StepOutput>, 
/**
 * Initial prompt template for the Claude agent
 */
prompt: string, 
/**
 * Type of review required for this step (none, plan, visual, pr)
 */
review_type: ReviewType, 
/**
 * Configuration for visual review (required when `review_type` is "visual")
 */
visual_config?: VisualReviewConfig | null, 
/**
 * What to do if step output is rejected
 */
on_reject?: OnReject | null, 
/**
 * Name of the next step (None for final step)
 */
next_step?: string | null, 
/**
 * Claude Code tools allowed in this step
 */
allowed_tools: Array<string>, 
/**
 * Optional agent (delegator) name for this step (overrides ticket's default agent)
 */
agent?: string | null, 
/**
 * Provider-agnostic permissions for this step
 */
permissions?: StepPermissions | null, 
/**
 * Arbitrary CLI arguments per provider
 */
cli_args?: ProviderCliArgs | null, 
/**
 * Preferred LLM permission mode for this step
 */
permission_mode: PermissionMode, 
/**
 * Inline JSON schema for structured output (Claude-specific)
 */
jsonSchema?: JsonValue | null, 
/**
 * Path to JSON schema file for structured output (Claude-specific)
 */
jsonSchemaFile?: string | null, 
/**
 * File glob patterns in the worktree that signal this step is complete
 */
artifact_patterns: Array<string>, 
/**
 * Configuration for classifier steps (required when type=classifier)
 */
classifier_config?: ClassifierConfig | null, 
/**
 * Configuration for RAG steps (required when type=rag)
 */
rag_config?: RagConfig | null, 
/**
 * Configuration for delegator steps (required when type=delegator)
 */
delegator_config?: DelegatorStepConfig | null, 
/**
 * Configuration for MCP steps (required when type=mcp)
 */
mcp_config?: McpStepConfig | null, 
/**
 * Configuration for multi-model steps (required when `type=multi_model`)
 */
multi_model_config?: MultiModelConfig | null, 
/**
 * Configuration for multi-prompt steps (required when `type=multi_prompt`)
 */
multi_prompt_config?: MultiPromptConfig | null, 
/**
 * Configuration for matrixed steps (required when type=matrixed)
 */
matrixed_config?: MatrixedConfig | null, 
/**
 * Configuration for pipeline steps (required when type=pipeline)
 */
pipeline_config?: PipelineConfig | null, };
