// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Discriminator tag for step types
 */
export type StepTypeTag = "task" | "classifier" | "rag" | "delegator" | "mcp" | "multi_model" | "multi_prompt" | "matrixed" | "pipeline";
