// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NextStepInfo } from "./NextStepInfo";

/**
 * Response from step completion endpoint
 */
export type StepCompleteResponse = { 
/**
 * Status of the step: "completed", "awaiting_review", "failed", "iterate"
 */
status: string, 
/**
 * Information about the next step (if any)
 */
next_step: NextStepInfo | null, 
/**
 * Whether to automatically proceed to the next step
 */
auto_proceed: boolean, 
/**
 * Command to execute for the next step (opr8r wrapped)
 */
next_command: string | null, 
/**
 * Whether OperatorOutput was successfully parsed from agent output
 */
output_valid: boolean, 
/**
 * Agent has more work (exit_signal=false) - indicates iteration needed
 */
should_iterate: boolean, 
/**
 * How many times this step has run (for circuit breaker)
 */
iteration_count: number, 
/**
 * Circuit breaker state: closed (normal), half_open (monitoring), open (halted)
 */
circuit_state: string, 
/**
 * Summary from previous step's OperatorOutput
 */
previous_summary: string | null, 
/**
 * Recommendation from previous step's OperatorOutput
 */
previous_recommendation: string | null, 
/**
 * Cumulative files modified across iterations
 */
cumulative_files_modified: number, 
/**
 * Cumulative errors across iterations
 */
cumulative_errors: number, };
