// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Launch context fixed at launch time, persisted with the agent record, and
 * read back by `complete_step` to build subsequent step commands.
 *
 * The persisted context is the baseline for a ticket's whole chain; per-step
 * `agent` overrides from the step schema apply on top for that step only.
 */
export type StepLaunchContext = { 
/**
 * Delegator name used at launch (None = ad-hoc provider/model)
 */
delegator: string | null, 
/**
 * Resolved LLM tool (e.g. "claude")
 */
tool: string, 
/**
 * Resolved model alias (e.g. "sonnet")
 */
model: string, 
/**
 * YOLO (auto-accept) mode
 */
yolo: boolean, 
/**
 * Session UUID of the step launched with this context (informational;
 * each transition mints a fresh UUID for the next step)
 */
session_id: string | null, 
/**
 * opr8r invocation for the launch environment ("opr8r" inside a
 * container where the image ships it on PATH, an absolute path locally).
 * Steps exec inside the same environment, so the value holds chain-wide.
 */
opr8r: string, 
/**
 * Relay MCP injection override from the delegator launch config
 */
operator_relay: boolean | null, 
/**
 * Extra CLI flags from the delegator launch config
 */
extra_flags: Array<string>, };
