// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NextStepInfo } from "./NextStepInfo";

/**
 * Response from step completion endpoint
 */
export type StepCompleteResponse = { 
/**
 * Status of the step: "completed", "awaiting_review", "failed"
 */
status: string, 
/**
 * Information about the next step (if any)
 */
next_step: NextStepInfo | null, 
/**
 * Whether to automatically proceed to the next step
 */
auto_proceed: boolean, 
/**
 * Command to execute for the next step (opr8r wrapped)
 */
next_command: string | null, };
