// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for a step
 */
export type StepResponse = { name: string, display_name: string | null, prompt: string, outputs: Array<string>, allowed_tools: Array<string>, 
/**
 * Type of review required: "none", "plan", "visual", "pr"
 */
review_type: string, next_step: string | null, permission_mode: string, };
