// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperatorOutput } from "./OperatorOutput";

/**
 * Request to report step completion (from opr8r wrapper)
 */
export type StepCompleteRequest = { 
/**
 * Exit code from the LLM command
 */
exit_code: number, 
/**
 * Whether output validation passed (if schema was specified)
 */
output_valid: boolean, 
/**
 * List of validation errors (if output_valid is false)
 */
output_schema_errors: Array<string> | null, 
/**
 * Session ID from the LLM session
 */
session_id: string | null, 
/**
 * Duration of the step in seconds
 */
duration_secs: bigint, 
/**
 * Sample of the output (first N chars for debugging)
 */
output_sample: string | null, 
/**
 * Structured output from agent (parsed OPERATOR_STATUS block)
 */
output: OperatorOutput | null, };
