// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomFlags } from "./CustomFlags";
import type { DirectoryPermissions } from "./DirectoryPermissions";
import type { McpServerPermissions } from "./McpServerPermissions";
import type { ToolPermissions } from "./ToolPermissions";

/**
 * Complete permission set for a step (as defined in issuetype schema)
 */
export type StepPermissions = { 
/**
 * Tool-level allow/deny lists
 */
tools: ToolPermissions, 
/**
 * Directory-level allow/deny lists
 */
directories: DirectoryPermissions, 
/**
 * MCP server enable/disable configuration
 */
mcp_servers: McpServerPermissions, 
/**
 * Per-provider custom configuration flags
 */
custom_flags: CustomFlags, };
