// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Official support / maturity level of an advertised integration.
 */
export type SupportStatus = "proto" | "alpha" | "beta" | "ga";
