// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KanbanIssueTypeResponse } from "./KanbanIssueTypeResponse";

/**
 * Response from syncing kanban issue types from a provider.
 */
export type SyncKanbanIssueTypesResponse = { 
/**
 * Number of issue types synced
 */
synced: number, 
/**
 * The synced issue types
 */
types: Array<KanbanIssueTypeResponse>, };
