// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoderConfig } from "./CoderConfig";
import type { DockerConfig } from "./DockerConfig";
import type { SshTarget } from "./SshTarget";

/**
 * A named execution target agents can be launched on.
 */
export type TargetDef = { 
/**
 * Unique name, referenced by `DelegatorLaunchConfig.target`.
 * `local` and `docker` are reserved for synthesized targets.
 */
name: string, 
/**
 * Human-readable name for UI surfaces
 */
display_name?: string | null, } & ({ "kind": "local" } | { "kind": "docker" } & DockerConfig | { "kind": "coder" } & CoderConfig | { "kind": "ssh" } & SshTarget);
