// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TargetToolProbe } from "./TargetToolProbe";

export type TargetProbeResponse = { reachable: boolean, message: string, 
/**
 * LLM CLIs reported by `opr8r tools --json` on the target. Empty if unreachable/unknown.
 */
tools: Array<TargetToolProbe>, tools_error?: string | null, };
