// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoderConfig } from "./CoderConfig";
import type { DockerConfig } from "./DockerConfig";
import type { SshTarget } from "./SshTarget";

/**
 * Execution-target kind, tagged by `kind` in config.
 */
export type TargetKind = { "kind": "local" } | { "kind": "docker" } & DockerConfig | { "kind": "coder" } & CoderConfig | { "kind": "ssh" } & SshTarget;
