// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionPreset } from "./CollectionPreset";

export type TemplatesConfig = { 
/**
 * Named preset for issue type collection
 * Options: simple, dev_kanban, devops_kanban, custom
 */
preset: CollectionPreset, 
/**
 * Custom issuetype collection (only used when preset = custom)
 * List of issue type keys: TASK, FEAT, FIX, SPIKE, INV
 */
collection: Array<string>, 
/**
 * Active collection name (overrides preset if set)
 * Can be a builtin preset name or a user-defined collection
 */
active_collection: string | null, };
