// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionMode } from "./ExecutionMode";
import type { FieldSchema } from "./FieldSchema";
import type { StepSchema } from "./StepSchema";

/**
 * Schema definition for an issuetype template
 */
export type TemplateSchema = { 
/**
 * Unique issuetype key (e.g., FEAT, FIX, SPIKE, INV, TASK)
 */
key: string, 
/**
 * Display name of the template type
 */
name: string, 
/**
 * Brief description of when to use this template
 */
description: string, 
/**
 * Whether this issuetype runs autonomously or requires human pairing
 */
mode: ExecutionMode, 
/**
 * Glyph character displayed in UI for this issuetype
 */
glyph: string, 
/**
 * Optional color for glyph display in TUI
 */
color?: string | null, 
/**
 * Whether a project must be specified for this issuetype
 */
project_required: boolean, 
/**
 * Field definitions for this template
 */
fields: Array<FieldSchema>, 
/**
 * Lifecycle steps for completing this ticket type
 */
steps: Array<StepSchema>, 
/**
 * Optional prompt for work launching (interpolated with handlebars)
 */
prompt?: string | null, 
/**
 * Prompt for generating this issue type's operator agent via `claude -p`
 */
agent_prompt?: string | null, 
/**
 * Default delegator name for this issuetype (overridden by step.agent)
 */
agent?: string | null, };
