// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Theme color configuration for Backstage
 * Default colors match Operator's tmux theme
 */
export type ThemeColors = { 
/**
 * Primary/accent color (default: salmon #cc6c55)
 */
primary: string, 
/**
 * Secondary color (default: dark teal #114145)
 */
secondary: string, 
/**
 * Accent/highlight color (default: cream #f4dbb7)
 */
accent: string, 
/**
 * Warning/error color (default: coral #d46048)
 */
warning: string, 
/**
 * Muted text color (default: darker salmon #8a4a3a)
 */
muted: string, };
