// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Workflow status, as constrained by `src/schemas/ticket_metadata.schema.json`.
 */
export type TicketStatus = "queued" | "running" | "awaiting" | "completed";
