// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Full ticket details including content and metadata
 */
export type TicketDetailResponse = { 
/**
 * Ticket ID (e.g., "FEAT-7598")
 */
id: string, 
/**
 * Ticket summary/title
 */
summary: string, 
/**
 * Ticket type: FEAT, FIX, INV, SPIKE
 */
ticket_type: string, 
/**
 * Project name
 */
project: string, 
/**
 * Current status: queued, running, awaiting, completed
 */
status: string, 
/**
 * Current step name
 */
step: string, 
/**
 * Human-readable step name
 */
step_display_name: string | null, 
/**
 * Priority: P0-critical, P1-high, P2-medium, P3-low
 */
priority: string, 
/**
 * Timestamp (YYYYMMDD-HHMM format)
 */
timestamp: string, 
/**
 * Full markdown content of the ticket
 */
content: string, 
/**
 * Ticket filename
 */
filename: string, 
/**
 * Full filesystem path
 */
filepath: string, 
/**
 * Session IDs per step (`step_name` -> `session_uuid`)
 */
sessions: { [key in string]: string }, 
/**
 * Delegator used per step (`step_name` -> `delegator_name`)
 */
step_delegators: { [key in string]: string }, 
/**
 * Path to git worktree (if created)
 */
worktree_path: string | null, 
/**
 * Git branch name
 */
branch: string | null, 
/**
 * External issue ID from kanban provider
 */
external_id: string | null, 
/**
 * URL to the issue in the external provider
 */
external_url: string | null, 
/**
 * Provider name (e.g., "jira", "linear")
 */
external_provider: string | null, };
