// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ticket urgency, as constrained by `src/schemas/ticket_metadata.schema.json`.
 *
 * Variants are declared most-urgent first, so the derived `Ord` is the sort order.
 */
export type TicketPriority = "P0-critical" | "P1-high" | "P2-medium" | "P3-low";
