// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TmuxConfig = { 
/**
 * Whether custom tmux config has been generated
 */
config_generated: boolean, };
