// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scope } from "./Scope";

/**
 * A newly issued access token, and a refresh token when the grant produces one.
 */
export type TokenResponse = { 
/**
 * Signed, short-lived bearer token.
 */
access_token: string, 
/**
 * Always `Bearer`.
 */
token_type: string, 
/**
 * Seconds until `access_token` expires.
 */
expires_in: bigint, 
/**
 * Opaque rotating refresh token. Absent for access-key exchange, which is
 * re-exercised with the key itself rather than refreshed.
 */
refresh_token?: string | null, 
/**
 * Scopes the access token carries.
 */
scopes: Array<Scope>, };
