// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token endpoint request. The discriminator makes unrelated credential
 * combinations unrepresentable.
 */
export type TokenRequest = { "grant_type": "urn:ietf:params:oauth:grant-type:device_code", device_code: string, client_id: string, } | { "grant_type": "refresh_token", refresh_token: string, client_id: string, } | { "grant_type": "operator:access-key", access_key: string, };
