// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provider-agnostic tool pattern
 */
export type ToolPattern = { 
/**
 * Tool name: Read, Write, Edit, Bash, Glob, Grep, `WebFetch`, etc.
 */
tool: string, 
/**
 * Optional pattern for tool arguments (e.g., "cargo test:*" for Bash)
 */
pattern?: string | null, };
