// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolCapabilitiesSummary = { supports_sessions: boolean, supports_headless: boolean, };
