// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolPattern } from "./ToolPattern";

/**
 * Tool-level permissions (allow/deny lists)
 */
export type ToolPermissions = { 
/**
 * Tools/patterns to allow
 */
allow: Array<ToolPattern>, 
/**
 * Tools/patterns to deny
 */
deny: Array<ToolPattern>, };
