// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tool capabilities
 */
export type ToolCapabilities = { 
/**
 * Whether the tool supports session continuity via UUID
 */
supports_sessions: boolean, 
/**
 * Whether the tool can run in headless/non-interactive mode
 */
supports_headless: boolean, };
