// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PanelNamesConfigurationPatch } from "./PanelNamesConfigurationPatch";

export type UiConfigurationPatch = { refresh_rate_ms: bigint | null, completed_history_hours: bigint | null, summary_max_length: number | null, panel_names: PanelNamesConfigurationPatch | null, };
