// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unified PR comment (general or inline review)
 */
export type UnifiedPrComment = { "comment_type": "general", id: string, author: string, author_association: string, body: string, created_at: string, url: string, } | { "comment_type": "review", id: bigint, author: string, author_association: string, body: string, created_at: string, url: string, 
/**
 * File path the comment is on
 */
path: string, 
/**
 * Line number (if applicable)
 */
line: bigint | null, 
/**
 * Diff hunk context
 */
diff_hunk: string, };
