// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to update a step
 */
export type UpdateStepRequest = { display_name: string | null, prompt: string | null, outputs: Array<string> | null, allowed_tools: Array<string> | null, 
/**
 * Type of review required: "none", "plan", "visual", "pr"
 */
review_type: string | null, next_step: string | null, permission_mode: string | null, };
