// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from updating a ticket's status
 */
export type UpdateTicketStatusResponse = { 
/**
 * Ticket ID
 */
id: string, 
/**
 * Previous status before the update
 */
previous_status: string, 
/**
 * New status after the update
 */
status: string, 
/**
 * Human-readable message
 */
message: string, };
