// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to update a ticket's status
 */
export type UpdateTicketStatusRequest = { 
/**
 * Target status: queued, running, awaiting, done
 */
status: string, };
