// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentsConfigurationPatch } from "./AgentsConfigurationPatch";
import type { LaunchConfigurationPatch } from "./LaunchConfigurationPatch";
import type { QueueConfigurationPatch } from "./QueueConfigurationPatch";
import type { UiConfigurationPatch } from "./UiConfigurationPatch";

/**
 * Field-level patch for the public operational configuration.
 */
export type UpdateConfigurationRequest = { agents: AgentsConfigurationPatch | null, queue: QueueConfigurationPatch | null, ui: UiConfigurationPatch | null, launch: LaunchConfigurationPatch | null, };
