// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateFieldRequest } from "./CreateFieldRequest";
import type { CreateStepRequest } from "./CreateStepRequest";

/**
 * Request to update an issue type
 */
export type UpdateIssueTypeRequest = { name: string | null, description: string | null, mode: string | null, glyph: string | null, color: string | null, project_required: boolean | null, fields: Array<CreateFieldRequest> | null, steps: Array<CreateStepRequest> | null, };
