// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GithubValidationDetailsDto } from "./GithubValidationDetailsDto";
import type { JiraValidationDetailsDto } from "./JiraValidationDetailsDto";
import type { LinearValidationDetailsDto } from "./LinearValidationDetailsDto";

/**
 * Response from validating kanban credentials.
 *
 * `valid: false` is returned for auth failures — never a 4xx/5xx HTTP
 * status — so clients can display `error` inline without exception handling.
 */
export type ValidateKanbanCredentialsResponse = { valid: boolean, error?: string | null, jira?: JiraValidationDetailsDto | null, linear?: LinearValidationDetailsDto | null, github?: GithubValidationDetailsDto | null, };
