// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Version check configuration for automatic update notifications
 */
export type VersionCheckConfig = { 
/**
 * Enable automatic version checking on startup
 */
enabled: boolean, 
/**
 * URL to fetch latest version from (optional, can be removed)
 */
url: string | null, 
/**
 * Timeout in seconds for version check HTTP request
 */
timeout_secs: bigint, };
