// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration for visual review steps
 */
export type VisualReviewConfig = { 
/**
 * URL to open for visual check (supports handlebars templates)
 */
url: string, 
/**
 * Optional startup command (e.g., dev server) to run before opening browser
 */
startup_command?: string | null, 
/**
 * Timeout in seconds for server startup (default: 30)
 */
startup_timeout_secs?: number | null, };
