// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Voting strategy for multi-model steps
 */
export type VotingStrategy = "majority" | "ranked" | "unanimous";
