// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the voting round is executed in multi-model steps
 */
export type VotingMode = "single_judge" | "multi_voter";
