// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VsCodeTerminalState } from "./VsCodeTerminalState";

/**
 * Terminal list response
 */
export type VsCodeListResponse = { 
/**
 * List of managed terminals
 */
terminals: Array<VsCodeTerminalState>, };
