// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VsCodeTicketStatus } from "./VsCodeTicketStatus";

/**
 * Information about a ticket from .tickets directory
 */
export type VsCodeTicketInfo = { 
/**
 * Ticket ID (e.g., "FEAT-123")
 */
id: string, 
/**
 * Ticket title from markdown heading
 */
title: string, 
/**
 * Ticket type key (e.g., "FEAT", "FIX", or any custom type)
 */
type: string, 
/**
 * Current status
 */
status: VsCodeTicketStatus, 
/**
 * Path to the ticket markdown file
 */
filePath: string, 
/**
 * Terminal name if in-progress (e.g., "op-FEAT-123")
 */
terminalName?: string, };
