// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ticket status in the workflow
 */
export type VsCodeTicketStatus = "in-progress" | "queue" | "completed";
