// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Health check response from webhook server
 */
export type VsCodeHealthResponse = { 
/**
 * Health status (always "ok" when healthy)
 */
status: string, 
/**
 * Extension version
 */
version: string, 
/**
 * Port the server is listening on
 */
port: number, };
