// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Terminal activity state
 */
export type VsCodeActivityState = "idle" | "running" | "unknown";
