// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error response from webhook server
 */
export type VsCodeErrorResponse = { 
/**
 * Error message
 */
error: string, };
