// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VsCodeModelOption } from "./VsCodeModelOption";

/**
 * Launch options for starting an agent on a ticket
 */
export type VsCodeLaunchOptions = { 
/**
 * Model to use (sonnet, opus, haiku)
 */
model: VsCodeModelOption, 
/**
 * YOLO mode - auto-accept all prompts
 */
yoloMode: boolean, 
/**
 * Resume from existing session (uses session_id from ticket)
 */
resumeSession: boolean, };
