// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Session discovery file written to .tickets/operator/vscode-session.json
 * Used by Operator to discover the extension's webhook server.
 */
export type VsCodeSessionInfo = { 
/**
 * Wrapper type identifier (always "vscode")
 */
wrapper: string, 
/**
 * Actual port the webhook server is listening on
 */
port: number, 
/**
 * Process ID of VS Code
 */
pid: number, 
/**
 * Extension version
 */
version: string, 
/**
 * ISO timestamp when server started
 */
startedAt: string, 
/**
 * Workspace folder path
 */
workspace: string, };
