// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Generic success response
 */
export type VsCodeSuccessResponse = { 
/**
 * Whether the operation succeeded
 */
success: boolean, 
/**
 * Optional terminal name (for create operations)
 */
name?: string, };
