// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Model options for Claude CLI
 */
export type VsCodeModelOption = "sonnet" | "opus" | "haiku";
