// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parsed ticket metadata from YAML frontmatter
 */
export type VsCodeTicketMetadata = { 
/**
 * Ticket ID
 */
id: string, 
/**
 * Current status
 */
status: string, 
/**
 * Current step name
 */
step: string, 
/**
 * Priority level
 */
priority: string, 
/**
 * Project name
 */
project: string, 
/**
 * Session UUIDs by step name
 */
sessions?: { [key in string]?: string }, 
/**
 * Git worktree path if using per-ticket worktrees
 */
worktreePath?: string, 
/**
 * Git branch name
 */
branch?: string, };
