// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VsCodeActivityState } from "./VsCodeActivityState";

/**
 * State of a managed terminal
 */
export type VsCodeTerminalState = { 
/**
 * Terminal name
 */
name: string, 
/**
 * Process ID if available
 */
pid?: number, 
/**
 * Current activity state
 */
activity: VsCodeActivityState, 
/**
 * Unix timestamp when terminal was created (milliseconds)
 */
createdAt: number, };
