// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Terminal exists check response
 */
export type VsCodeExistsResponse = { 
/**
 * Whether the terminal exists
 */
exists: boolean, };
