// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Options for creating a new terminal
 */
export type VsCodeTerminalCreateOptions = { 
/**
 * Terminal name (e.g., "op-FEAT-123")
 */
name: string, 
/**
 * Working directory for the terminal
 */
workingDir?: string, 
/**
 * Environment variables to set
 */
env?: { [key in string]?: string }, };
