// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to send a command to a terminal
 */
export type VsCodeSendCommandRequest = { 
/**
 * Command to execute
 */
command: string, };
