// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Webhook notification configuration.
 */
export type WebhookConfig = { 
/**
 * Optional name for this webhook (for logging)
 */
name: string | null, 
/**
 * Whether this webhook is enabled
 */
enabled: boolean, 
/**
 * Webhook URL
 */
url: string, 
/**
 * Authentication type: "bearer" or "basic"
 */
auth_type: string | null, 
/**
 * Environment variable containing the bearer token
 */
token_env: string | null, 
/**
 * Username for basic auth
 */
username: string | null, 
/**
 * Environment variable containing the password for basic auth
 */
password_env: string | null, 
/**
 * Events to send (empty = all events)
 */
events: Array<string> | null, };
