// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SupportStatus } from "./SupportStatus";

/**
 * One workflow export format operator can emit, for `GET /api/v1/workflow-formats`.
 *
 * A projection of [`WorkflowFormat`] joined to its `Workflows` catalog entry —
 * the single source of truth for the format's [`SupportStatus`] and docs. Lets
 * the UIs render a format picker without hardcoding the list.
 */
export type WorkflowFormatDto = { 
/**
 * Stable slug (e.g. "claude", "agnt") — the value the `format` query param takes.
 */
slug: string, 
/**
 * Display label (e.g. "Claude Workflow").
 */
label: string, 
/**
 * File extension of the emitted artifact, no leading dot (e.g. "js", "json").
 */
extension: string, 
/**
 * Official support / maturity status (from the catalog).
 */
status: SupportStatus, 
/**
 * Absolute docs URL, or `null` if undocumented.
 */
docs_url: string | null, };
