// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Descriptive workflow hints for a collection (v1: metadata only).
 */
export type WorkflowHintsDto = { loop_kind: string | null, memory_surfaces: Array<string>, review_gates: Array<string>, external_tools: Array<string>, stop_conditions: Array<string>, runner_semantics: string, };
