// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for exporting a ticket to a Claude dynamic workflow (`.js`).
 */
export type WorkflowExportResponse = { 
/**
 * The ticket the workflow was generated from.
 */
ticket_id: string, 
/**
 * The issue type key that supplied the step structure.
 */
issuetype_key: string, 
/**
 * Suggested filename for saving the workflow (`<ticket-id>.workflow.js`).
 */
suggested_filename: string, 
/**
 * The generated `.js` workflow source.
 */
contents: string, };
