// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for a *preview* workflow generated from an issue type alone (no
 * concrete ticket). Used by the UI to visualize an issue type's workflow shape.
 */
export type WorkflowPreviewResponse = { 
/**
 * The issue type key the preview was generated from.
 */
issuetype_key: string, 
/**
 * Suggested filename for saving the preview (`<KEY>.preview.workflow.js`).
 */
suggested_filename: string, 
/**
 * The generated `.js` workflow source (placeholder ticket values).
 */
contents: string, };
