// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for writing an `OpenSpec` instance config section.
 */
export type WriteOpenspecConfigBody = { 
/**
 * Instance name, used as the `[kanban.openspec.<instance>]` key
 */
instance: string, 
/**
 * Directory containing the `OpenSpec` `changes/` tree
 */
root_path: string, 
/**
 * Operator project stamped on imported tickets (optional)
 */
project?: string | null, };
