// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WriteGitConfigResponse = { provider: string, token_env: string, shell_export_block: string, username?: string | null, };
