// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KanbanStatusMapping } from "./KanbanStatusMapping";

/**
 * Body for writing a Jira project config section.
 */
export type WriteJiraConfigBody = { domain: string, email: string, api_key_env: string, project_key: string, sync_user_id: string, 
/**
 * Mapping of operator todo/doing/done to external board columns
 */
status_mapping?: KanbanStatusMapping | null, };
