// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for writing a GitHub Projects v2 config section.
 */
export type WriteGithubConfigBody = { 
/**
 * GitHub owner login (user or org), used as the workspace key
 */
owner: string, 
/**
 * Env var name where the project-scoped token is set
 * (default: `OPERATOR_GITHUB_TOKEN`). MUST be distinct from `GITHUB_TOKEN`
 * — see Token Disambiguation in the kanban github docs.
 */
api_key_env: string, 
/**
 * `GraphQL` project node ID (e.g., `PVT_kwDOABcdefg`)
 */
project_key: string, 
/**
 * Numeric GitHub `databaseId` of the user whose items to sync
 */
sync_user_id: string, };
