// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response after writing a kanban config section.
 */
export type WriteKanbanConfigResponse = { 
/**
 * Filesystem path that was written (e.g., ".tickets/operator/config.toml")
 */
written_path: string, 
/**
 * Header of the top-level section that was upserted
 * (e.g., `[kanban.jira."acme.atlassian.net"]`)
 */
section_header: string, };
