// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KanbanProviderKind } from "./KanbanProviderKind";
import type { WriteGithubConfigBody } from "./WriteGithubConfigBody";
import type { WriteJiraConfigBody } from "./WriteJiraConfigBody";
import type { WriteLinearConfigBody } from "./WriteLinearConfigBody";

/**
 * Request to write or upsert a kanban config section.
 *
 * This endpoint does NOT take the secret — only the env var NAME
 * (`api_key_env`). The secret is set via `/api/v1/kanban/session-env`.
 */
export type WriteKanbanConfigRequest = { provider: KanbanProviderKind, jira: WriteJiraConfigBody | null, linear: WriteLinearConfigBody | null, github: WriteGithubConfigBody | null, };
