// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DelegatorLaunchConfig } from "./DelegatorLaunchConfig";

/**
 * The Operator-namespaced half of an [`AgentProfile`] — the fields a Delegator
 * carries that have no shared-core equivalent. AGNT ignores this bag; Operator
 * round-trips it losslessly.
 */
export type XOperator = { 
/**
 * Optional display name for UI.
 */
display_name: string | null, 
/**
 * Arbitrary model properties (e.g. `reasoning_effort`, sandbox).
 */
model_properties: { [key in string]?: string }, 
/**
 * Name of a declared `ModelServer` (`None` = implicit vendor default).
 */
model_server: string | null, 
/**
 * Launch configuration (permission mode, flags, worktree/docker, prompt
 * wrapping, ...).
 */
launch_config: DelegatorLaunchConfig | null, };
