// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DelegatorLaunchConfig } from "./DelegatorLaunchConfig";
import type { GitExecutionConfig } from "./GitExecutionConfig";

/**
 * The Operator-namespaced half of an [`AgentProfile`] — the fields a Delegator
 * carries that have no shared-core equivalent.
 */
export type XOperator = { 
/**
 * Optional Git identity, HTTPS credential reference, and runtime settings.
 */
git?: GitExecutionConfig | null, 
/**
 * Optional display name for UI.
 */
display_name?: string | null, 
/**
 * Arbitrary model properties (e.g. `reasoning_effort`, sandbox).
 */
model_properties?: { [key in string]: string }, 
/**
 * Name of a declared `ModelServer` (`None` = implicit vendor default).
 */
model_server?: string | null, 
/**
 * Launch configuration (permission mode, flags, worktree/docker, prompt
 * wrapping, ...).
 */
launch_config?: DelegatorLaunchConfig | null, };
