// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * YOLO (auto-accept) mode configuration for fully autonomous execution
 */
export type YoloConfig = { 
/**
 * Whether YOLO mode option is available in launch dialog
 */
enabled: boolean, };
