// @generated by `trust vendor` from untra-trust a8fac3142170fe7aebeb5c556500605000e88732-dirty
// source: trust-core/src/vendored.rs
// sha256: 23aeb017215667af15f957915fc1f93fb139c0913305b39f2cfe6b792d351e3b
//
// DO NOT EDIT. This file is generated, and three repositories carry
// byte-identical copies so they cannot drift apart on what a valid
// license is. Local edits here become a divergence nobody sees until a
// license is rejected in the field.
//
// To change it: edit trust-core/src/vendored.rs in untra-trust, then
// regenerate here and in every other consumer:
//     trust vendor --out src/trust_verify.rs
//     trust vectors --out testdata/trust-vectors.json

//! Verification of untra software licenses against a root of trust.
//!
//! **This file is copied verbatim into every consuming repository** by
//! `trust vendor`. Two constraints follow from that, and breaking either one
//! breaks every consumer at once:
//!
//! 1. It must be self-contained. No `use crate::...`, no reference to any other
//!    module in this workspace — it has to compile when dropped into a crate
//!    that has never heard of `trust-core`.
//! 2. It must carry no `#[cfg(test)]` code. A consumer runs its own `cargo
//!    test`, and tests referencing fixtures that do not exist there would fail
//!    to compile. This crate's tests live in `tests.rs` and exercise these exact
//!    bytes.
//!
//! Its only dependencies are `base64`, `serde`, `serde_json` and `jsonwebtoken`
//! — deliberately not `thiserror`, so vendoring imposes as little as possible on
//! a consumer's manifest.

use std::collections::BTreeMap;

use base64::engine::general_purpose::STANDARD;
use base64::Engine;
use serde::de::DeserializeOwned;
use serde::{Deserialize, Serialize};

/// Raw Ed25519 public key length. Keys travel as standard-base64 of these bytes,
/// matching the encoding the license registry uses for its `public_keys` map.
pub const PUBLIC_KEY_BYTES: usize = 32;

/// Envelope format version. Bumped only for a breaking change to the wrapper
/// itself, never for a change to the claims inside either token.
pub const ENVELOPE_VERSION: u32 = 1;

/// Upper bound on an encoded license key. Two JWTs and a small wrapper are well
/// under this; the cap exists so a hostile input cannot force a large allocation
/// before any signature has been checked.
pub const MAX_ENVELOPE_BYTES: usize = 32 * 1024;

/// Claim-set version for the attestation itself.
pub const ATTESTATION_VERSION: u32 = 1;

/// Fixed issuer and audience. Platform-wide constants rather than per-product
/// configuration, so a token minted for some other purpose can never be replayed
/// as a signing delegation.
pub const ATTESTATION_ISSUER: &str = "untra-root";
pub const ATTESTATION_AUDIENCE: &str = "untra-trust";

/// The only purpose this code will honour. A future purpose (say, telemetry
/// signing) must not be accepted as authority to sign licenses.
pub const PURPOSE_LICENSE_SIGNING: &str = "license-signing";

/// Why a license was not trusted.
///
/// No variant carries key material or token bytes: these strings reach logs and
/// user-facing surfaces, and a rejection reason must never leak what was
/// rejected.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TrustError {
    MalformedEnvelope,
    UnsupportedEnvelopeVersion,
    MalformedKeyring,
    MalformedKey,
    KeyGeneration,
    AttestationRejected,
    MissingKeyId,
    UnknownRoot,
    ProductMismatch,
    KeyMismatch,
    UnsupportedAlgorithm,
    LicenseRejected,
}

impl TrustError {
    /// A stable identifier for this rejection.
    ///
    /// The conformance vectors assert on these strings, and every consuming
    /// repository asserts against those vectors — so a code is contract. The
    /// `Display` message above is for humans and may be reworded; this may not.
    pub fn code(&self) -> &'static str {
        match self {
            Self::MalformedEnvelope => "malformed_envelope",
            Self::UnsupportedEnvelopeVersion => "unsupported_envelope_version",
            Self::MalformedKeyring => "malformed_keyring",
            Self::MalformedKey => "malformed_key",
            Self::KeyGeneration => "key_generation",
            Self::AttestationRejected => "attestation_rejected",
            Self::MissingKeyId => "missing_key_id",
            Self::UnknownRoot => "unknown_root",
            Self::ProductMismatch => "product_mismatch",
            Self::KeyMismatch => "key_mismatch",
            Self::UnsupportedAlgorithm => "unsupported_algorithm",
            Self::LicenseRejected => "license_rejected",
        }
    }
}

impl std::fmt::Display for TrustError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let message = match self {
            Self::MalformedEnvelope => "license is not a valid envelope",
            Self::UnsupportedEnvelopeVersion => "unsupported license envelope version",
            Self::MalformedKeyring => "malformed trust root keyring",
            Self::MalformedKey => "malformed verification key",
            Self::KeyGeneration => "key generation failed",
            Self::AttestationRejected => "license attestation was rejected",
            Self::MissingKeyId => "license attestation names no trust root",
            Self::UnknownRoot => "license attestation was signed by an untrusted root",
            Self::ProductMismatch => "license attestation is for a different product",
            Self::KeyMismatch => "license was not signed by the attested key",
            Self::UnsupportedAlgorithm => "unsupported signature algorithm",
            Self::LicenseRejected => "license signature or claims were rejected",
        };
        f.write_str(message)
    }
}

impl std::error::Error for TrustError {}

/// The trust roots a client is willing to accept attestations from.
///
/// A map rather than a single key so a root can be rotated: ship a release
/// trusting both roots, then start attesting under the new one.
///
/// `Hash` is part of the contract, not incidental. Consumers memoise
/// verification and must fold the keyring into their cache key, or a rotated
/// root is answered from a stale entry. Iteration order is the `BTreeMap`'s, so
/// the hash depends on the roots themselves and not on how they were parsed.
/// It is a process-local value: do not persist it or compare it across builds.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct RootKeyring {
    keys: BTreeMap<String, Vec<u8>>,
}

impl RootKeyring {
    /// Parses a `{"<root-kid>": "<standard-base64 raw 32-byte key>"}` map, the
    /// same shape consumers bake in at build time.
    pub fn from_json(json: &str) -> Result<Self, TrustError> {
        let encoded: BTreeMap<String, String> =
            serde_json::from_str(json).map_err(|_| TrustError::MalformedKeyring)?;

        let mut keys = BTreeMap::new();
        for (kid, value) in encoded {
            let bytes = STANDARD
                .decode(value.trim())
                .map_err(|_| TrustError::MalformedKey)?;
            if bytes.len() != PUBLIC_KEY_BYTES {
                return Err(TrustError::MalformedKey);
            }
            keys.insert(kid, bytes);
        }
        Ok(Self { keys })
    }

    pub fn get(&self, kid: &str) -> Option<&[u8]> {
        self.keys.get(kid).map(Vec::as_slice)
    }

    pub fn is_empty(&self) -> bool {
        self.keys.is_empty()
    }
}

/// A license as it is handed to a customer: the license JWT together with the
/// root-signed attestation for the key that signed it.
///
/// Both travel together so verification stays entirely offline — a client never
/// fetches a key to validate a license.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Envelope {
    pub v: u32,
    pub lic: String,
    pub att: String,
}

impl Envelope {
    pub fn new(license: String, attestation: String) -> Self {
        Self {
            v: ENVELOPE_VERSION,
            lic: license,
            att: attestation,
        }
    }

    /// Standard-base64 of the JSON wrapper. Base64-wrapping keeps the license
    /// key a single opaque line a customer can paste.
    pub fn encode(&self) -> String {
        STANDARD.encode(serde_json::to_vec(self).expect("envelope serializes"))
    }

    pub fn decode(license_key: &str) -> Result<Self, TrustError> {
        let trimmed = license_key.trim();
        if trimmed.len() > MAX_ENVELOPE_BYTES {
            return Err(TrustError::MalformedEnvelope);
        }

        let bytes = STANDARD
            .decode(trimmed)
            .map_err(|_| TrustError::MalformedEnvelope)?;
        let envelope: Self =
            serde_json::from_slice(&bytes).map_err(|_| TrustError::MalformedEnvelope)?;

        if envelope.v != ENVELOPE_VERSION {
            return Err(TrustError::UnsupportedEnvelopeVersion);
        }
        Ok(envelope)
    }
}

/// The root-signed statement that delegates license signing to a product key.
///
/// It says: "the root trusts key `kid`, whose public half is `pub`, to sign
/// licenses for product `sub`, between `nbf` and `exp`." It is the only thing
/// standing between a baked root key and a license signature, which is why every
/// field is checked rather than merely parsed.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AttestationClaims {
    pub version: u32,
    pub iss: String,
    pub aud: String,
    /// The product this key may sign for.
    pub sub: String,
    pub purpose: String,
    /// The key being attested.
    pub kid: String,
    /// Standard-base64 raw 32-byte Ed25519 public key.
    #[serde(rename = "pub")]
    pub public_key: String,
    pub iat: i64,
    pub nbf: i64,
    pub exp: i64,
}

/// What the caller expects this license to be. `issuer` and `audience` are
/// per-product, so they are supplied rather than assumed.
pub struct LicensePolicy<'a> {
    pub product: &'a str,
    pub issuer: &'a str,
    pub audience: &'a str,
}

/// A root-signed delegation whose signature and claims have been checked.
///
/// Exposed because a license service must verify its *own* attestation at
/// startup, before it holds any license to verify — and must fail to start
/// rather than sign licenses nobody can validate.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VerifiedAttestation {
    /// The product this key may sign licenses for.
    pub product: String,
    /// The key this attestation delegates to.
    pub signing_kid: String,
    /// The attested key, raw 32 bytes.
    pub signing_public_key: Vec<u8>,
    pub not_before: i64,
    pub expires_at: i64,
}

impl VerifiedAttestation {
    /// The attested key in the standard-base64 raw-32-byte form the product
    /// registry stores, re-encoded so a comparison is on value rather than text.
    pub fn signing_public_key_b64(&self) -> String {
        STANDARD.encode(&self.signing_public_key)
    }
}

/// A license whose signature chain has been checked, with the claims projected
/// into the caller's own type.
///
/// Deliberately **time-independent**: nothing here consults a clock. Callers
/// memoise verification against file contents (Operator does), and folding the
/// clock in would let a cached verdict outlive the trust that produced it.
/// `attestation_expires_at` is returned so the caller's own clock check can
/// respect it — see [`VerifiedLicense::effective_expiry`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VerifiedLicense<C> {
    pub claims: C,
    pub signing_kid: String,
    pub attestation_not_before: i64,
    pub attestation_expires_at: i64,
}

impl<C> VerifiedLicense<C> {
    /// The earlier of the license's own expiry and the attestation's. A license
    /// cannot outlive the delegation that authorised its signature.
    pub fn effective_expiry(&self, license_expires_at: i64) -> i64 {
        license_expires_at.min(self.attestation_expires_at)
    }
}

/// Verifies a license key's full chain: root -> attestation -> license.
///
/// Performs no clock checks. See [`VerifiedLicense`] for why, and
/// [`VerifiedLicense::effective_expiry`] for what a caller must fold into its own.
pub fn verify_license<C: DeserializeOwned>(
    license_key: &str,
    roots: &RootKeyring,
    policy: &LicensePolicy<'_>,
) -> Result<VerifiedLicense<C>, TrustError> {
    let envelope = Envelope::decode(license_key)?;
    let attestation = verify_attestation(&envelope.att, roots, policy.product)?;
    let claims = verify_signed_license(&envelope.lic, &attestation, policy)?;

    Ok(VerifiedLicense {
        claims,
        signing_kid: attestation.signing_kid,
        attestation_not_before: attestation.not_before,
        attestation_expires_at: attestation.expires_at,
    })
}

/// Verifies a root-signed attestation on its own.
///
/// Like [`verify_license`], this consults no clock: it returns the validity
/// window for the caller to check. A caller that needs the attestation to cover
/// a term must compare `expires_at` against its own longest term.
pub fn verify_attestation(
    token: &str,
    roots: &RootKeyring,
    product: &str,
) -> Result<VerifiedAttestation, TrustError> {
    let header = jsonwebtoken::decode_header(token).map_err(|_| TrustError::AttestationRejected)?;
    // Pinned, never read from the token: honouring the token's own algorithm
    // would let an attacker HMAC-sign with the root's public key as the secret.
    if header.alg != jsonwebtoken::Algorithm::EdDSA {
        return Err(TrustError::UnsupportedAlgorithm);
    }
    let root_kid = header.kid.ok_or(TrustError::MissingKeyId)?;
    let root_key = roots.get(&root_kid).ok_or(TrustError::UnknownRoot)?;

    let mut validation = jsonwebtoken::Validation::new(jsonwebtoken::Algorithm::EdDSA);
    validation.set_issuer(&[ATTESTATION_ISSUER]);
    validation.set_audience(&[ATTESTATION_AUDIENCE]);
    validation.set_required_spec_claims(&["iss", "aud", "sub", "exp", "nbf", "iat"]);
    validation.validate_exp = false;
    validation.validate_nbf = false;

    let claims = jsonwebtoken::decode::<AttestationClaims>(
        token,
        &jsonwebtoken::DecodingKey::from_ed_der(root_key),
        &validation,
    )
    .map_err(|_| TrustError::AttestationRejected)?
    .claims;

    if claims.version != ATTESTATION_VERSION
        || claims.purpose != PURPOSE_LICENSE_SIGNING
        || claims.kid.is_empty()
        || claims.nbf < claims.iat
        || claims.exp <= claims.nbf
    {
        return Err(TrustError::AttestationRejected);
    }
    if claims.sub != product {
        return Err(TrustError::ProductMismatch);
    }

    let signing_public_key = STANDARD
        .decode(claims.public_key.trim())
        .map_err(|_| TrustError::MalformedKey)?;
    if signing_public_key.len() != PUBLIC_KEY_BYTES {
        return Err(TrustError::MalformedKey);
    }

    Ok(VerifiedAttestation {
        product: claims.sub,
        signing_kid: claims.kid,
        signing_public_key,
        not_before: claims.nbf,
        expires_at: claims.exp,
    })
}

fn verify_signed_license<C: DeserializeOwned>(
    token: &str,
    attestation: &VerifiedAttestation,
    policy: &LicensePolicy<'_>,
) -> Result<C, TrustError> {
    let header = jsonwebtoken::decode_header(token).map_err(|_| TrustError::LicenseRejected)?;
    if header.alg != jsonwebtoken::Algorithm::EdDSA {
        return Err(TrustError::UnsupportedAlgorithm);
    }
    let kid = header.kid.ok_or(TrustError::MissingKeyId)?;
    if kid != attestation.signing_kid {
        return Err(TrustError::KeyMismatch);
    }

    let mut validation = jsonwebtoken::Validation::new(jsonwebtoken::Algorithm::EdDSA);
    validation.set_issuer(&[policy.issuer]);
    validation.set_audience(&[policy.audience]);
    // `exp` must be present even though this layer does not compare it to a
    // clock, so a token with no expiry can never be treated as a license.
    validation.set_required_spec_claims(&["iss", "aud", "exp"]);
    validation.validate_exp = false;
    validation.validate_nbf = false;

    Ok(jsonwebtoken::decode::<C>(
        token,
        &jsonwebtoken::DecodingKey::from_ed_der(&attestation.signing_public_key),
        &validation,
    )
    .map_err(|_| TrustError::LicenseRejected)?
    .claims)
}
